### ISSUE TITLE
Parsing of external file with option excludeFrom

### ISSUE THREAD

**Issue by cappellaiomatto** [axkibe/lsyncd#105]
We have a three nodes web cluster running ubuntu 11.10 and after extensive testing we migrated the /www folder from ocfs to lsyncd 2.0.4.

The setup uses default.rsyncssh and from each node is possible to login to
the other two nodes via ssh without password.

The rsync exclusion list is stored in a file having the following contents:

> cat /etc/lsyncd/rsync-exclude.txt
> .ipc_in
> .ipc_out
> logs/
> .scratch/
> .nfs000*
> lost+found/
> Thumbs.db

If the above file contains at the end an extra newline with tab character

the following rsyncOps (--exclude-from explicitly set as a rsync option) works fine:

rsyncOps= {
          "-ltspog", 
          "--numeric-ids", 
          "--bwlimit=10000", 
          "--exclude-from=/etc/lsyncd/rsync-exclude.txt"
}

The following setup doesn't work:

excludeFrom="/etc/lsyncd/rsync-exclude.txt",
rsyncOps= {
          "-ltspog", 
          "--numeric-ids", 
          "--bwlimit=10000"
}

The service starts but no folder is monitored:

the file 
/var/log/lsyncd-status.log

contains
"Inotify watching 0 directories"

instead of 
"Inotify watching 3571 directories"

**Comment by dmig** [comment]
I use version 2.1.5 and was just bitten by this bug. Doesn't seem to be fixed.

I my case exclude file contained a newline at the end.

**Comment by axkibe** [comment]
The above patch has been merged and is part of 2.1.6

**Comment by dmig** [comment]
Oh, I see. Do you have ppa with fresh builds?

**Comment by axkibe** [comment]
no, sorry

**Comment by ElliotNB** [comment]
@dmig Wow, thank you for pointing that out. I had the same problem and modifying the exclude file to remove the two new lines at the end fixed it. I doubt I would've been able to figure that on my own.
