### ISSUE TITLE
Doc-Problem (?): Exclusion Lists

### ISSUE THREAD

**Issue by raimi** [axkibe/lsyncd#125]
Hello again!

While lsyncing a live courier Maildir filesystem I try to exclude some files and folders that are basically transient. I think the documentation needs some more explaination and/or some examples. I cannot reconstruct it from the Lua sources, unfortunately.
Example:

``` lua
sync {
   default.rsync,
   source = "/foo/courier",
   target = "root@standby::foo/courier",
   rsyncOpts = "-slptgoDAX",
   exclude = { "*/tmp/*", "*/.Spam/*", "courier.lock"},
   init = false
}
```

1) An example for the LIST syntax would be nice, since this list/map-mixture is not intuitive on first glance :)

2) The above example works, but I actually want to anchor the patterns since the fs layout is known. What I cannot tell is which path is matched against the pattern: Consider the absolute path "/foo/courier/raimi/.Spam/". Is the exclude pattern matched against "/raimi/.Spam/" (cutting of the source "/foo/courier") or is it matched against the absolute path name?

Once this is clarified, I will open an issue if it does not work as intended :)

**Comment by axkibe** [comment]
I'm closing this for now, this is now 6 years ago, and I suppose many things have moved on since then.

The documentation has been improved on this as well.
