### ISSUE TITLE
No way to use ssh's identity_file option, ssh port, and get rsyncssh to work

### ISSUE THREAD

**Issue by archon810** [axkibe/lsyncd#180]
Using 2.1.4 here, taking a 2nd go at lsyncd to sync multiple servers.

I am not using a password file (or password auth altogether), but I do have a key file that doesn't need a password. It is passed to rsync as follows: -e "/usr/bin/ssh -p 222 -i /root/.ssh/id_rsa_pwl -o StrictHostKeyChecking=no"

Note that I'm also using an alternate ssh port.

As far as I can tell, you can set port in ssh = {} now. But in order to set the -i option, I need to use _extra for either rsync or ssh.

If I use 
 ssh = {
   port = 222,
    _extra = {"-i", "/root/.ssh/id_rsa_pwl"}
  }
it doesn't even read the -i option. I tried a few variations but couldn't get it to work at all.

If I use 
rsync = {
    archive = true,
    verbose = true,
    _extra = {"-P", "-e", "/usr/bin/ssh -p 222 -i /root/.ssh/id_rsa_pwl -o StrictHostKeyChecking=no"}
  },
it actually does work for the initial sync, but any subsequent sync tries to use port 22 for some reason.

If I set both the rsync._extra with the -e option and the sync.port option, lsyncd just chokes right away:
02:28:57 Normal: recursive startup rsync: /tmp/lsyncdtest/ -> spire:/tmp/lsyncdtest/
rsync: Failed to exec --rsh=ssh: No such file or directory (2)
rsync error: error in IPC code (code 14) at pipe.c(84) [sender=3.0.9]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in IPC code (code 14) at io.c(605) [sender=3.0.9]
02:28:57 Error: Temporary or permanent failure on startup of "/tmp/lsyncdtest/". Terminating since "insist" is not set.

So, how can I make this work?

**Comment by axkibe** [comment]
I guess we can drop this?
