### ISSUE TITLE
2.1 Layer 3 Config page error

### ISSUE THREAD

**Issue by wytcld** [axkibe/lsyncd#182]
At https://github.com/axkibe/lsyncd/wiki/Lsyncd%202.1.x%20%E2%80%96%20Layer%203%20Config%20%E2%80%96%20Simple%20onAction it has a table claiming to be "All possible variables" which does not include a variable given in an example above that on the page, "^sourceName". Are there other omissions?

**Comment by axkibe** [comment]
The example was wrong. "sourceName" was used before, it was changed since it was a confusing terminiology. Fixed in the contemporary Manual:

https://axkibe.github.io/lsyncd/manual/config/layer3/
