### ISSUE TITLE
how to break full sync at startup?

### ISSUE THREAD

**Issue by guobinchn** [axkibe/lsyncd#188]
I am testing lsyncd,and is cool,i have a question：

Only real-time synchronization, unnecessary full sync after startup?

**Comment by RorschachChan** [comment]
when i change "init=false" to "init=true",and "/etc/init.d/lsyncd restart".i find that failed,and the log showing like this:

Mon Apr 23 19:01:55 2018 Normal: --- TERM signal, fading ---
Mon Apr 23 19:01:57 2018 Error: in Lua: lsyncd.lua:1962: attempt to call field 'init' (a boolean value)
Mon Apr 23 19:01:57 2018 Error: Backtrace 1 :lsyncd.lua:1962
Mon Apr 23 19:01:57 2018 Error: Backtrace 1 :lsyncd.lua:1962
Mon Apr 23 19:01:57 2018 Error: Backtrace 2 :lsyncd.lua:3511

where am i wrong?

**Comment by axkibe** [comment]
"init" must either be unset (then default behavior applies), a function (then your function is executed see documentation to Layer 1), or false then nothing is done. "true" is not a valid option.

**Comment by RorschachChan** [comment]
thank U ,that worked !!!!
