### ISSUE TITLE
how to execute commands before/after every sync operation

### ISSUE THREAD

**Issue by ndemou** [axkibe/lsyncd#208]
I want to execute a command on the remote/slave host before and another after every sync operation (rsync,delete or move). I found an example for executing commands after (lpostcmd.lua) but nothing for executing commands before.

Nick

---

The reason I want this is that I'm syncing code from my master PC to a few slave hosts. But from time to time I will accidentally edit code on a slave host thinking I'm on the master. Having all the code being non writable on slaves helps me avoid this trap.

**Comment by axkibe** [comment]
Here's documented a general suggestion for custom pre/post stuff:

http://axkibe.github.io/lsyncd/faq/postscript/

**Comment by ndemou** [comment]
Thanks Axel. Pretty nice solution.

**Comment by doppelweber** [comment]
Hello, with the solution from http://axkibe.github.io/lsyncd/faq/postscript/
i can execute bash commands "after" sync.
Where or how do i place a bash command to fire it up "before" the sync?
Any idea?

m@rko

**Comment by t0mtaylor** [comment]
Latest url here - https://lsyncd.github.io/lsyncd/faq/postscript/
