### ISSUE TITLE
if one job fails lsyncd dies

### ISSUE THREAD

**Issue by ndemou** [axkibe/lsyncd#209]
One of my jobs begun failing on startup with these log messages: 

rsync error: protocol incompatibility (code 2) at compat.c(174) [sender=3.0.9]
23:05:13 Error: Failure on startup of "/home/ndemou/Dropbox/source/zanadoo/billing-code/bin/": 2
23:05:13 Error: Critical exitcode.

The error was indeed critical for this job but I would like lsyncd to go on with all other jobs. Instead it died after the "Error: Critical exitcode" message

**Comment by g980** [comment]
What is the yync confic. Is that /etc/lsyncd.conf?

If I write in to my /etc/lsyncd.conf:

rsyncExitCodes = {
        [   1 ] = 'ok'
}

, Lsyncd will not die when receiving exit code 1?
