### ISSUE TITLE
default.direct appears not to log

### ISSUE THREAD

**Issue by wytcld** [axkibe/lsyncd#211]
Was running 2.1.1 for months with default.rsync watching 555 directories. Mostly has worked well, but rsync a few times has ended up running overlapping processes and driving the system load up. Switched to using default.direct with the remote system's tree mounted via sshfs. Files are copied okay, but lsyncd.log, which remains specified in "settings" just as before, no longer is gaining entries. The 2.1 manual says "All parameters are just like default.rsync." Seems not the case with the log setting.

**Comment by alkisg** [comment]
> turning on/off logging categories is not yet supported in the config file. Sorry about that.

I too would like to feature-request that one!

As a workaround, in Ubuntu 20.04, this worked:

> echo 'DAEMON_ARGS="-pidfile ${PIDFILE} ${CONFIG} -log scarce -log Exec"' > /etc/default/lsyncd

Thank you for lsyncd!
