### ISSUE TITLE
examples/lpostcmd.lua fails checkgauge test

### ISSUE THREAD

**Issue by marcefr** [axkibe/lsyncd#216]
Using the examples/lpostcmd.lua fails with the following error:

Starting lsyncd: Error: error preparing /etc/lsyncd.conf: /etc/lsyncd.conf:89: Parameter "postcmd" unknown. (if this is not a typo add it to checkgauge)

how can I add postcmd to checkgauge in lpostcmd.lua?

Running from lsyncd-2.1.4-3.el5 rpm on centos 5.6.

**Comment by axkibe** [comment]
Sorry never having replied to it, this has been fixed for a while already.
