### ISSUE TITLE
Add more options for SSH binary

### ISSUE THREAD

**Issue by ajardan** [axkibe/lsyncd#217]
Please add the table ssh.options where multiple additional options can be specified for the SSH binary to be used on every sync.

Please also add an option ssh.key so an ssh key can be specified (-i /path/to/ssh_key)

**Comment by archon810** [comment]
Odd, I'm getting
```
Starting lsyncd: Error: error preparing /etc/lsyncd.lua: Parameter "ssh" unknown. (if this is not a typo add it to checkgauge)
```
