### ISSUE TITLE
Use lsyncd to be the Guard of Web Servers

### ISSUE THREAD

**Issue by zhaosanshi** [axkibe/lsyncd#223]
Hello everyone,

There are one CMS server, five Weblogic servers and ten Apache servers in our portal. I am using lsyncd to monitor the directories of CMS, and keep synchronization between the CMS and Apache servers through default.rsync.lua.

Besides, I am trying to use lsyncd to protect the files of Apache servers that nobody could add, delete or modify them. In other words, lsyncd should be also running on the Apache servers and monitor the directories. If somebody modify the files of Apache servers, lsyncd which is runing on Apache server will overwrite the modified files by the original files from CMS server immediately.

I modified the default-rsync.lua file with exchange between config.source and config.target in spawn functions as follow:

spawn(
        elist,
        config.rsync.binary,
        '<', filter0,
        config.rsync._computed,
        '-r',
        delete,
        '--force',
        '--from0',
        '--include-from=-',
        '--exclude=*',
        config.target,
        config.source
    )

Therefore, every Apache server will run lsyncd while CMS is runing it. the questions are:
1. the modification of above code could work well as the file guard on Apache servers?
2. the lsyncd on the apache servers and CMS could work well together?
3. Any suggestions.

Thanks a lot.

**Comment by axkibe** [comment]
Ya, fair enough to make it a pull whenever locally something changed.

By why don't you simply chmod it 000? So nobody can write to it?

Note that someone being malicious without enough rights to write the files in the first place has easy methods to work around such a guard. (E.g. simply stopping Lsyncd, or create a hard link to a file and modify the hard link, so Lsyncd doesn't get an event).

IMO there are already tools for this better suited, that calculate a hash code for config files and bug when something changed.
