### ISSUE TITLE
lsyncd watches ignored directories

### ISSUE THREAD

**Issue by mikehaertl** [axkibe/lsyncd#230]
Today i found out that lsyncd wasn't running anymore due to too low `max_user_watches`. After I increased that number about a factor 10, I looked at the status file to find out, what's going on.

There I found, that lsyncd is watching 100s of 1000s of my rsnapshot files, even though i have excluded them. Here's my config:

```
sync {
    default.rsync,
    source = "/home/",
    target = "maste0@slave.****.de::home",
    rsyncOpts = { "-a", "--del", "--password-file=/etc/****.master" },
    exclude = { "/home/backup", "/home/lost+found" }
}
```

The excludes are listed fine in the status file:

```
Excluding:
/home/backup
/home/lost+found
```

But below in the list of watched directories i see 1000s of lines like:

```
26647: /home/backup/snapshots/
26648: /home/backup/snapshots/weekly.3/
...
```

So this is wasting many inotify watches. Shouldn't it only watch non-ignored directories?

UPDATE:
My lsnycd version is 2.0.7-3.

**Comment by isarandi** [comment]
Just ran into the same issue. It would be nice to include in the manual that the excludes are relative to the watch root.
