### ISSUE TITLE
Install error when parse lsyncd.1.txt

### ISSUE THREAD

**Issue by notenking** [axkibe/lsyncd#233]
When I compile it with make,it's halt with this error:

make[1]: Entering directory `/tmp/lsyncd'
format=manpage doc/lsyncd.1.txt
doc/lsyncd.1.txt: line 1: syntax error near unexpected token`1'
doc/lsyncd.1.txt: line 1: `lsyncd(1)'
make[1]: [doc/lsyncd.1] error 2 (ingore)
make[1]: Leaving directory`/tmp/lsyncd' 

It's seem when parsing document of man page.

**Comment by axkibe** [comment]
The build system has been completely overhauled since this issue is filed. So I suppose/hope it is fixed by now.
