### ISSUE TITLE
Not detecting Lua on MacOs X

### ISSUE THREAD

**Issue by chironfly** [axkibe/lsyncd#240]
Getting the following on mac os x mountain lion. The problem is that there doesn't seem to be any .pc files for lua on the machine. I do have lua install via brew. My brew packages are:

$ brew list
asciidoc        automake        git         m4          pkg-config      terminal-notifier
autoconf        docbook         lua52           objective-caml      rsync           unison

The end of the configure script is:

Checking for luac51... no
checking for LUA... no
checking for lua... /usr/local/bin/lua
checking for luac... /usr/local/bin/luac
configure: error: Need a Lua toolchain with matching versions ('lua' library and 'lua' and 'luac' programs)

Any ideas?

**Comment by axkibe** [comment]
Since Lsyncd switched to cmake, the autotool issues should no longer apply.

If there are new cmake issues, please report them as new.
