### ISSUE TITLE
No support for multiple targets

### ISSUE THREAD

**Issue by rgeary1** [axkibe/lsyncd#241]
Hi,

I have a handful of machines I'd like to use lsyncd to update. I'd like to use one machine as a hub, syncing any changes to multiple targets, but specifying more than 1 target to lsyncd gives errors. Please could you add this feature?

Thanks

**Comment by djester** [comment]
Hi,

I need to delete files on source only after both target are synced. But there is delete option only within sync block. So, i cannot use loop (or many sync block) for multiple target configuration.

Could you advise solve this problem?
Thanks.
