### ISSUE TITLE
Lsync cant delete file on receiver

### ISSUE THREAD

**Issue by creotiv** [axkibe/lsyncd#251]
Here is my config
settings {
  logfile = "/var/log/lsyncd.log",
  statusFile = "/var/log/lsyncd-status.log",
  statusInterval = 20
}

sync {
  default.rsyncssh,
  source="/data/d3",
  host="fc2",
  targetdir="/data/d1",
  delay=5,
  ssh = {
    _extra={"-l testuser","-o GSSAPIAuthentication=no"}
  },
  rsync = {
     _extra = {"-odtgpvvv","--delete","--chmod=ugo=rwx"}
  }
}

When i create file on main server file successfully copied to the fc2 server. But when i delete file on main server lsync not deleting it on fc2 server an give such error:
Thu Nov 28 14:34:39 2013 Normal: Retrying (list): 255
Thu Nov 28 14:34:44 2013 Normal: Deleting list
/data/d1//test.txt
Permission denied, please try again.
Permission denied, please try again.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

i set directories on both ends to user "testuser" and set permissions to 0777

**Comment by vskubriev** [comment]
I resolved this issue when I removed ssh section. I suspect, that this section is written wrongly.

```
    ssh = {
      port = 22,
      _extra = {"-i","/root/.ssh/id_rsa.pub", "-l", "root"}
    },
```
