### ISSUE TITLE
lsyncd terminates randomly

### ISSUE THREAD

**Issue by phaseOne** [axkibe/lsyncd#254]
Lsyncd seems to terminate for no reason at times that I can't track down.

The last log item is:

```
Normal: waiting for 1 more child processes.
```

And there are hundreds of entries with the same exact datestamp (even seconds), then the daemon crashes.

**Comment by axkibe** [comment]
I'm sorry I wasn't there at the time to debug this out.

If this still happens with Lsyncd 2.1.6 please open a new issue.
