### ISSUE TITLE
lsyncd is copying partially written files

### ISSUE THREAD

**Issue by dwatzke** [axkibe/lsyncd#256]
Hi,

lsyncd copies the partially written files that are still being written to (e.g. they are open for writing, etc.) - I think there should be an option allowing that the open-for-write files won't be transferred until their file descriptors are closed. Current behavior is unacceptable for any use I can imagine :-/

Thanks

**Comment by schrauger** [comment]
This method causes corruption if two-way sync is set up. I've got a couple computers with lsync on them. Both sync to each other (load balanced servers).

So when lsync syncs a partial file that is still uploaded, the other server syncs the partial file back, and both end up with a corrupt file. At least, that is what seems to happen when a large file starts to copy over.

Any thoughts on a better method?

**Comment by piphoto** [comment]
I encountered the same problem. I solved it by using the rsync option to sync first to a temporary directory .  Then when the the file is fully written lsyncd moves the file to the final destination.

In your config file add to the sync /rsync part:

```
rsync {
           ...
           ...
           temp_dir = "path/to/your/temp"
```

**Comment by axkibe** [comment]
You should also set
```update = true```

**Comment by painfull30** [comment]
Hi from 2018 ))
I have same trouble with 2-way sync, with
	rsync = {
		temp_dir = "/tmp",
		_extra = { "-ausS" }
	}
still big-files (1mb+) which time2time OS fully re-write are thuncated
Nut fully clear how it happens, flow must be
1) lsync see file was changes
2) add to pending sync
3) start rsync
4) before rsync read file other app opens it for writing and thuncate (or lets say write 25% of file)
5) rsync read 25% and send to 2nd server (triple checked it - rsync really not check in-use files and not skip them)
===
I expected that on side1 file-close file will pushed in next-sync and 100% of file will sended, but it not happen.
FYI - On 30 servers we have this issue about 2-3 times per month
