### ISSUE TITLE
Unknown exitcode (list): 123

### ISSUE THREAD

**Issue by plouj** [axkibe/lsyncd#259]
I had lsyncd running for a good month with a few direct and rsyncssh targets before it suddenly died with the following messages:

```
...
10:44:21 Call: collectProcess( )
10:44:21 Delay: collected a list
10:44:21 Error: Unknown exitcode (list): 123
10:44:21 Error: Critical exitcode.
```

I know this isn't much to go on, but maybe someone can suggest some ways to debug this further?

**Comment by lhopwood** [comment]
We're also seeing this error crop up occasionally. In our case it occurs after an "rm: cannot remove `<name-of-dir>': Directory not empty" error.

`Thu Oct 22 10:34:34 2015 Error: Unknown exitcode (list): 123`
`Thu Oct 22 10:34:34 2015 Error: Critical exitcode.`

**Comment by axkibe** [comment]
I suppose this ought to be gone with 2.2.0 as  it doesn't do xargs removing anymore.

If it still happens with 2.2.0 make a new issue please.
