### ISSUE TITLE
post command after sync

### ISSUE THREAD

**Issue by markusweb** [axkibe/lsyncd#260]
i want to run a command after sync of a certain directory is finished.
background: i want to sync master and slave(s) and after sync of config files i want to restart eg. apache or haproxy on my slave(s).

lsyncd works perfect for a long time to sync directories. 

```
sync {
    default.rsync,
    source="/var/www",
    exclude= {
        "logs/*",
        "*.swp",
        "*~",
    },
    target="12.34.56.78:/var/www",
    rsync = {
        rsh="/usr/bin/ssh -l wwwuser ",
        verbose=true,
        compress=true,
        archive=true,
    },
    -- init = false,
}
```

but now i am looking for a way to run the "restart" after sync.

i tried lpostcmd.lua from example dir but i'll get the error:

Error: error preparing /opt/lsyncd/lsyncd.conf: default-rsync.lua:305: attempt to perform arithmetic on local 'level' (a nil value)

is there a "simpler" way to run a post-command?

thanxs markus

**Comment by JoseGoncalves** [comment]
Hi. I am running lsyncd 2.1.5 on Debian 8 and encountered the same issue.
Increasing the delay does not do the trick as the command is spawned for each file that is changed.
Any suggestions for a fix/workaround?
