### ISSUE TITLE
Lsyncd Not Excluding Swap Files

### ISSUE THREAD

**Issue by Schmoopy** [axkibe/lsyncd#262]
Lsyncd keeps syncing .swp files even though they are in the exclude list. I have tried multiple variants but nothing seems to work. It then gets stuck in a loop where the file appears on one server, then gets deleted, and then appears on the other - this goes on until the service is stopped.

Here are the exclude patterns:

. \* .swp
. \* .swpx
. \* .swx

For some reason when I post this the string it's being changed into (..), however there is no space between the asterisks and the dots in my file.

Could it be that the "." is interpreted instead of taken literally?

I have also tried just *swp but that doesn't work either. Is this a bug?

**Comment by axkibe** [comment]
If this is still an Issue with Lsyncd 2.1.6 please open a new issue.
