### ISSUE TITLE
lsyncd takes long time before it starts sync

### ISSUE THREAD

**Issue by BlackRavener** [axkibe/lsyncd#263]
I apologize if this is wrong place to post it, but the issue I'm seeing is this:

I have two sync's setup in configuration that takes one folder from my truecrypt volume and copies onto encrypted volume on NAS
and another sync that takes all folders from truecrypt volume, except the folder from above sync.
Total amount of data on truecrypt volume is about 160GB, about 4300 folders.

When lsyncd is first initiated after a boot it takes about an hour before it starts actually syncing source and target. Is it running a diff on source and target? Can this be improved?

**Comment by ashokarun** [comment]
*Just an update*

- Noticed this while setting up sync for two directories (100+ GB & 10000000+ files)

- Lsyncd daemon actually setting up "Inotify: addwatch" for all the directories (sub) to identify the changes for sync.

- This you can see by enabling log all. You can run/start the process with:

`#lsyncd -log all /etc/lsyncd.conf`

```
Mon Jul 13 17:47:38 2020 Inotify: addwatch( /dir/one/ )-> 134390
Mon Jul 13 17:47:38 2020 Function: Inotify.addWatch( /dir/one/  )
Mon Jul 13 17:47:38 2020 Inotify: addwatch( /dir/two/  )-> 134391
Mon Jul 13 17:47:38 2020 Function: Inotify.addWatch( /dir/two/  )
```
