### ISSUE TITLE
Some way of defining sync priority for files in a directory

### ISSUE THREAD

**Issue by pramttl** [axkibe/lsyncd#267]
`lsyncd` is really useful to push-sync a directory on server A with a directory on server B.  However, there is a common additional constraint in many use cases.
Files matching a certain regex pattern in server `A` must be synced before other files are synced. Eg. Syncing all binaries first and then syncing the source code, etc.

Can we do something like this using lsyncd? If not it will be really useful to have a way to do this.

**Comment by axkibe** [comment]
Sorry, I can't think of any remotely easy way to do this within the current design.
