### ISSUE TITLE
does FreeBSD can install lsyncd ?

### ISSUE THREAD

**Issue by axkibe** [axkibe/lsyncd#27]
Originally filed by fkk...@163.com on 2010-09-05T07:31:16

I try to install with lsyncd in FreeBSD 8, but faild.
I had installed: xinetd build libxml2.
any ideas?

the configure had ok, and make info is:
# make

make  all-am
if gcc -DHAVE_CONFIG_H -DXML_CONFIG -I. -I. -I.     -Wall  `xml2-config --cflags` -g -O2 -MT lsyncd.o -MD -MP -MF ".deps/lsyncd.Tpo"  -c -o lsyncd.o `test -f 'lsyncd.c' || echo './'`lsyncd.c;  then mv -f ".deps/lsyncd.Tpo" ".deps/lsyncd.Po";  else rm -f ".deps/lsyncd.Tpo"; exit 1;  fi
In file included from lsyncd.c:20:
inotify-nosys.h:15:24: error: asm/unistd.h: No such file or directory
In file included from lsyncd.c:20:
inotify-nosys.h:28: error: expected ':', ',', ';', '}' or '**attribute**' before '__flexarr'
inotify-nosys.h:155:3: error: #error "Unsupported architecture!"
inotify-nosys.h:158:3: error: #error "Unsupported architecture!"
inotify-nosys.h:161:3: error: #error "Unsupported architecture!"
inotify-nosys.h: In function 'inotify_init':
inotify-nosys.h:167: error: '__NR_inotify_init' undeclared (first use in this function)
inotify-nosys.h:167: error: (Each undeclared identifier is reported only once
inotify-nosys.h:167: error: for each function it appears in.)
inotify-nosys.h: In function 'inotify_add_watch':
inotify-nosys.h:172: error: '__NR_inotify_add_watch' undeclared (first use in this function)
inotify-nosys.h: In function 'inotify_rm_watch':
inotify-nosys.h:177: error: '__NR_inotify_rm_watch' undeclared (first use in this function)
lsyncd.c: At top level:
……

**Comment by JonathonReinhart** [comment]
It looks like someone did get this ported to FreeBSD: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=228714
