### ISSUE TITLE
One time sync

### ISSUE THREAD

**Issue by betaboon** [axkibe/lsyncd#271]
Hello,
I am trying to set up a sync task that is run first and blocks all other sync tasks before it is done. is that even possible ?

The setup i have in mind is as follows:
i have a ramdisk that should be populated from another partition on lsyncd startup. after that initial population it should be synced to that partition.

any ideas or hints?

**Comment by axkibe** [comment]
As far I understand the question, the answer is: this is how Lsyncd always operates.
