### ISSUE TITLE
Cannot follow destination file with tail -f

### ISSUE THREAD

**Issue by ubellavance** [axkibe/lsyncd#274]
Hi,

I'd like to use lsyncd to sync some log files to another server and be able to do a tail -f on a log file, but it looks like the tail command doesn't see when the file is updated.  I tried with -F but it reloads the whole file instead of just showing the new content.

**Comment by axkibe** [comment]
Added append and append_verify to Lsyncd 2.1.7

Whatever the difference between the two is, you need to ask the rsync people. I don't know.

**Comment by zffocussss** [comment]
use tail -F your_filename to keep track of the fresh content

**Comment by ubellavance** [comment]
> 
> 
> use tail -F your_filename to keep track of the fresh content

https://github.com/axkibe/lsyncd/issues/274#issuecomment-43098167
