### ISSUE TITLE
How to turn off the initial sync

### ISSUE THREAD

**Issue by KevinGideon** [axkibe/lsyncd#276]
Hello.
    I have two question. Could you help me for these?

1) Is there any option to turn off the initial sync when the lsyncd deamon process crash and restart ? You know, sometimes the watching directory is very large and will take a great time to finish the checksum for rsync. 

2) Is it possible to only sync the changed files not the directory?

**Comment by aisrael** [comment]
From https://github.com/axkibe/lsyncd/wiki/Lsyncd%202.1.x%20%E2%80%96%20Layer%204%20Config%20%E2%80%96%20Default%20Behavior:

>  One can also skip the initial rsync process by overriding the default `init` function with false:

**Comment by axkibe** [comment]
As aisrael said.

**Comment by swood** [comment]
Hello.

I'd like to ask you the same question. How can I turn off init synchronization? My storage is about 2Tb and I want to begin sync file as soon as possible and make rsync by hand.the

**Comment by axkibe** [comment]
The URL has changed, but the citation is still the same:
new URL: https://axkibe.github.io/lsyncd/manual/config/layer4/
old cite: One can also skip the initial rsync process by overriding the default init function with false:
