### ISSUE TITLE
--temp_dir wiil not working

### ISSUE THREAD

**Issue by alex-raven** [axkibe/lsyncd#277]
I have lsyncd version 2.1.5 but option temp_dir  will not working.
How i can use two-way sync?

My config:

settings = {
  logfile    = "/var/log/lsyncd/lsyncd.log",
  statusFile = "/var/log/lsyncd/lsyncd.status",
  nodaemon   = true, 
  statusInterval = 20
}

sync {
default.rsync,
source="/usr/cms",
target="user@host:/opt/webapps",
delete="false",

rsync = {
_extra = {"-ausS","--temp-dir=/tmp","-e","ssh -p 22"}
},
}

It's not work.
Lsyncd run, check target dir, copy files from my source dir to target and whats all.

I try change config and write sync section 

rsync = {
binary = "/usr/bin/rsync",
compress=true,
archive = true,
recursive=truse,
verbose=true,
times=true,
whole_file=true,
update=true,
rsh = "ssh",
temp_dir="/tmp",}

Not working.

**Comment by axkibe** [comment]
Sorry, I don't understand what the issue is.

Why do you think "tempdir" is not working?

**Comment by axkibe** [comment]
PS, the extra comma doesn't hurt in Lua.
