### ISSUE TITLE
Adding excludeFrom and exclude to Custom Configuration With checkgauge

### ISSUE THREAD

**Issue by shawing** [axkibe/lsyncd#278]
I am writing a custom configuration based on the sample from examples/lbash.lua.  I would like to be able to use exclude and excludeFrom within it, but get this error:

root@web:~# /usr/local/bin/lsyncd /etc/lsyncd.conf
Error: error preparing /etc/lsyncd.conf: /etc/lsyncd.conf:23: Parameter "excludeFrom" unknown. (if this is not a typo add it to checkgauge)
root@web:~#

If I grep I can see references to "rsync.checkgauge = {" and "rsyncssh.checkgauge = {" in default-rsync.lua and default-rsyncssh.lua, but I am uncertain how to do that for a custom configuration and be able to include the options for exclude and excludeFrom.

**Comment by madhavkhakhar08** [comment]
Is this issue fixed?

**Comment by axkibe** [comment]
There isn't an issue as far I realize.

If you make a custom configuration, you'll have to code the exclusion logic with it. It is done in default.rsync.

To enable additional options with your custom config, set the "checkgauge" variable of it.

See "default-rsync.lua" on how.

**Comment by smartmouse** [comment]
I used  excludeFrom in my lsyncd.config,
it does not exclude the file at all.


settings {
logfile = "/var/log/lsyncd/lsyncd.log",
statusFile = "/var/log/lsyncd/lsyncd-status.log",
statusInterval = 20,
insist=true
}

sync {
default.rsync,
rsync
source="/root/.liberty/wlp/usr/servers/controller/configDropins/overrides/",
target="root@xxx.xxx.com:/root/.liberty/wlp/usr/servers/controller/configDropins/overrides/",
excludeFrom="/root/.liberty/wlp/usr/servers/controller/configDropins/overrides/replicate-config.xml",

**Comment by axkibe** [comment]
smartmouse, with excludeFrom you're supposed to specify a file which contains the filter rules, not the filter rule itself, that would be the exclude option
