### ISSUE TITLE
Lsyncd 2.1.4+ : Perform an action based on the failure type of a default.rsync (or any other default provider)

### ISSUE THREAD

**Issue by kostecky** [axkibe/lsyncd#287]
Is it possible to perform actions on specific types of failures of default.rsync?  I would like catch the case where a target host goes down a.k.a a network failure after start. lsyncd will continue to retry on that host, which is fine, but I'd like to fire another default.rsync event with different settings/target.

**Comment by axkibe** [comment]
Yes, you can override the default collect() function that handles error codes.

You'll find the default provided one in default.lua ... copy it and adapt it to your needs.
