### ISSUE TITLE
default.direct and nfs mounts

### ISSUE THREAD

**Issue by rotor-head** [axkibe/lsyncd#288]
On start up of lsyncd the directories sync i.e. /localpath /nfspath, however, any changes to the /nfspath fail to get replicated to the /localpath.

I presumed NFS mounts are treated as local fs objects but it doesn't appear to work. Is NFS not supported?

**Comment by axkibe** [comment]
I now created a FAQ for this:

http://axkibe.github.io/lsyncd/faq/nothing-after-startup/
