### ISSUE TITLE
"delete = false" does not work

### ISSUE THREAD

**Issue by shirazd** [axkibe/lsyncd#296]
lsyncd 2.1.5 running on Ubuntu.
Target server is windows running cywgin.

I cannot get the "delete = false" option to work. If I delete a file at source, it deletes the file on the (windows) target.

This issue occurs both when using default.rsync and default.rsyncssh. I have the ssh method commented out here, in the config file:

sync {
default.rsync,
-- default.rsyncssh,
delete = false,
source = "/root/test",
target = "deerhouse_media:/cygdrive/c/media/test"
-- host="deerhouse_media",
-- targetdir="/cygdrive/c/media/test",
}

Am I missing something obvious? Perhaps something to do with the cygwin target (though I would think this was all handled at the source)? 

The log file doesn't show anything special. I can see it doing the delete op. No warnings or errors. It just doesn't seem to respect that flag.

Any help appreciated!

Shiraz

**Comment by 1049229070** [comment]
hello，Thank you very much for your selfless dedication. I am not effective here either.
This is my configuration file.version 2.15.
settings {
        logfile = "/var/log/lsyncd/lsyncd.log",
        statusFile = "/var/log/lsyncd/lsyncd.status"
}
sync {
        default.rsync,
        source = "/home/ftp/task",
        target = "root@192.168.0.36:/mnt/glusterfs",
        delete = false,
        -- exclude = { "*.bak", "*.tmp" }
}


Specific operation: I want to delete locally, the target will not be deleted. After touching the source, I execute rm, and then find that the target will also be deleted. I expect that the target will not delete the file I just created.
