### ISSUE TITLE
What about handling --backup option for rsync?

### ISSUE THREAD

**Issue by ardabro** [axkibe/lsyncd#299]
Hi
In my opinion --backup option is essential to keep safe backup system immune to some fatal mistakes.
But it is not trivial - there is need to create multiple time-stamped backup directories - one per each synchronization "transaction". 
Did You consider implementing such behavior?
regards

**Comment by Kelwing** [comment]
I second this, --backup, --backup-dir, and --suffix would all be very useful features.

**Comment by axkibe** [comment]
Fair enough, added to Lsyncd 2.1.7
