### ISSUE TITLE
mechanism to notify of 'dirty' state

### ISSUE THREAD

**Issue by desrt** [axkibe/lsyncd#300]
lsyncd could use a mechanism to notify an external program about if the directory is "dirty".

This dirty state would start immediately when the first inotify event is received and would only be cleared once the rsync has finished and the event queue is found to be empty again.

The most general mechanism here would be execution of an external hook script, but sending a D-Bus signal might also be nice.

At a minimum there should be three states that can be reported:
- doing first sync on startup
- dirty
- idle

Maybe it makes sense to report the difference between 'in delay period waiting for more events' and 'actually syncing', but that's not too important to me.

My motivation is that I'm using this on my Public/ folder on my laptop to push files to my server and I want to see an indication in the UI about when things are pending and when they've completed.

**Comment by axkibe** [comment]
Well, Lsyncd uses a scripting Language, so one can code this custom wishes there....

(And thats why Lsyncd 2.x switched to Lua instead of native C all the way, since a lot of people wanted speicifc things, now they can do that in Lua)
