### ISSUE TITLE
Lsyncd permission denied Error

### ISSUE THREAD

**Issue by gauravsaini03-zz** [axkibe/lsyncd#301]
Hello @axkibe ,

First of all, I am thankful to you for creating this awesome library for syncing. 

I am setting up lsyncd at for automatic sync local and remote folders. I have researched for many solution available, also adding extra params to the conf file. I have also, updated the sshd_config with PermitRootLogin without-password

Also, I am able to ssh with password and also rsync without password manually tried but the problem is when I use it via lsyncd it give permission denied error 3 times and exit (seems like its asking for password).

http://stackoverflow.com/questions/27342407/lsyncd-permission-denied-publickey-password

Thanks
Gaurav

**Comment by DavidStaron** [comment]
Hi there, i have an issue that looks somewhat like yours so i'll post my findings in case it is useful to someone:

When running this job as a Launch Daemon in OSX 10.11.1 i get this error:
```
Warn: Using /dev/fsevents which is considered an OSX internal interface.
Warn: Functionality might break across OSX versions (This is for 10.5.X)
Warn: A hanging Lsyncd might cause Spotlight/Timemachine doing extra work.
Call: initialize( )
Permission denied (publickey,keyboard-interactive).
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.1]
```

Then, i stop the job, and log in as 'root' in the terminal and execute:
```
/usr/local/bin/lsyncd -log Exec -nodaemon /etc/lsyncd/lsyncd2.lua
```
and now it works perfectly.

Note that the job runs as root as well:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Disabled</key>
  <false/>
  <key>KeepAlive</key>
  <true/>
  <key>Label</key>
  <string>lsyncd2.plist</string>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/local/bin/lsyncd</string>
    <string>-nodaemon</string>
    <string>/etc/lsyncd/lsyncd2.lua</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>StandardErrorPath</key>
  <string>/var/log/lsyncd/lsyncd2-error.log</string>
  <key>StandardOutPath</key>
  <string>/var/log/lsyncd/lsyncd2-info.log</string>
  <key>UserName</key>
  <string>root</string>
</dict>
</plist>
```

**Comment by PatrickGrenier** [comment]
Hello,

I have the same problem and I would like to know how to start lsyncd as a simple user, not as root. is it possible ? We use ubuntu a16.04 with no root ssh permission. We use a normal user to connect.

Patrick.
