### ISSUE TITLE
lsyncd and selinux

### ISSUE THREAD

**Issue by byurick** [axkibe/lsyncd#306]
I've been able to verify that lsync wont auto start when selinux is enforcing (by temporarily disabling it). Server is 64bit Centos 6.6

Anyone else see this issue and how to workaround (other than disabling selinux)?

**Comment by byurick** [comment]
I was able to disable only the rsync module and leave the rest of selinux enforcement running (semodule -d rsync)

Not really the best solution but better than disabling all of selinux.

**Comment by Fiddich** [comment]
No other options so far?

**Comment by byurick** [comment]
So far no, that's the best I've got.
