### ISSUE TITLE
Documentation is missing "insist"

### ISSUE THREAD

**Issue by modir** [axkibe/lsyncd#309]
Whenever I want to start lsyncd I get the following error message:

 Error, Temporary or permanent failure on startup of "/srv/httpd/". Terminating since "insist" is not set.

Nowhere in the documentation I can find something about this "insist".

**Comment by axkibe** [comment]
Fixed,

https://axkibe.github.io/lsyncd/manual/config/file/
https://axkibe.github.io/lsyncd/manual/invoking/

Thank you, sorry it took almost 2 years.
