### ISSUE TITLE
explicit support for --chmod option

### ISSUE THREAD

**Issue by ibukanov** [axkibe/lsyncd#310]
I need to disable permission synchronization so the target permissions will use permissions derived from umask. According to rsync manual, one has to use `--chmod=ugo=rwX` while ensuring that --perm option is not set. As --chmod is not directly supported in the rsync table, I have to use the uglier `_extra` workaround:

```
sync {
   default.rsync,
   source = "/tmp/test-src",
   target = "/tmp/test-dst",
   delay = 1,
   rsync = {
      _extra = { "--chmod=ugo=rwX" }
   }
}
```

**Comment by axkibe** [comment]
Done, will be in Lsyncd 2.1.7
