### ISSUE TITLE
Lsyncd did not continue after connection loss

### ISSUE THREAD

**Issue by mmike7** [axkibe/lsyncd#312]
In my scenario, I have to account for connection loss (as anyone running Lsyncd as a service I guess). Normally Lsyncd would just quit, but with "insist=1" it kept running and the status log showed the queued transactions.
However, nothing happened after enabling the connection again. The queue filled further up, but I had to restart the service before things were back to normal again. Is there a set timeout for this situation? I waited a few minutes.

**Comment by axkibe** [comment]
I suppose that rsync or ssh where still running and Lsyncd waited for it.
