### ISSUE TITLE
Lsyncd non-root rsyncssh configurations

### ISSUE THREAD

**Issue by alternativshik** [axkibe/lsyncd#313]
my config:

settings {
  logfile    = "/var/log/lsyncd/lsyncd.log",
  statusFile = "/var/log/lsyncd/lsyncd.status",
  nodaemon   = true
}

sync {
  default.rsyncssh,
  source="/home/USER/test",
  host="USER@slave",
  targetdir="/home/USER/test",
  delay=3,
  rsync={
        rsh="ssh -l USER -i /home/USER/.ssh/id_rsa.pub -o StrictHostKeyChecking=no",
 },
}

If I start with sudo /etc/init.d/lsyncd start - IT allways ask me a passphrase for key, then password for USER@slave.
ssh USER@slave works fine - without password.
If i start lsyncd with non root user - all works fine, any passwords and problems. How can I disable any prompts when launch it from ROOT?

I dont want login via ssh to slave server from root account.

**Comment by envygeeks** [comment]
Copy your ssh keys to /root/.ssh

**Comment by axkibe** [comment]
As envygeeks said.

**Comment by wangawei** [comment]
I use this config code:

sync {
   default.rsyncssh,
   source="/data/test01",
   host="ww@192.168.1.60",
   targetdir="/data/test01",
   rsync = {
     archive = true,
     compress = false,
     whole_file = false
   },
   ssh = {
     identityFile = "/root/.ssh/id_rsa",
     port = 22,
   }
}

yes, YourUserName@the_remote_host
