### ISSUE TITLE
File that was deleted on target was not synced up by lsyncd

### ISSUE THREAD

**Issue by laurentiuspurba** [axkibe/lsyncd#314]
Hello all,

I have a weird situation that I encountered with lsyncd. I don't know if I missed something in lsyncd.conf or if this is lsyncd behavior.

I am using lsyncd 2.0.4 (I know, I know ... I can't upgrade it at this moment)

Below is my lsyncd.conf:
<pre>
settings = {
    logfile = "/var/log/lsyncd.log",
    statusFile = "/var/log/lsyncd-status.log"
}

sync {
    default.rsyncssh,
    delete = false,
    source = "/home/jdoe/test-rsync",
    host = "source.jdoe.com",
    targetdir = "/home/jdoe/test-rsync",
    rsyncOps = "-avh",
    delay = 5,
    maxProcesses = 4,
    ssh = {
        port = 22
    }
}
</pre>

The directory content of <b>SOURCE</b> is as follows:
<pre>
-rw-rw-r-- 1 jdoe jdoe  0 Mar 10 09:54 test1.txt
-rw-rw-r-- 1 jdoe jdoe  0 Mar 10 09:54 test2.txt
-rw-rw-r-- 1 jdoe jdoe  0 Mar 10 09:54 test3.txt
-rw-rw-r-- 1 jdoe jdoe  0 Mar 10 09:54 test4.txt
-rw-rw-r-- 1 jdoe jdoe  0 Mar 10 09:54 test5.txt
</pre>

While directory content of <b>TARGET</b> as of now is empty.

When I issued command from command line with the following command,
<pre>root@source:~/test-rsync# lsyncd /etc/lsyncd.conf</pre>

The directory content of <b>TARGET</b> is as follows:
<pre>
-rw-rw-r-- 1 jdoe jdoe  0 Mar 10 09:54 test1.txt
-rw-rw-r-- 1 jdoe jdoe  0 Mar 10 09:54 test2.txt
-rw-rw-r-- 1 jdoe jdoe  0 Mar 10 09:54 test3.txt
-rw-rw-r-- 1 jdoe jdoe  0 Mar 10 09:54 test4.txt
-rw-rw-r-- 1 jdoe jdoe  0 Mar 10 09:54 test5.txt
</pre>

I can see the lsyncd /etc/lsyncd.conf is still running by issuing command ps aux | grep lsyncd from command line.

This is when thing got interesting:
I deleted 3 files (test3.txt,  test4.txt,  test5.txt) from <b>TARGET</b>, and lsyncd does not sync up from <b>SOURCE</b> to <b>TARGET</b> regarding deleted files on <b>TARGET</b>.
So, I created a new file on <b>SOURCE</b>, helpme.txt, and lsyncd is smart enough to detect this file, and sync up to <b>TARGET</b>. But the deleted files on <b>TARGET</b> (test3.txt,  test4.txt,  test5.txt) were not synced up from <b>SOURCE</b> to <b>TARGET</b>.

I don't know if there is other options that I need to pass, or I should use event, or any other things.

If anybody had experienced this before, I would be more than happy if you could share it with me.

Regards,
-Laurentius

**Comment by lilmike** [comment]
Hi,
I may be totally wrong, but my understanding was that lsyncd only monitored the local file system. That would mean, in order for the target to sync any changes to the source, you'd need a separate instance of lsyncd running on the target syncing to source.
Hth,
-Michael.

**Comment by laurentiuspurba** [comment]
Hi Michael,

Thanks for your response. I thought the same thing.

**Comment by alibarj** [comment]
I'm facing the same issue, but when I restart lsyncd, the TARGET deleted files DO get restored. Still no solution without restarting lsyncd though.
