### ISSUE TITLE
Second sync only runs on launch of lsyncd

### ISSUE THREAD

**Issue by multplx** [axkibe/lsyncd#316]
Hi I have the /etc/lsyncd/lsyncd.conf.lua file below.

On launch, both syncs work perfectly.

But if I leave lsycnd running, only Sync #1 stays consistent on target1.

Sync #2 does not seem to trigger.
/var/log/lsyncd/lsyncd.log contains

Normal: Startup of "/src/2/" finished: 0
Thereafter, changes to /src/1 are record in the log, but no changes to /src/2 appear.

Could you help please? 

``` bash
settings {
 logfile = "/var/log/lsyncd/lsyncd.log",
 statusFile = "/var/log/lsyncd/lsyncd.status"
}
-- Sync #1:
sync {
 default.rsyncssh,
 source = "/src/1",
 host = "user1@target1",
 targetdir = "/dst/1",
 rsync = {
  archive = true,
  compress = false,
  whole_file = false
 },
 ssh = {
  port = 2999
 }
}
-- Sync #2.
sync {
 default.rsyncssh,
 source = "/src/2",
 host = "user2@target2",
 targetdir = "/dst/2",
 rsync = {
  archive = true,
  compress = false,
  whole_file = false
 },
-- delete = false,
 ssh = {
  port = 2999
 }
}
```

**Comment by axkibe** [comment]
Is /src/2 on a nfs, samba or sshfs filesystem perhaps?

**Comment by multplx** [comment]
Thanks for the prompt response.

Not nfs, samba or sshfs. It is webdav with some snaky symlinks along the way. But initial sync is OK...

**Comment by axkibe** [comment]
If its a remote file system - webdav is also one - the kernel will not send
any file event notifications. This is a shortcoming of all remote file
systems I know of. Lsyncd needs to run on whatever machine this filesystem
is local to.

**Comment by multplx** [comment]
Thanks. Apologies for the lazy question - I have not used lsyncd for pull before. Is this straightforward?

**Comment by axkibe** [comment]
There is no pull. Lsyncd needs to run where the filesystem is localized.

**Comment by multplx** [comment]
Thanks that's very clear. I will try pointing target differently.
