### ISSUE TITLE
inotifywait exclude is not supported?

### ISSUE THREAD

**Issue by seanlook** [axkibe/lsyncd#317]
I have checked lsyncd source code and find out inotifywait do not suport exclude options. rsync exclude is a nice feature for me. In order to eliminate cpu load, I want  some subdirectories do not be watched. I am not sure inotify use the same exclude pattern as rsync, or just watch the whole source directory?

**Comment by axkibe** [comment]
As designed it shouldn't watch excluded directories, Lsyncd parses the exclude file for that.

If you see/debug it doing it nevertheless, it is a bug. Open another issue if so.
