### ISSUE TITLE
Incorrect man page install on OS X 10.3.3

### ISSUE THREAD

**Issue by elmart** [axkibe/lsyncd#319]
I'm on OS X 10.3.3.
I managed to build ok, but manpage was not being found because installed on `/usr/local/man/`. To be picked by default on my OS, it should have been in `/usr/local/share/man/man1`.

**Comment by axkibe** [comment]
You're using the release that has autotools yes? I fully changed the build system in git to cmake instead. Can you try that one please?

**Comment by axkibe** [comment]
No longer applies to git HEAD.
