### ISSUE TITLE
lsyncd stops after initial sync

### ISSUE THREAD

**Issue by predmijat** [axkibe/lsyncd#324]
test.conf.lua:
```
settings{
	statusFile = "/home/ubuntu/lsyncd/log/test.status",
	logfile = "/home/ubuntu/lsyncd/log/test.log",
	statusInterval = 1,
}

sync{
	default.rsync,
	source="/home/ubuntu/src",
	target="/home/ubuntu/dst",
}
```

I've tried a bunch of different configs, but ended up with this simple one and it's still happening - lsyncd only syncs the initial state of src directory and then stops. Doing a `kill -HUP` on lsyncd PID will send new stuff to dst.

I started with both dirs empty. Created a file in src, didn't get synced. Did a `kill -HUP`, it appears in dst.
`echo $(date -I) >> /home/ubuntu/src/1` - doesn't get synced. `kill -HUP` - it syncs...

```
/home/ubuntu/lsyncd/log# cat test.log 
Wed Jul  8 10:35:44 2015 Normal: recursive startup rsync: /home/ubuntu/src/ -> /home/ubuntu/dst/
Wed Jul  8 10:35:44 2015 Normal: Startup of "/home/ubuntu/src/" finished.
Wed Jul  8 10:36:09 2015 Normal: Calling rsync with filter-list of new/modified files/dirs
/1
/
Wed Jul  8 10:36:09 2015 Normal: --- HUP signal, resetting ---
Wed Jul  8 10:36:09 2015 Normal: waiting for 1 more child processes.
Wed Jul  8 10:36:09 2015 Normal: Finished a list after exitcode: 0
Wed Jul  8 10:36:09 2015 Normal: recursive startup rsync: /home/ubuntu/src/ -> /home/ubuntu/dst/
Wed Jul  8 10:36:09 2015 Normal: Startup of "/home/ubuntu/src/" finished.
Wed Jul  8 10:36:24 2015 Normal: --- HUP signal, resetting ---
Wed Jul  8 10:36:24 2015 Normal: recursive startup rsync: /home/ubuntu/src/ -> /home/ubuntu/dst/
Wed Jul  8 10:36:24 2015 Normal: Startup of "/home/ubuntu/src/" finished.
```

```
/home/ubuntu/lsyncd/log# cat test.status 
Lsyncd status report at Wed Jul  8 10:36:25 2015

Sync1 source=/home/ubuntu/src/
There are 0 delays
Excluding:
  nothing.


Inotify watching 1 directories
  1: /home/ubuntu/src/
```

Again, nothing gets synced until I do a `kill -HUP` on lsyncd PID.

**Comment by axkibe** [comment]
I suppose "/home/ubuntu/src/" is a network mounted resource?

In that case Lsyncd doesn't work. It needs to run where the files are physically located. Or you get the NFS and Linux kernel team to support file events over NFS. Or the Samba team for SMB or the SSHFS team for sshfs, etc.

I don't know of any network file system that supports inotify event through network mounts...

**Comment by predmijat** [comment]
It's not network mounted...but it turns out it does work actually...
I was using `tail -f` on the dst side to check for updates and it didn't show anything there...but if I later do `cat` the updates are there...sorry for the alarm :)

**Comment by axkibe** [comment]
Maybe its just the delay you are experiencing. By default Lsyncd waits 15 seconds before it does action.

**Comment by predmijat** [comment]
I have to reopen this...
After the simple config pasted in the OP (local directories only), I've tried to use something more complex - ssh with options:

```
/home/ubuntu/lsyncd# cat ba560311bb85.conf.lua
settings{
    statusInterval = 1,
    logfile = "/home/ubuntu/lsyncd/log/ba560311bb85.log",
    statusFile = "/home/ubuntu/lsyncd/log/ba560311bb85.status"
}

sync{
    default.rsync,
    source = "/var/lib/docker/aufs/mnt/ba560311bb854607fe00d8215cf1a37d9a930228d4a96b9f8fb708fe09666aa8/var/log/containerlogs/",
    target = "logginguser@remoteserver:ba560311bb85/",
    rsync = {
        archive = true,
        verbose = true,
        _extra = {"-e", "/usr/bin/ssh -o StrictHostKeyChecking=no", "-avz"}
    }
}
```

This syncs the initial state and will not sync any more - I've tried `cat` instead of `tail -f` too :)
If, however, I do a `echo $(date -I) >> /var/lib/docker/aufs/mnt/ba560311bb854607fe00d8215cf1a37d9a930228d4a96b9f8fb708fe09666aa8/var/log/containerlogs/log1.log` it will trigger the sync and it will send the date and also everything in between the inital state and me echoing the date. No other files in that dir will be synced, even though they've also changed in the meantime - I have to do an explicit change (echo) to each one I want synced again...

I'm starting lsyncd with `sudo lsyncd /home/ubuntu/lsyncd/ba560311bb85.conf.lua`.

What am I missing?

**Comment by axkibe** [comment]
It looks like you want to sync log files, and whatever writes them doesn't close the file handle.

Lsyncd is by default configured to respond when a file handle is closed after the file has been modified, but you want it to respond while its still being modified.

See inotifyMode in the docs

https://github.com/axkibe/lsyncd/wiki/Lsyncd%202.1.x%20%E2%80%96%20The%20Configuration%20File

You can set it to "CloseWrite or Modify" to change it to be that way.

**Comment by predmijat** [comment]
It worked! Thank you, axkibe!
