### ISSUE TITLE
rsync exclude documentation incorrect

### ISSUE THREAD

**Issue by jacobweber** [axkibe/lsyncd#326]
According to [this page](https://github.com/axkibe/lsyncd/wiki/Lsyncd%202.1.x%20%E2%80%96%20Layer%204%20Config%20%E2%80%96%20Default%20Behavior), the rsync parameter should include the "exclude" option.

But when I do that, I get an error 'Parameter "rsync.exclude" unknown':

    sync {
        default.rsync,
        rsync = {
            exclude = {"X", "Y"}
        }
    }

However, if I move "exclude" up a level, it seems to work:

    sync {
        default.rsync,
        exclude = {"X", "Y"},
            rsync = {
            }
    }

**Comment by RoyBellingan** [comment]
I can confirm the bug in the first case, and that in my case a file is still replicated using the second case.

**Comment by mickaelperrin** [comment]
I can confirm the issue, thanks for sharing.

**Comment by axkibe** [comment]
But it isn't that way in the docs.

**Comment by pauvos** [comment]
Just curious, why were the docs not updated accordingly?
Should I create a pull request?

**Comment by axkibe** [comment]
Yes please, since I checked and as far I've seen the docs are correct.

Maybe I overlooked something?

**Comment by markkrj** [comment]
I guess I found it... There is a table with options for the rsync parameter, and the "exclude" is there. It is wrong because exclude is an option for the sync parameter and not rsync.

> Below is a table of options for the rsync parameter. Please have a look at the Rsync documentation for an in depth explanation.

|    |            |   |
|----------|:-------------|------|
| exclude | = | PATTERN	TABLE of PATTERNs also allowed |
| excludeFrom | = | FILENAME |

**Comment by itemir** [comment]
+1

**Comment by Crispy13** [comment]
But in the the docs, exclude parameter is in both rsync paramter table and sync paramter table(see "Exclusions" section.)

I got the same error, unknown parameter "rsync.exclude". But exclude is an option for rsync(i saw it in rsync manual) also. I have no idea why this error message was shown

**Comment by corbolais** [comment]
This is a semantic bug in `lsyncd`. `exclude` is an **rsync** parameter, so, as https://github.com/axkibe/lsyncd/issues/326#issuecomment-301141962 states, the online doc is correct. But the lsyncd implementation still seems at fault as of 2020-04. Or the other way round when taking https://github.com/axkibe/lsyncd/issues/326#issuecomment-603624766 into account.

Either way, this is clearly a bug in lsyncd and it is still not fixed, FIVE years on. *facepalm*

Using Debian pkg lsyncd, version 2.2.3-1
