### ISSUE TITLE
Different computed options for initial vs update?

### ISSUE THREAD

**Issue by willmuldrew** [axkibe/lsyncd#327]
Hi

I'm trying to use lsyncd on a 1TB/4M file source.  If there are files that are changing internally (with no length change), then there's a bit of a race condition on the initial sync.  If the initial blanket rsync hits a file while it's changing, and it changes again in the same second, then the subsequent inotify triggered rsync is a noop (since it only looks at size and second resolution mtime by default) .  My way around this is to use the checksum option, but this means that if lsyncd needs to be restarted or hits a 'die' error, then the initial sync takes a very long time since there's a lot of data on both sides that needs to be read and md5'd!  I _think_ that it's safe to not use checksum in the blanket init sync, if you use it later in the normal updates.  Is it possible to have different options for each?  (I'm currently playing with a customised init function).

As an aside - it's really annoying that nano timestamps can't be preserved with rsync AFAIK.

**Comment by axkibe** [comment]
Is it really? When Lsyncd fires rsync, rsync starts to transmit the file in a condition whatever, however when the file is changed afterward, Lsyncd receives the inotify event for this and thus runs rsync another time after the first one is finished. At least this is the design.

If this is not the case, then its a bug in the implementation.

**Comment by axkibe** [comment]
Ah i get it now, it is a rsync issue. You can always copy "default-rsync.lua" to make your own custom script of it. There you can alter different behaviors.

**Comment by willmuldrew** [comment]
Hi Axel.  Yes - I've done this thanks, but I wondered if it might be
something that was useful to be able to configure without a long custom
init method,

**Comment by axkibe** [comment]
Ya, but it would complicate the runner/core quite a bit for a rather rarely asked issue.

Overriding the default init function sound perfect enough to me. Thats why Lsyncd now runs a scripting engine anyway.. so rarely requested features can easily be scripted by those people (well at least as easy as sanely possible)
