### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by nilroy** [axkibe/lsyncd#329]
My compile is failing with below error

./configure: line 3793: syntax error near unexpected token `LUA52,'
./configure: line 3793: `PKG_CHECK_MODULES(LUA52, lua5.2,,'

I have gcc and lua5.2 installed in my ubuntu 14.04. What extra packages I need to install?

**Comment by xxorax** [comment]
On Debian Jessie, I install it successfully by running :
```
apt-get install -y \
  autoconf \
  curl \
  libglib2.0-dev \
  liblua5.2-dev \
  lua5.2 \
  make

LUA_CFLAGS="-I/usr/local/lua-5.2.2-1/include" && \
LUA_LIBS="-L/usr/local/lua-5.2.2-1/lib -llua -ldl -lm" && \
./autogen.sh && \
./configure && \
make

```

Hope this help

**Comment by axkibe** [comment]
Since Lsyncd now uses cmake instead of configure this issue should no longer apply.
