### ISSUE TITLE
LSYNCD with iconv

### ISSUE THREAD

**Issue by gklipel** [axkibe/lsyncd#332]
Hi!

Tried to work with rsync _extra parameter but can't get it working. I need iconv parameter with rsync with format iconv=iso88591,utf8 but always get "bad argument #1 to 'ipairs' (table expected, got string)" from LUA. 

There is a way to get rid of this?

+++++++++++++++++++++++++++++++++++
EDIT:

Sorry, wasn't using {}... so the right way was _extra = {"--iconv=utf8,iso88591"},

Thanks anyway!

**Comment by axkibe** [comment]
Ok.
