### ISSUE TITLE
Symlink content doesn't sync right away

### ISSUE THREAD

**Issue by daedeloth** [axkibe/lsyncd#333]
Hi,

I have set up a system that only syncs data of some of our customers.
So I've set up a folder that is syncronised, and with a script that runs once every hour I add / remove symlinks to that folder.

If I launch lsyncd, the synchronisation runs perfectly. (copy_links is set to true). It copies the content of all symlinks correctly and everything is fine.

If I, however, add a symlink while lsyncd is running, only the name of the symlink is synced to my remote location. The content of the file is skipped.

I'm not sure if this is an rsync or an lsyncd issue, or perhaps just a misconfiugration on my side.

Many thanks for the help!

**Comment by daedeloth** [comment]
The same also happens when removing a symlink:
cannot delete non-empty directory: 000022

**Comment by axkibe** [comment]
I suppose whatever you're linking to is not within the watched source dir. In that case, no Lsyncd won't follow symlinks to add the linked directories into it's watch tree. That would complicate things quite a bit...
