### ISSUE TITLE
How to delete source file only after all targets are synced?

### ISSUE THREAD

**Issue by djester** [axkibe/lsyncd#335]
Hi,

I need to delete files on source only after both target are synced. But there is delete option only within sync block. So, i cannot use loop (or many sync block) for multiple target configuration. I read issues, but not found answer. 

Could you advise me to solve this problem?
Thanks.

**Comment by axkibe** [comment]
I'm sorry, this just doesn't fit into Lsyncd's structure at all, since the different targets act independently of each other.
