### ISSUE TITLE
default-rsyncssh -- can't move files

### ISSUE THREAD

**Issue by jcloth** [axkibe/lsyncd#336]
---
## Version:
# lsyncd --version

Version: 2.1.5

---
## Config:

sync {
   default.rsyncssh,
   source="/tmp/test/",
   host="remotehost",
   targetdir="/tmp/test/",
   rsync = {
     archive = true,
     compress = false,
     whole_file = false
   },
   ssh = {
     port = 22
   }
}

---
## Error:
# mv a b

Tue Sep 15 23:52:25 2015 Normal: Moving /a -> /b
Tue Sep 15 23:52:25 2015 Error: in Lua: default-rsyncssh.lua:92: attempt to call local 'path2' (a string value)
Tue Sep 15 23:52:25 2015 Error: Backtrace 1 :default-rsyncssh.lua:92
Tue Sep 15 23:52:25 2015 Error: Backtrace 2 :lsyncd.lua:1960
Tue Sep 15 23:52:25 2015 Error: Backtrace 3 :lsyncd.lua:3511

**Comment by sfarrell5123** [comment]
I had the same issue, same error, line 92 , same lsync version

did you find a solution ?

I think I'll just move to rsync instead of rsyncssh

**Comment by jcloth** [comment]
I went backwards to 2.0.x and have it working but I'd prefer to upgrade again to 2.1.x.

Sadly though, it looks like the lsyncd project has been abandoned.

**Comment by sfarrell5123** [comment]
mmm .. not good

did you try any intermediate versions ? or did you jump straight to 2.0 ?

I just moved over to pure rsync for now

**Comment by jcloth** [comment]
I changed the target release to debian wheezy and it installed its default which ended up being 2.0.x

I had just upgraded to "Jessie" before I tried rsyncssh then found it not working. Never tried rsyncssh in 2.1.x on wheezy.

**Comment by roben** [comment]
I have the exact same issue here with the lsync 2.1.5-2 from Debian Jessy. Is there any way to work around this without downgrading lsync?

**Comment by roben** [comment]
Seeing that the master branch has last been updated 11 months ago, I fear that we will be left alone here :(

**Comment by axkibe** [comment]
I'm still here, sorry I just don't invest much time into this anymore.

What makes me wonder is that line 92 in default-rsyncssh.lua from 2.1.5 hasn't even a code line. Maybe Debian patched something?

PS: I still didn't yet recover from the closing of google projects to figure out how to make proper releases on github, meaning having to check in autogenerated files which I so far avoided.

**Comment by axkibe** [comment]
PS: Anyhow I advice using plain "default.rsync" over "default.rsyncssh", the second has some issues with symlinks being replaced by real files withing a short time period for which I don't really know how to properly avoid all race conditions.

**Comment by roben** [comment]
Thanks for the info, good to hear from you! I issued a bug report to debian directly, maybe they really changed something. I also will checkout "default.rsync" when I have the time.

**Comment by axkibe** [comment]
yes they made a fix. also due to my fault since my failure to make a release version in time.

let me figure out what changed

**Comment by axkibe** [comment]
In line 91 of default-rsyncssh.lua it misses a ',' at the end of the line.

Dunno how to make a proper new debian package, but try
```
apt-get source lsyncd
cd lsyncd-2.1.5
```
edit line 91 of default-rsyncssh.lua with your favorite editor.
```
sudo apt-get remove lsyncd
./configure
make
sudo make install
```

Which should put the custom fixed lsyncd in /usr/local/bin

Anyhow, unless you really need the local move on target feature, I suggest using plain default.rsync option instead of the one taking use of ssh.

**Comment by roben** [comment]
Thanks, will try that.
The debian issue has been created and is available here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=801761
I guess they will fix this in time, too.

**Comment by axkibe** [comment]
Lets do the following, I'll make lsyncd 2.1.6 release on github and you test if it works you, yes?

I changed the build system a while ago, so I'd like a test on some other machine than mine.

**Comment by roben** [comment]
I would really like to, but lsyncd runs on several production servers where I have to stick to official releases - Sorry. The thing is that the sync targets all have to run with --delete, which really is sensitive if something goes wrong...

**Comment by tahder** [comment]
I don't know if this is related to this issue, as per testing at first run of lsync works perfectly but when you modify the configuration (/etc/lsyncd.conf) and on succeeding restart of lsync it doesn't work. But manually running it works perfectly which trigger me that there is something fishy going on. At first I thought the configurations particularly on spaces between equal sign say  rsync = {rsh = "/usr/bin/ssh -l root -i /root/.ssh/id_rsa",} but I was wrong in the end.

As per notice and testing further, when you stop the  lsync daemon  there are  still running in background; and rsyncd also running (but need to confirm too if related to rsyncd). Manual solution is to kill those processes and start again the lsyncd which work fine but tedious as you keep on deleting/killing the said processes.

As final solution on me, I used to modify the systemd service for lsyncd. The steps I made:
1. modify in full the lsyncd service 
sudo systemctl edit --full lsyncd.service

2. locate the file above, as it usually reside in /etc/systemd/system/lsyncd.service
vi /etc/systemd/system/lsyncd.service

3. add the following lines under [Service]
ExecReload=/bin/kill -HUP $MAINPID
ExecStop=/bin/kill -WINCH ${MAINPID}


4. Save and reload the services
sudo systemctl daemon-reload

Note: if you wanted not to save it or revert your settings, remove the said file in #2 and rerun #4.

The final code looks like these:
[Unit]
Description=Live Syncing (Mirror) Daemon
After=network.target

[Service]
Type=simple
Nice=19
EnvironmentFile=-/etc/sysconfig/lsyncd
ExecStart=/usr/bin/sh -c 'eval `/usr/bin/lsyncd -nodaemon $LSYNCD_OPTIONS /etc/lsyncd.conf`'
ExecReload=/bin/kill -HUP $MAINPID
ExecStop=/bin/kill -WINCH ${MAINPID}


[Install]
WantedBy=multi-user.target

**Comment by Ginkosama** [comment]
Sadly as of today, the Debian package in stable is still having this issue...

Getting the source, adding the missing comma, and compiling as axkibe [described it here](https://github.com/axkibe/lsyncd/issues/336#issuecomment-148012986) works fine.

P.S: you'll need lua5.2 and liblua5.2-dev to compile it.

**Comment by axkibe** [comment]
Ya, seems Debian downstream manager is busy with other stuff or I've fallen from grace.

I suppose it needs someone to stand up for it for Debian.

Anyway, for me as upstream it is to be considered as fixed.

**Comment by roben** [comment]
FYI: I have contacted the maintainer. He has updated the unstable package to the latest version. (https://packages.debian.org/de/unstable/lsyncd)

**Comment by axkibe** [comment]
Thanks!

**Comment by axkibe** [comment]
I suggest asking Debian/Ubuntu.
