### ISSUE TITLE
network mounted directory

### ISSUE THREAD

**Issue by bymaximus** [axkibe/lsyncd#339]
I have a linux virtual server which mounts a windows shared folder. This mounted directory works perfectly, all changed/created/removed files (by linux side) are being synced but when file change/create/remove comes from shared network folder seems lsyncd doesnt see any event.

Any tip about it? Is lsyncd unable to watch file events when it comes from shared network?

**Comment by axkibe** [comment]
Yes, the SMB network filesystem just doesn't give any file notifications.
BTW same with NFS.
