### ISSUE TITLE
Issues compiling under Mac OS X 10.5

### ISSUE THREAD

**Issue by domb84** [axkibe/lsyncd#341]
I'm trying to compile the 2.1.5 release under OS X 10.5.8. I'm getting the following problem when configuring:

Mac-Pro-1:lsyncd-release-2.1.5 era$ ./configure --without-inotify --with-fsevents CFLAGS="-I /Users/era/Desktop/xnu-10.5"
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables...
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for a BSD-compatible install... /usr/bin/install -c
checking whether make sets $(MAKE)... (cached) yes
./configure: line 3446: syntax error near unexpected token `LUA52,'
./configure: line 3446:`PKG_CHECK_MODULES(LUA52, lua5.2,,'

lua 5.2 is installed however (from brew)

Mac-Pro-1:lsyncd-release-2.1.5 era$ brew info lua
lua: stable 5.2.4

Looks like there is an issue with the detection as it's 5.2.4 release?

If any body can help that would be much appreciated. Or if there is a prebuilt binary for 10.5 even better.

**Comment by axkibe** [comment]
Please try using HEAD from git, I changed the build system to cmake.

**Comment by domb84** [comment]
Hi thanks for the response, but I can't build the current source on 10.5 either. See below:

Mac-Pro-1:lsyncd-master era$ cmake -DWITH_INOTIFY=OFF -DWITH_FSEVENTS=ON -DXNU_DIR=/Users/era/Desktop/xnu-10.5/

Mac-Pro-1:lsyncd-master era$ make
[ 10%] Building C object CMakeFiles/lsyncd.dir/lsyncd.c.o
/Users/era/Desktop/lsyncd/lsyncd-master/lsyncd.c:182:3: warning: #warning having to use old style realpath()
/Users/era/Desktop/lsyncd/lsyncd-master/lsyncd.c: In function 'write_pidfile':
/Users/era/Desktop/lsyncd/lsyncd-master/lsyncd.c:667: error: 'O_CLOEXEC' undeclared (first use in this function)
/Users/era/Desktop/lsyncd/lsyncd-master/lsyncd.c:667: error: (Each undeclared identifier is reported only once
/Users/era/Desktop/lsyncd/lsyncd-master/lsyncd.c:667: error: for each function it appears in.)
make[2]: *** [CMakeFiles/lsyncd.dir/lsyncd.c.o] Error 1
make[1]: *** [CMakeFiles/lsyncd.dir/all] Error 2
make: *** [all] Error 2

I did some research into this yesterday and it looks like O_CLOEXEC is not a function that existed until 10.6?

**Comment by axkibe** [comment]
```
@@ -664,7 +664,9 @@ write_pidfile(
        const char *pidfile
 )
 {
-       pidfile_fd = open( pidfile, O_CREAT | O_RDWR | O_CLOEXEC, 0644 );
+       pidfile_fd = open( pidfile, O_CREAT | O_RDWR, 0644 );
+
+       fcntl( pidfile_fd, F_SETFD, FD_CLOEXEC );
 
        char buf[ 127 ];
```

You can try this patch. I honestly don't know about the state of OSX compatibility, there was some effort to change the notification system from the reverse engineered /dev/fsevent to the official OSX FsEvents interface, but wasn't finished. Anyway that one would require >10.6

**Comment by domb84** [comment]
I'm patching lsyncd.c I assume? Many thanks

**Comment by domb84** [comment]
Ok thats built. I'll give it a try. Thanks for your help!
