### ISSUE TITLE
Is lsyncd useful for bidirectional synchronization ?

### ISSUE THREAD

**Issue by gnumoksha** [axkibe/lsyncd#342]
When both hosts constantly changes, is lsyncd useful for bidirectional synchronization ?

Sorry for asking here.

**Comment by Episodio1** [comment]
Hi!

I am also interested in bidirectional sync (with "delete = false").

**Comment by mdiehn** [comment]
I considered this just the other day, actually.

Lsyncd uses the kernel inotify features to know what to send to a remote.
Once I remembered that, it didn't make much sense to me to think about
using it to sync from the remote.

I expect the tool is flexible enough that one could use it to sync to and
from, but I haven't thought it through. If you do, I'd like to hear.

Sincerely,
Mike
--
Mike Diehn
Enfield, NH

**Comment by axkibe** [comment]
Lsyncd does not 'officially' support a master-master setup, as there are many possible race conditions, that are not designed out. 

Some people do it nevertheless, but usally they're supposed to be the ones that know exactly what they're doing, and figure out startup solution etc. themselves matching their setup. Anyway, mostly your on your own if you go that path.

To avoid at least some endless circles, be sure to set
update	= true,
temp_dir	= DIR (someplace not synced)
