### ISSUE TITLE
Mac OS X 10.5 - Overflow in event queue

### ISSUE THREAD

**Issue by domb84** [axkibe/lsyncd#343]
Is there a way to increase the number of events that can be queued in OS X 10.5? I know under Linux we can just increase the following:

fs.inotify.max_user_watches=65536
fs.inotify.max_queued_events=65536

The same doesn't apply to OS X though and I keep having to kill the rsync processes and start lsyncd again after it crashes out with the following:

Sep 28 22:00:35 xxx lsyncd[56474]: Normal, --- OVERFLOW in event queue ---
Sep 28 22:00:35 xxx lsyncd[56474]: Normal, --- HUP signal, resetting ---
Sep 28 22:00:35 xxx lsyncd[56474]: Normal, waiting for 3 more child processes.
Sep 28 22:00:37 xxx lsyncd[56474]: Normal, --- OVERFLOW in event queue ---
Sep 28 22:00:37 xxx lsyncd[56474]: Normal, --- HUP signal, resetting ---
Sep 28 22:00:40 xxx lsyncd[56474]: Normal, --- OVERFLOW in event queue ---
Sep 28 22:00:40 xxx lsyncd[56474]: Normal, --- HUP signal, resetting ---
Sep 28 22:00:42 xxx lsyncd[56474]: Normal, --- OVERFLOW in event queue ---
Sep 28 22:00:42 xxx lsyncd[56474]: Normal, --- HUP signal, resetting ---
Sep 28 22:00:42 xxx lsyncd[56474]: Normal, --- OVERFLOW in event queue ---
Sep 28 22:00:42 xxx lsyncd[56474]: Normal, --- HUP signal, resetting ---
Sep 28 22:00:46 xxx lsyncd[56474]: Normal, --- OVERFLOW in event queue ---
Sep 28 22:00:46 xxx lsyncd[56474]: Normal, --- HUP signal, resetting ---
Sep 28 22:00:48 xxx lsyncd[56474]: Normal, --- OVERFLOW in event queue ---
Sep 28 22:00:48 xxx lsyncd[56474]: Normal, --- HUP signal, resetting ---
Sep 28 22:00:50 xxx lsyncd[56474]: Normal, --- OVERFLOW in event queue ---
Sep 28 22:00:50 xxx lsyncd[56474]: Normal, --- HUP signal, resetting ---
Sep 28 22:00:53 xxx lsyncd[56474]: Normal, --- OVERFLOW in event queue ---
Sep 28 22:00:53 xxx lsyncd[56474]: Normal, --- HUP signal, resetting ---
Sep 28 22:00:55 xxx lsyncd[56474]: Normal, --- OVERFLOW in event queue ---
Sep 28 22:00:55 xxx lsyncd[56474]: Normal, --- HUP signal, resetting ---
Sep 28 22:00:56 xxx ReportCrash[59068]: Formulating crash report for process lsyncd[56474]
Sep 28 22:00:56 xxx ReportCrash[59068]: Saved crashreport to /Library/Logs/CrashReporter/lsyncd_2015-09-28-220056_xxx.crash using uid: 0 gid: 0, euid: 0 egid: 0

**Comment by domb84** [comment]
Hi all, I'm guessing there is no way to increase the buffer in that case and another tool should be used? It's crashing out constantly as the filesystem is constantly being written to.

**Comment by axkibe** [comment]
This is something Apple ought to fix.

Once Lsyncd uses FsEvents instead of /dev/fsevents it might occur less often, if the FsEvents daemon empties the kernel queue faster than Lsyncd does directly.
