### ISSUE TITLE
protect_args crashes on Mac OSX 10.11

### ISSUE THREAD

**Issue by thecodeassassin** [axkibe/lsyncd#344]
Hey guys,

The protect_args argument (-s) will crash when used with rsync 2.6.9 on OSX. This option was true by default so i had to look through the code to find out that it was protect_args that was making the whole thing crash. 

``` bash
$ rsync --version
rsync  version 2.6.9  protocol version 29
```

``` bash
Thu Oct  8 13:33:23 2015 Normal: recursive startup rsync: /srv/shared/sho/ -> stephen@xxx.com:/tmp/stephen/ excluding
.git
app/cache
.idea
rsync: -tsl: unknown option
rsync error: syntax or usage error (code 1) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-47/rsync/main.c(1333) [client=2.6.9]
```

**Comment by axkibe** [comment]
You need rsync > 3.x for Lsyncd to work properly. Even if you remove the
"s" argument, you gonna have issues with files with spaces in them.
Kind regards, Axel

**Comment by thecodeassassin** [comment]
Hi @axkibe ,

While this may solve the problem with protect_args this doesn't solve all the problems on OSX. For example, because you directly use the fsevents device the OS crashes when you force close lsyncd. Leaving me with the problem of having to reboot my OS every time lsyncd or rsync crashes. 

I would suggest using fswatch (https://github.com/emcrisostomo/fswatch) they do a pretty good job at having a stable cross platform api for detecting file changes.

I think if rsync 3.x is required this should actually be a requirement :) It's not really listed anywhere.

**Comment by axkibe** [comment]
```I think if rsync 3.x is required this should actually be a requirement :) It's not really listed anywhere.```

Thanks for that suggestion, will do.

The manual needs a overhaul anyway, I'm fed up with the gollum wiki.

**Comment by thecodeassassin** [comment]
I just implemented the following simple bash script using fswatch.

```bash
#!/bin/bash

echo "Sync script started"
echo

SRC=/srv/shared/sho/
DEST=stephen@remote:/srv/shared/sho

if [ "$SRC" != "" ] ; then

    /usr/local/bin/fswatch -r --latency=0.1 -0 $SRC | xargs -0 -n 1 -I{} /usr/local/bin/rsync -rav -S --force --delete -e "/usr/bin/ssh -i /home/user/.ssh/id_rsa -o StrictHostKeyChecking=no" --exclude="app/cache" --exclude ".idea" $SRC $DEST

     echo "Syncing $SRC to $DEST"

fi
```

If you would change the internal file watcher to use libfswatch (https://github.com/emcrisostomo/fswatch/tree/master/libfswatch) you don't have to worry about implementing it yourself anymore. I would love to make a PR myself but i don't really know C that well :( shame! *rings bell* shame *rings bell*)

**Comment by dktanwar** [comment]
I am getting this error:

```
rsync: on remote machine: -svRe.Ls: unknown option
rsync error: syntax or usage error (code 1) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-51/rsync/main.c(1337) [server=2.6.9]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(600) [sender=3.0.6]
```

Any help?

**Comment by axkibe** [comment]
I listed rsync requirement to be >= 3.0 on source and target machines in the docs:

http://axkibe.github.io/lsyncd/manual/building/
