### ISSUE TITLE
Host key verification failed

### ISSUE THREAD

**Issue by alfredbez** [axkibe/lsyncd#345]
my lsyncd.conf.lua:

```lua
settings {
  logfile = "/var/log/lsyncd/lsyncd.log",
  statusFile = "/var/log/lsyncd/lsyncd.status",
  insist = true
}

sync {
  default.rsyncssh,
  source = "/home/username/projects/projectA",
  host = "username@server.com",
  targetdir = "/home/projectA"
}
```

I see the following error in my logfile:
```
Host key verification failed.
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.1]
```

However, this works as expected:
```
$ ssh username@server.com
```

What's wrong?

**Comment by axkibe** [comment]
Try running rsync manually and see what happens.

**Comment by alfredbez** [comment]
```bash
$ rsync -r /home/username/projects/projectA/ username@server.com:/home/projectA
```
works perfect

`server.com` is actually not `.com` but something intern.

**Comment by axkibe** [comment]
Ok, please run it with -log Exec (or even -log all)

**Comment by alfredbez** [comment]
```
$ lsyncd -log Exec -rsync /home/username/projects/projectA/ username@server.com:/home/projectA
```

I see the following message in /var/log/lsyncd/lsyncd.log:
```
Thu Oct 15 12:52:18 2015 Normal: recursive startup rsync: /home/username/projects/projectA/ -> username@server.com:/home/projectA/
Host key verification failed.
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.1]
Thu Oct 15 12:52:19 2015 Normal: Retrying startup of "/home/username/projects/projectA/": 255
```

/var/log/lsyncd/lsyncd.status:
```
Lsyncd status report at Thu Oct 15 12:55:01 2015

Sync1 source=/home/username/projects/projectA/
There are 2 delays
wait   Init 
block  Create /test1
Excluding:
  nothing.


Inotify watching 1 directories
  1: /home/username/projects/projectA/
```

**Comment by axkibe** [comment]
Akward it misses the lines in that log that say how Lsyncd exactly invokes rsync.

I suppose with -nodaemon it works?

**Comment by alfredbez** [comment]
Yay, that works, thank you very much!

**Comment by axkibe** [comment]
I suppose it has something to do with Lsyncd deamonizing itself (changing its working directory to '/') and thus ssh not finding the private key anymore.

Or you got your private key with a passphrase and it thus can only work in your user environment when it can access the respective keyring to decode it.

**Comment by alfredbez** [comment]
Calling lsyncd like so works: `lsyncd -nodaemon -rsync /home/username/projects/projectA/ username@server.com:/home/projectA`

However I want to set it up as a service. I re-created my ssh-public key without a password, but this doesn't work.
How can I debug this to find the error?

**Comment by axkibe** [comment]
I suppose you must tell Lsyncd to tell rsync to tell ssh where to find the identitfy file.
```
sync {
  default.rsyncssh,
  source = "/home/username/projects/projectA",
  host = "username@server.com",
  targetdir = "/home/projectA",
  {
     rsh = "ssh -i /home/username/.ssh/id_rsa"
  }
}
```

Make sure when Lsyncd runs as daemon it has access to the identity file.

**Comment by alfredbez** [comment]
I get the following error: `lsyncd[13288]: Error: error preparing /etc/lsyncd/lsyncd.conf.lua: Parameter "rsh" unknown.`

**Comment by axkibe** [comment]
Sorry try this:
```
sync {
  default.rsync,
  source = "/home/username/projects/projectA",
  target = "username@server.com:/home/projectA",
  rsync = {
     rsh = "ssh -i /home/username/.ssh/id_rsa"
  }
}
```

**Comment by alfredbez** [comment]
hm... I still get `Host key verification failed.`

btw I'm using a VPN, is this relevant?
I will try it with another server, to test this.

**Comment by alfredbez** [comment]
> btw I'm using a VPN, is this relevant?
> I will try it with another server, to test this.

Disconnected from VPN and tried it with other server doesn't worked either...

**Comment by alfredbez** [comment]
Mabye this helps:
```
$ ssh -v username@server.com
OpenSSH_6.7p1 Ubuntu-5ubuntu1.3, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /home/username/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to server.com [1.2.3.4] port 22.
debug1: Connection established.
debug1: identity file /home/username/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /home/username/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/username/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/username/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/username/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/username/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/username/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/username/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.7p1 Ubuntu-5ubuntu1.3
debug1: Remote protocol version 2.0, remote software version OpenSSH_5.5p1 Debian-6+squeeze3
debug1: match: OpenSSH_5.5p1 Debian-6+squeeze3 pat OpenSSH_5* compat 0x0c000000
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client aes128-ctr umac-64@openssh.com none
debug1: kex: client->server aes128-ctr umac-64@openssh.com none
debug1: SSH2_MSG_KEX_DH_GEX_REQUEST(1024<3072<8192) sent
debug1: expecting SSH2_MSG_KEX_DH_GEX_GROUP
debug1: SSH2_MSG_KEX_DH_GEX_INIT sent
debug1: expecting SSH2_MSG_KEX_DH_GEX_REPLY
debug1: Server host key: RSA ab:ab:ab:ab:ab:ab:ab:ab:ab:ab:ab:ab:ab:ab:ab:ab
debug1: Host 'server.com' is known and matches the RSA host key.
debug1: Found key in /home/username/.ssh/known_hosts:4
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: Roaming not allowed by server
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /home/username/.ssh/id_rsa
debug1: Server accepts key: pkalg ssh-rsa blen 535
debug1: Authentication succeeded (publickey).
Authenticated to server.com ([1.2.3.4]:22).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: Sending environment.
debug1: Sending env LANG = en_US.UTF-8
debug1: Sending env LC_CTYPE = de_DE.UTF-8
You have mail.
Last login: Thu Oct 15 21:04:30 2015 from 1.2.3.5
```

**Comment by axkibe** [comment]
Log in as user you want to run Lsyncd with using a Terminal Console (CTRL+ALT+F1) and try running rsync there. This is all not the issue of Lsyncd but your setup to get it right.

**Comment by alfredbez** [comment]
It works now. I had to set up the SSH Key for the root user.

This helped me: [How to Configure Remote Syncing with lsyncd](https://www.digitalocean.com/community/tutorials/how-to-mirror-local-and-remote-directories-on-a-vps-with-lsyncd#how-to-configure-remote-syncing-with-lsyncd) and [How To Set Up SSH Keys](https://www.digitalocean.com/community/tutorials/how-to-set-up-ssh-keys--2)

Thank you @axkibe you pointed me to the right direction!

**Comment by vyachkonovalov** [comment]
With `-i` ssh option you may also specify known_hosts file
```lua
sync {
  -- ...
  rsync = {
    rsh = "ssh -i /home/user/.ssh/id_rsa -o UserKnownHostsFile=/home/user/.ssh/known_hosts"
  }
}
```
and it works without root key

**Comment by etosan** [comment]
"Host key verification failed" means **host key of the server** you are connecting to was not found in ~/.ssh/known_hosts of the user under which lsyncd runs.

This can fixed by adding your host to trusted hosts machine-wide, usually by adding it to /etc/ssh/ssh_known_hosts. This way any user on machine will trust the host (without need to modify each user's ~/.ssh/known_hosts)

Next usual error is missing client ssh key. For that people suggested two solutions.

Thrid way is to "prefix" your lsyncd daemon with ssh-agent, which will export ssh environment variables (required so it can be reached by ssh client that rsync uses internallu),  load keys into the ssh-agent and then finally run lsyncd.

**Comment by heaventouch** [comment]
It is useful, thanks.
