### ISSUE TITLE
Error: There can only be one config file in command line.

### ISSUE THREAD

**Issue by sbrl** [axkibe/lsyncd#346]
I found this neat little tool whilst trying to set up a live syncing environment for web development. I installed it through `apt-get`, but then found I got this error as soon as I tried to use it:

```
Error: There can only be one config file in command line.
```

Here's the command I used:
```
lsyncd . starbeamrainbowlabs.com /srv/www
```

Here's my `uname -a`:
```
Linux Snowflake 3.19.0-30-generic #34-Ubuntu SMP Fri Oct 2 22:08:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Can anyone help me?

Thanks.

**Comment by jimbojsb** [comment]
If you didn't already figure this out you're missing the -rsync flag on the command line. I was in the same boat.

**Comment by sbrl** [comment]
Thanks!
