### ISSUE TITLE
--temp-dir with share rsyncd 

### ISSUE THREAD

**Issue by whatvn** [axkibe/lsyncd#347]
Hello, 

I use lsyncd with rsyncd, not through ssh. 

So it my configuration, I specify target = remote_host::share_storage/ 
in this case, how can I specify --temp-dir, how to make it works? 

Thanks,

**Comment by axkibe** [comment]
For example
```
sync {
    default.rsync,
    source    = "/home/user/src/",
    target    = "remote_host::share_storage/",
    rsync     = {
        temp_dir = '/bla'
    }
}
```

see:
https://github.com/axkibe/lsyncd/wiki/Lsyncd%202.1.x%20%E2%80%96%20Layer%204%20Config%20%E2%80%96%20Default%20Behavior

**Comment by whatvn** [comment]
temp_dir = '/bla' means it creates temp_dir  `blah` inside share storage, right? 
So, if I want to create bidirectional lsyncd, is exclude `bla` from lsyncd config can avoid loop?
