### ISSUE TITLE
lsyncd crashes when it cannot change source directory (Segmentation fault)

### ISSUE THREAD

**Issue by rbu** [axkibe/lsyncd#350]
I tried setting up lsyncd with rsyncssh in a user<->user mode (as opposed to running as root on source and target), however I noticed it crashes when root or other users place directories into its source that lsyncd's user cannot change.

Is this not supported? I found no such information in the man page or wiki.

This is CentOS7 with 2.1.5 from EPEL.

```
11:16:27 Call: inotifyEvent( )
11:16:27 Inotify: got event Create 22600/(2)
11:16:27 Function: Inotify.addWatch( /mnt/something/owned/by/root/ )
Segmentation fault

user@host $ touch /mnt/something/owned/by/root/
touch: setting times of ‘/mnt/something/owned/by/root/’: Permission denied
```

**Comment by axkibe** [comment]
Works for me if I add a directory as root within the watched directory, with an umask 0077 so the user running Lsyncd cannot read it. It gets skipped.
```
10:55:59 Call: inotifyEvent( )
10:55:59 Inotify: got event Create test/(1)
10:55:59 Function: Inotify.addWatch( /home/axel/lsyncd/src/test/ )
10:55:59 Inotify: addwatch( /home/axel/lsyncd/src/test/ )-> -1; err= 13 : Permission denied
10:55:59 Inotify: Unable to add watch "/home/axel/lsyncd/src/test/"
10:55:59 Function: delay( Sync1, Create, /test/, (nil) )
10:55:59 Delay: New Create:/test/
```

**Comment by axkibe** [comment]
PS; Yes sorry for leaving this lying for so long, if you can provide more detailed instructions how to raise the Segfault please provide them and reopen the issue.

**Comment by rbu** [comment]
I cannot reproduce this issue anymore in production either, although the version in use has not changed.
