### ISSUE TITLE
Timestamps to logfiles

### ISSUE THREAD

**Issue by sveredyuk** [axkibe/lsyncd#351]
I meet some issue and googled a lot of time but can't found any suggestion about this. Details here: http://serverfault.com/questions/733826/how-to-add-timestamps-to-lsyncd-log-output-files

Please, help me who can. Thx a lot!

**Comment by axkibe** [comment]
just log via syslog instead.

**Comment by sveredyuk** [comment]
Some more details ? please

**Comment by axkibe** [comment]
If you dont put a logFile setting it will log via syslog.

**Comment by sveredyuk** [comment]
Yes, and got log files, like:

==> /var/log/lsyncd.log <==
rsync error: unexplained error (code 255) at io.c(600) [sender=3.0.6]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]rsync error: unexplained error (code 255) at io.c(600) [sender=3.0.6]

rsync error: unexplained error (code 255) at io.c(600) [sender=3.0.6]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(600) [sender=3.0.6]

==> /var/log/lsyncd-status.log <==
  2754: /tftpboot/images/centos5/diskless/snapshot/00-50-56-9f-11-b8/bootscripts/
  2755: /tftpboot/images/centos5/diskless/snapshot/00-50-56-9f-11-b8/etc/
  2756: /tftpboot/images/centos5/diskless/snapshot/00-50-56-9f-11-b8/etc/ssh/
  2757: /tftpboot/images/centos6/

and i need to have timestamp for each line.

**Comment by axkibe** [comment]
Well I guess you DO have a logfile setting, but if you don't, Lsyncd will log via syslog.

**Comment by axkibe** [comment]
sorry its another issue, this is an rsync error you are seeing, not an Lsyncd error.

Lsyncd DOES write timestamps on every of its messages even if using logfile setting

**Comment by sveredyuk** [comment]
Hopes for this, but no. My lsyncd-status.log don't has any timestamps.

**Comment by axkibe** [comment]
The status logs timestamp is the timestamp of the whole file. you can see that with ls -l

**Comment by Tu-114-s-undercarriage** [comment]
What we want:
```
[2020-05-06 09:21:54]
sent 65 bytes  received 19 bytes  168.00 bytes/sec
total size is 0  speedup is 0.00
20200506/aaaa.csv

[2020-05-06 09:26:16]
sent 138 bytes  received 31 bytes  338.00 bytes/sec
total size is 0  speedup is 0.00

[2020-05-06 09:32:02]
sent 102 bytes  received 12 bytes  76.00 bytes/sec
total size is 0  speedup is 0.00
20200506/bbbb.csv

[2020-05-06 09:40:47]
sent 143 bytes  received 31 bytes  348.00 bytes/sec
total size is 0  speedup is 0.00

[2020-05-06 09:55:22]
sent 107 bytes  received 12 bytes  79.33 bytes/sec
total size is 0  speedup is 0.00
20200506/aaaa.csv

[2020-05-06 10:02:33]
sent 140 bytes  received 31 bytes  342.00 bytes/sec
total size is 0  speedup is 0.00

[2020-05-06 10:13:25]
sent 104 bytes  received 12 bytes  232.00 bytes/sec
total size is 0  speedup is 0.00
20200506/aaaa.csv

[2020-05-06 10:21:08]
sent 137 bytes  received 31 bytes  112.00 bytes/sec
total size is 0  speedup is 0.00

[2020-05-06 10:27:55]
sent 101 bytes  received 12 bytes  226.00 bytes/sec
total size is 0  speedup is 0.00
20200506/situ62.bbbb.csv
```
And there is what he got:
```
sent 65 bytes  received 19 bytes  168.00 bytes/sec
total size is 0  speedup is 0.00
20200506/aaaa.csv

sent 138 bytes  received 31 bytes  338.00 bytes/sec
total size is 0  speedup is 0.00

sent 102 bytes  received 12 bytes  76.00 bytes/sec
total size is 0  speedup is 0.00
20200506/bbbb.csv

sent 143 bytes  received 31 bytes  348.00 bytes/sec
total size is 0  speedup is 0.00

sent 107 bytes  received 12 bytes  79.33 bytes/sec
total size is 0  speedup is 0.00
20200506/aaaa.csv

sent 140 bytes  received 31 bytes  342.00 bytes/sec
total size is 0  speedup is 0.00

sent 104 bytes  received 12 bytes  232.00 bytes/sec
total size is 0  speedup is 0.00
20200506/aaaa.csv

sent 137 bytes  received 31 bytes  112.00 bytes/sec
total size is 0  speedup is 0.00

sent 101 bytes  received 12 bytes  226.00 bytes/sec
total size is 0  speedup is 0.00
20200506/situ62.bbbb.csv
```
