### ISSUE TITLE
relative ^d.targetPathname? 

### ISSUE THREAD

**Issue by hongkongkiwi** [axkibe/lsyncd#352]
Hi,

I'm looking to use this alongside acd_cli tool to upload to Amazon Cloud Drive.

Essentially I would capture operations so for example, if a file is moved from /mnt/Movies/1 to /mnt/Movies/2 then it would execute acd_cli mv /mnt/Movies/1 /2

In this case, /mnt/Movies is my root dir. But I couldn't see anyway to get simply the new relative path of the file that's being moved without getting the absolute directory path.

Is there something I'm missing?

**Comment by axkibe** [comment]
I suppose you mean ^pathname ?
