### ISSUE TITLE
Host key verification failed.

### ISSUE THREAD

**Issue by tdyhacker** [axkibe/lsyncd#353]
I am using lsyncd to sync file between two vps. but it give me some error:
```
Host key verification failed.
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.0]
Thu Nov 12 16:13:34 2015 Error: Temporary or permanent failure on startup of "/source/to/copy/". Terminating since "insist" is not set.
```
first,I think the ssh key is fault,but when I try to use `rsync -r -ltsd --delete /source/to/copy root@xx.xxx.xxx.xx:/root/testsync`,it works,so I can't find where is wrong  

my config file is as following:
```
settings {
        logfile = "/var/log/lsyncd/lsyncd.log",
        statusFile = "/var/log/lsyncd/lsyncd.status"
}
sync {
        default.rsync,
        source = "/source/to/copy",
        target = "root@xx.xx.xx.xx:/root/testsync",
        -- targetdir = '/root/testsync'
}
```

**Comment by jfgrissom** [comment]
I have the same issue.

This works just fine running as root:
rsync -avzO /path/to/source/ -e 'ssh -i /home/lsync/.ssh/id_rsa' lsync@host.domain.tld:/path/to/destination/

However when I try to do this in lsync I get the same "Host key verification failed" message. 

I've tried many variations on this and they all fail:
`sync{
    default.rsyncssh,
    source    = "/path/to/source/",
    host      = "lsync@my.fqdn.tld",
    targetdir = "/path/to/target/",
    rsync     = {
        archive  = true,
        compress = true,
        _extra   = {"-O", "ssh -i /home/lsync/.ssh/id_rsa"}
    }
}`

Any thoughts on this would be really appreciated.
=)

**Comment by axkibe** [comment]
@tdyhacker  in your case, I suppose you just need to log in normally once via ssh and accept the host key.

@jfgrissom "default.rsyncssh" uses rsync and ssh channels to communicate with the target, if you change the rsync {} settings, you must change the ssh{} settings approperiately. For simplicity I adive to use just "default.rsync", in that case no seperate ssh channel is used, and thus doesn't need to be configured.

**Comment by jfgrissom** [comment]
@axkibe 

You're awesome. Thanks for this!

Here is how it works if anyone else is struggling with this:
1) Install lsyncd
2) Create your user and keys.
3) Share the public key to your target server.
4) Test login from your source server to your target at least once (to accept the host key).
5) Define your configuration like this below (where lsync is the user and /home/lsync/.ssh/id_rsa is the private key).
6) Start lsyncd (systemctl start lsyncd - Centos 7)

```
sync{
    default.rsync,
    source    = "/path/to/source/",
    target    = "lsync@my.fqdn.tld:/path/to/target/",
    rsync     = {
        archive  = true,
        compress = true,
        _extra   = {"--omit-dir-times","-e ssh -i /home/lsync/.ssh/id_rsa"}
    }
}
```

**Comment by vsile** [comment]
@jfgrissom 
Thanks!
I had the same issue.
It works with your config!

**Comment by jfgrissom** [comment]
@vsile

Thanks for the feedback, I was worried it didn't make any sense! 

Haha

I'm very glad it helped you!

**Comment by dale-c-anderson** [comment]
In my case, it still didn't work after accepting the host key as the specified user. It ended up being the other way around -- I had to to accept the host key as root before it would work:

`[root@source ~]# ssh user@destination -i /home/user/.ssh/id_rsa`

I'm using version 2.1.5 from epel on CentOS 6.7.

**Comment by catchmareck** [comment]
I had the same issue. My config was as follows:

`settings {
        logfile="/var/log/lsyncd/lsyncd.log",
        statusFile="/var/log/lsyncd/lsyncd.status"
}

sync {
        default.rsyncssh,
        source="/var/www/html",
        host="user@host.com",
        targetdir="/backup/html/"
}
`

I have generated the ssh keys for user `user` but since the service `lsyncd` is started as root, you need to generate the ssh keys as root, e.x. `sudo ssh-keygen -t rsa` and then copy the `id_rsa.pub` file to the `authorized_keys` on the remote machine.
