### ISSUE TITLE
misbehaving with "--remove-sent-files"  or "--remove-source-files"

### ISSUE THREAD

**Issue by khaderkool** [axkibe/lsyncd#354]
Hello ,
I am running into this problem deletion problem with lsyncd
# Details:

   lsyncd --version
   Version: 2.1.5
# my lsyncd file:

settings{
  logfile         = "/var/log/lsyncd.log",
  statusFile      = "/var/log/lsyncd.stat",
  statusInterval = 20,
 pidfile="/tmp/lsyncd.pid"
}
sync{
  default.rsync,
  source="/media/local/source-log/",
  target="/media/store/machine-a/files/destination-log/",
  rsync = {
    archive = true,
    compress = false,
    _extra = {
      "-ltusavz","--remove-sent-files", "--compress"
    }

   }

}

If i create direction with a file (dir/file.txt) under source folder, this will automagically gets copied do destination directory.
But when Lsynd does "deletion" of source file (file.txt), this will is also getting deleted on destination. 
I want to retain the file(s) on destination directory, please help me.
FYI: I searched for "lrsync.lua" on my centos m/c, i found it only under example folder (/usr/share/doc/lsyncd-2.1.5/examples/lrsync.lua)

**Comment by Episodio1** [comment]
There is "delete" parameter with 4 possible values. You have to set it as "false".

sync{
        default.rsync,
        source=
        target=
      **  delete = false,**
....
....

**Comment by axkibe** [comment]
Ya, as Episodio1 said, otherwise Lsyncd will transfer the delete operation as well, since it keeps stuff in sync...
