### ISSUE TITLE
Add options for "--omit-dir-times" and "--omit-link-times".

### ISSUE THREAD

**Issue by selivan** [axkibe/lsyncd#356]
This is required if you are running lsyncd from non-root user.

**Comment by chimpy** [comment]
You can already add these in the rsync extra option.

**Comment by selivan** [comment]
> Note that the underscore highlights this as workaround. If you need something that is not covered by the above options, please request it via a feature request on the project website

**Comment by axkibe** [comment]
Yes, yes will do.

**Comment by axkibe** [comment]
done with latest git.
