### ISSUE TITLE
default.rsync pass source directory

### ISSUE THREAD

**Issue by g980** [axkibe/lsyncd#357]
default.rsync pass source directory to a rsync. I expect it is directory of modified files.

   my conf is:

sync { default.rsync,
        source = "/a",
        target = "/b",
        init = false
}

   my operation is:

$ touch /a/b/c/d/e/f/g

   lsyncd.log is:

Fri Dec  4 13:34:08 2015 Normal: Calling rsync with filter-list of new/modified files/dirs
/b/c/d/e/f
/b/c/d/e/
/b/c/d/
/b/c/
/b/
/

   executed binary is:

/usr/bin/rsync -slt -r --delete --ignore-errors --force --from0 --include-from=- --exclude=* /a/ /b/

   my expectation is:

/usr/bin/rsync -slt -r --delete --ignore-errors --force --from0 --include-from=- --exclude=* /a/b/c/d/e/f/ /b/

**Comment by axkibe** [comment]
If I recall correctly, you expectation would put the files at the correct place on the target.

Note that "--include-from=-" means, Lsyncd passes the filter over stdin to rsync, it would often be too long to put it as call parameters directly.

**Comment by g980** [comment]
Sorry, I correct my writing.

   my expectation is:

/usr/bin/rsync -slt -r --delete --ignore-errors --force --from0 --include-from=- --exclude=* /a/b/c/d/e/f/ /b/b/c/d/e/f/

**Comment by axkibe** [comment]
In the special event of just one change this would be okay, however Lsyncd creates the above call from a general rule that encompasses a possible multitude of files.

It uses stdin to tell rsync via filters exactly which files need transfering, so I don't see the problem with the call as it is compared to your expectation.

**Comment by g980** [comment]
I have understood now. "/a/b/c/d/e/f/" come from stdin, probably...
Thank you for your comment. Sorry for stealing your time.
