### ISSUE TITLE
Why is copy_links enabled by default?

### ISSUE THREAD

**Issue by archon810** [axkibe/lsyncd#358]
https://github.com/axkibe/lsyncd/blob/5f74865f687d88d53b1af6082f2737bbd02b462b/default-rsync.lua lists copy_links as enabled by default.

But the name of this option is quite confusing. rsync manual says:

```
-L, --copy-links
              When symlinks are encountered, the item that they point to (the referent) is copied, rather than the symlink.
```

Why would we want this enabled by default? We want symlinks to be copied as symlinks, don't we?

Oddly, while I'm not disabling copy_links in my config, symlinks are still copied as symlinks. So I'm confused.

**Comment by axkibe** [comment]
It is not enabled by default. The code you are possibly referring to lists it as a valid option.

**Comment by archon810** [comment]
@axkibe I'm also looking here https://github.com/axkibe/lsyncd/wiki/Lsyncd-2.1.x-%E2%80%96-Layer-4-Config-%E2%80%96-Default-Behavior, and it says copy_link = true as well there. Are those not default values?

**Comment by axkibe** [comment]
No, it is the line in the config to turn them on.

**Comment by archon810** [comment]
Bah, then I (and I'm sure many others) am totally confused by the tables and the wiki. When you have a page that says Default Behavior in the title, then lists "rsync.default" as the section, and has values of "true" next to each config param, I don't understand who wouldn't assume those are the default values and wouldn't end up confused.
