### ISSUE TITLE
lsyncd.service doesn't copy over file changes

### ISSUE THREAD

**Issue by mogthesprog** [axkibe/lsyncd#359]
Hi guys,

This is potentially a misunderstanding on my part, but figured i better ask.

I've configured lsyncd on one of my centos7 boxes. I've used the following config file

```
----
-- User configuration file for lsyncd.
--
-- Simple example for default rsync, but executing moves through on the target.
--
-- For more examples, see /usr/share/doc/lsyncd*/examples/
--
settings {
        logfile = "/var/log/lsyncd/lsyncd.log",
        statusFile = "/var/log/lsyncd/lsyncd.status",
        statusIntervall = 20
}

sync{   default.rsyncssh,
        source="/nfs/science/computer-science/morganj",
        host="someuser@somehostname",
        targetdir="/nfs/science/computer-science/morganj",
        delay=30,
        rsync={rsh="ssh -i /home/someuser/.ssh/id_dsa -o StrictHostKeyChecking=no"
                },
        }
```

The first sync finished fine. which is great, but then I tried to add a file to the directory in the hope that it would be copied over after 30 seconds. but it doesn't.

I start the service with

```
systemctl start lsyncd
```
and the service is still alive after the initial sync. Any ideas?

Also, it seems that the watch list in /var/log/lsyncd/lsyncd.status stops at 7379.... even though my inotify limit is much  much higher. I'm guessing it's a config problem on my part.

Cheers in advance for the help,
Morgan

**Comment by axkibe** [comment]
You cannot have NFS as a source dir to watch, since NFS doesn't support watches. Unless the NFS/Kernel situation changes for this, Lsyncd needs to run on the machine that has direct control to the filesystem.

**Comment by mogthesprog** [comment]
Hi guys, sorry for slow reply. It seems that it is working now, and it is on NFS so i'm not sure how inotify is working?

Cheers for the help anyway

**Comment by axkibe** [comment]
The startup sync will work, further syncing wont.
