### ISSUE TITLE
How should I  edit the configuration file to sync multi target dir with one source dir?

### ISSUE THREAD

**Issue by FavorMylikes** [axkibe/lsyncd#360]
I don't find that in wiki,or write multi rsync label in the conf file?

**Comment by saas2813** [comment]
This seems like a duplicate.
https://github.com/axkibe/lsyncd/issues/388

**Comment by axkibe** [comment]
It's now in the manual.

http://axkibe.github.io/lsyncd/faq/multiple-targets/
