### ISSUE TITLE
How to distribute a custom backend

### ISSUE THREAD

**Issue by YarekTyshchenko** [axkibe/lsyncd#362]
I've written a [docker sync backend][1]. The backend is generic, and you have to configure it in individual sync blocks depending on your specific container names and paths.

How can I distribute the backend to people in a single file they can update but still hardcode the sync blocks in their projects?

```lua
sync {
    docker,
    source = ".",
    target="container:/path/in/container/",
    host=os.getenv("DOCKER_HOST"),
    excludes = {
        '.git'
    },
}
```

  [1]: https://gist.github.com/YarekTyshchenko/4dfd6670b9605ecb15ef

**Comment by axkibe** [comment]
Just let the users do dofile() to include a custom layer 1 backend.
```
dofile('path/to/docker.lua')

sync {
    docker,
    source = ".",
    target="container:/path/in/container/",
    host=os.getenv("DOCKER_HOST"),
    excludes = {
        '.git'
    },
}
```
Basically Lsyncd does nothing else for the build in configs using rsync (except it compiles the lua file into a lua code binary already on build time and binds that into the executable, but it still on startup just calls an execute on that scripts and let it set the respective globals)
