### ISSUE TITLE
Modify rsync command?

### ISSUE THREAD

**Issue by CohenBrianH** [axkibe/lsyncd#366]
The default behavior of rsync in lsyncd is:

`/usr/bin/rsync -ltsd --delete --include-from=- --exclude=* SOURCE TARGET`

I would like to add a command or commands after TARGET:

`/usr/bin/rsync -ltsd --delete --include-from=- --exclude=* SOURCE TARGET CUSTOM_STUFF_HERE`

I don't see any option to do that.  Would it be possible to add a field to the config file that passes a custom string of characters to the end of the rsync command?  This would be incredibly useful since I have a script which passes a notification to my phone when a process completes and pipes in part of the results (it specifies what files were moved and whether rsync was successful or if it failed).

**Comment by CohenBrianH** [comment]
Update:  I modified the source code to include a value called "Custom" and to include its value from the config file at the end of the rsync command, but now it's trying to mkdir [my custom command], which obviously doesn't work. 

`rsync: mkdir "/ &> /tmp/output; tail /tmp/output | pushme $? "rsync"" failed: No such file or directory`

 I'm not sure why that is since it isn't part of the source or target values, and the first part (the output to the log) is correct:

`recursive startup rsync: /Server1/test -> /Server2/test`

**Comment by axkibe** [comment]
This is what _extra is for.
