### ISSUE TITLE
Possible to rsyncssh with a remote source or rsync pull?

### ISSUE THREAD

**Issue by gonzalobustos** [axkibe/lsyncd#368]
Hi, first of all excuse me for asking here.

I want to know if it's possible to pull with lsyncd?

I've successfully used lsyncd to sync a local folder to a server I own using rsyncssh with a config file like this:

```
settings = {
        logfile = "/var/log/lsyncd/lsyncd.log",
        statusFile = "/var/log/lsyncd/lsyncd.status"
}
sync {
        default.rsyncssh,
        source = "/Users/user/source",
        host = "root@xxx.xxx.xxx.xxx",
        targetdir = "/tmp/data",
        rsync = { binary = "/usr/local/bin/rsync" }
} 
```

Now, I want to perform a "pull" to sync a local directory on another machine (different network) with that remote server.

I'm using this config file:

```
settings = {...}
sync {
        default.rsync,
        source = "root@xxx.xxx.xxx.xxx:/tmp/data",
        target = "/home/user/dest",
        rsync = { binary = "/usr/local/bin/rsync", _extra = { "-P", "-e", "ssh" } }
}
```

but I got this error:

```
Error: failure getting absolute path of [root@xxx.xxx.xxx.xxx:/tmp/data]
Error: Cannot access source directory: root@xxx.xxx.xxx.xxx:/tmp/data
```

Is it possible to use rsync the way I'm using it?
Or rsyncssh with a remote source?

Thanks!

**Comment by Adonai** [comment]
I looked for same option, but trying and failing made me think a bit. Lsyncd needs `inotify` kernel events to work properly. How's it supposed to catch remote inotify events then? So I assume, lsyncd works only with local source (unless you manage to send remote kernel `inotify` events to the pulling side somehow so it will know which file to request).

It's not clearly stated in documentation, though.
Prior to closing this, please, upgrade the doc. This will save someone's time.

**Comment by axkibe** [comment]
Indeed Lsyncd must run where the files are located.

It is said in the first sentence in the manual...

```Lsyncd watches a **local** directory trees event monitor interface (inotify or fsevents).```
