### ISSUE TITLE
Delete remote file with key based auth

### ISSUE THREAD

**Issue by rmazzotta** [axkibe/lsyncd#369]
I can not for the life of me get lsync to delete files remotely.  I am using a no-pass key for auth. copying new and updating changed works just fine.  Deleting however is not working.  If I restart lsyncd the file actually deletes.  But when it tries to delete a file during the  normal operation I get the following:

Tue Apr 12 20:23:08 2016 Normal: Finished (list): 0
Tue Apr 12 20:23:40 2016 Normal: Deleting list
/etc/dir//123
Permission denied (publickey).

My plain rsync command is:
rsync -rvzl -e "ssh" --rsync-path="sudo rsync" /etc/dir/ 10.2.1.20:/etc/dir/

My lsync conf is:
settings {
        logfile = "/var/log/lsyncd/lsyncd.log",
        statusFile = "/var/log/lsyncd/lsyncd.status"
}

sync {
        default.rsyncssh,
        source = "/etc/dir/",
        host = "10.2.1.20",
        targetdir = "/etc/dir/",
	delete = true,
rsync = {
	links = true,
	verbose = true,
	rsh = "/usr/bin/ssh -l admin -i /home/admin/.ssh/id_rsa",
	rsync_path = "sudo rsync"
	}
}

**Comment by axkibe** [comment]
If you change the user and id file with rsh, you have to do the same thing with the ssh connection.

I advise using simple "default.rsync" config and leave the ssh fluff away.

**Comment by rmazzotta** [comment]
I am confused.  I though default.rsync is for local sync not remote?  I am trying to copy to another server.

**Comment by axkibe** [comment]
default.direct is for local.

**Comment by rmazzotta** [comment]
Does nto work at all.  Permission denied.

sync {
        default.rsync,
        source = "/etc/dir/",
	target = "10.2.1.20:/etc/dir/",
	delete = true,
}

**Comment by rmazzotta** [comment]
got it!! thank you for your help!!

sync {
        default.rsync,
        source = "/etc/dir/",
	target = "admin@10.2.1.20:/etc/dir/",
	delete = true,
rsync = {
	links = true,
	verbose = true,
	rsh = "/usr/bin/ssh -l admin -i /home/admin/.ssh/id_rsa",
	rsync_path = "sudo rsync"
	}
}

**Comment by RaimundasR** [comment]
> got it!! thank you for your help!!
> 
> sync {
> default.rsync,
> source = "/etc/dir/",
> target = "admin@10.2.1.20:/etc/dir/",
> delete = true,
> rsync = {
> links = true,
> verbose = true,
> rsh = "/usr/bin/ssh -l admin -i /home/admin/.ssh/id_rsa",
> rsync_path = "sudo rsync"
> }
> }

Just would like to inform that this issue I have only on ubuntu 18, so from Ubuntu 20.04 everything works fine with "rsh".

But this one was a great solution form me, thank you :)

**Comment by ychaouche** [comment]
Came here to give a thanks too,
I was struggling with lsyncd 2.1.5 that didn't want to hear about my ssh identity key no matter what.
I've been pulling my hair on this.
Thanks again.

btw, I didn't have to use rsync_path
since I use lsyncd as root via sudo anyway,
same for specifying the user in the target variable or the -l switch.
Here's my conf

```
settings {
   logfile        = "/var/log/lsyncd.log",
   statusFile     = "/var/log/lsyncd.status",
   insist         = true,
   nodeamon       = true,
   verbose        = true
}

sync {
  default.rsync,  
  source        = "/home/ychaouche/SYNCHRO",
  target        = "10.10.10.82:/root/SYNCHRO",
  rsync = {
     copy_links = true,
     rsh = "/usr/bin/ssh -i /root/.ssh/idroot",      
  }  
}
```
