### ISSUE TITLE
lsyncd in default.direct mode copy file without datetime

### ISSUE THREAD

**Issue by programmerj** [axkibe/lsyncd#370]
Hello!

lsyncd in "default.direct" mode copy file without datetime.
And source and destination files have different date and time:
source - original datetime, destination - datetime of copy.

As I see it copy by cp command, could you please add switch -p to copy date attribute of file?

Thanks.

**Comment by axkibe** [comment]
Fair enough. Added. Will be default for Lsyncd 2.1.7
