### ISSUE TITLE
Rename local file that is missing on destination

### ISSUE THREAD

**Issue by viorel-m** [axkibe/lsyncd#371]
If I delete synced file from destination server and then rename it on local server, lsyncd doesn't recreate it until restart.
```
Moving /test_4.png -> /test_5.png
mv: cannot stat '/destination/Documents//test_4.png': No such file or directory
```
then, after restart, the file is created, like it should without restarting lsyncd 
```
sending incremental file list
./
test_5.png
```

**Comment by axkibe** [comment]
Lsyncd has no way to know what you're doing on the destination, it suppose they are in sync and if you break that it breaks.

If you go out of sync you'll have to restart or HUP signal Lsyncd to have it make a full startup sync.

**Comment by viorel-m** [comment]
So you cannot make something like : if file missing, transfer it from source without restarting lsyncd.

Ok, ty for answer.

**Comment by axkibe** [comment]
If you use default.rsync instead of default.rsyncssh moved files will always be recreated.
