### ISSUE TITLE
error: 'struct dirent' has no member named 'd_type'

### ISSUE THREAD

**Issue by geekrohit** [axkibe/lsyncd#375]
Am trying to compile this on illumos (SunOS) , getting this : 

cmake -DCMAKE_C_FLAGS="-std=gnu99" -DWITH_INOTIFY=OFF -DWITH_FSEVENTS=ON -Wno-dev .
-- Configuring done
-- Generating done
-- Build files have been written to: /root/lsyncd-master
[root@test ~/lsyncd-master]# make
Scanning dependencies of target lsyncd
[ 10%] Building C object CMakeFiles/lsyncd.dir/lsyncd.c.o
/root/lsyncd-master/lsyncd.c: In function 'get_realpath':
/root/lsyncd-master/lsyncd.c:182:3: warning: #warning having to use old style realpath() [-Wcpp]
 # warning having to use old style realpath()
   ^
/root/lsyncd-master/lsyncd.c: In function 'l_readdir':
/root/lsyncd-master/lsyncd.c:1469:9: error: 'struct dirent' has no member named 'd_type'
   if( de->d_type == DT_UNKNOWN )
         ^
/root/lsyncd-master/lsyncd.c:1469:21: error: 'DT_UNKNOWN' undeclared (first use in this function)
   if( de->d_type == DT_UNKNOWN )
                     ^
/root/lsyncd-master/lsyncd.c:1469:21: note: each undeclared identifier is reported only once for each function it appears in
/root/lsyncd-master/lsyncd.c:1493:14: error: 'struct dirent' has no member named 'd_type'
    isdir = de->d_type == DT_DIR;
              ^
/root/lsyncd-master/lsyncd.c:1493:26: error: 'DT_DIR' undeclared (first use in this function)
    isdir = de->d_type == DT_DIR;
                          ^
/root/lsyncd-master/lsyncd.c: In function 'l_configure':
/root/lsyncd-master/lsyncd.c:1602:16: error: 'facilitynames' undeclared (first use in this function)
    for( i = 0; facilitynames[ i ].c_name; i++ )
                ^
CMakeFiles/lsyncd.dir/build.make:85: recipe for target 'CMakeFiles/lsyncd.dir/lsyncd.c.o' failed
make[2]: *** [CMakeFiles/lsyncd.dir/lsyncd.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/lsyncd.dir/all' failed
make[1]: *** [CMakeFiles/lsyncd.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Any ideas what can be done or what am I missing?

**Comment by axkibe** [comment]
Aside from this issue, SolarisOS does not have inotify, so you won't be able to run Lsyncd there. As I googled it does have "FEN" as alternative (I can't yet say if it would sufficide for Lsyncd needs). Anyway there is no FEN backend in Lsyncd coded, currently there is only inotify, and OSX /dev/fsevents, for which the Lsyncd code is out-of-dated and broken, so right now its really only inotify that works.
