### ISSUE TITLE
Synchronizing multiple directory in multiple server

### ISSUE THREAD

**Issue by stevenhasanuddin** [axkibe/lsyncd#376]
Hi,

I have managed to synchronize a directory between 3 servers with the following config file,

```
settings = {
        logfile = "/var/log/lsyncd/lsyncd.log",
        statusFile = "/var/log/lsyncd/lsyncd-status.log",
        statusInterval = 1,
}

serverList = {
 "192.168.1.2:/var/www/html/synchronized",
 "192.168.1.3:/var/www/html/synchronized",
}

for _, server in ipairs( serverList ) do
  sync{
        default.rsync,
        delete = 'running',
        source="/var/www/html/synchronized",
        target=server,
        delay = 0,
        rsync={rsh ="/usr/bin/ssh -l steven -i /home/steven/.ssh/id_rsa", _extra = {"--chmod=Fo=rw,Fg=rw"},}
  }
end
```

The problem with the config file is that it only synchronize 1 directory whereas I have more than 1 directory that I want to synchronize, all the 3 servers are having the exact same directory tree, is there anyway I could achieve this?

Thanks!

**Comment by axkibe** [comment]
How about this?
```
serverList = {
 "192.168.1.2:/var/www/html/synchronized",
 "192.168.1.3:/var/www/html/synchronized",
}

sourceList =
{
        "/var/www/html/synchronized",
        "/var/someplace/synchronized",
}

for _, server in ipairs( serverList ) do
  for _, source in ipairs( sourceList ) do
    sync{
          default.rsync,
          delete = 'running',
          source=source,
          target=server,
          delay = 0,
          rsync={rsh ="/usr/bin/ssh -l steven -i /home/steven/.ssh/id_rsa", _extra = {"--chmod=Fo=rw,Fg=rw"},}
    }
  end
```

Note that 'delay = 0' will not allow Lsyncd to combine any events, like the usual 3-fold "create, attrib, close_write" event on a new file arriving at almost the same time., will result in 3 calls to rsync... I'd go with a delay of at least 1 second.

**Comment by stevenhasanuddin** [comment]
Hi Axel,

Thanks for responding to my question!

It seems that the above code will work differently, what I'm trying to achieve is something like this,

I have 2 directories A and B in all 3 servers and I want directory A on server 1 to be synchronized with directory A on server 2 and 3, the same case for directory B.

Are we able to achieve this?

And do you mind explaining more about the following please,

`Note that 'delay = 0' will not allow Lsyncd to combine any events, like the usual 3-fold "create, attrib, close_write" event on a new file arriving at almost the same time., will result in 3 calls to rsync... I'd go with a delay of at least 1 second.`

Thanks!

**Comment by axkibe** [comment]
I don't understand how it will be differently.

About the delay, Lsyncd optimizes stuff by combining multiple events, it can only do this tough, when it has the chance to do so. With a delay of zero, every event will *immidetaly* result in a rsync call, but usually most file events come in packs of several smaller events.

**Comment by stevenhasanuddin** [comment]
Hi Axel,

If I understand it correctly, the configuration file that you provided above will synchronize         "/var/www/html/synchronized" to "192.168.1.2:/var/www/html/synchronized", and "/var/someplace/synchronized"to "192.168.1.2:/var/www/html/synchronized",

where as what I'm trying to achieve is to get

/var/www/html/one to 192.168.1.2:/var/www/html/one and
/var/www/html/two to 192.168.1.2:/var/www/html/two

Kindly correct me if I'm wrong.

**Comment by axkibe** [comment]
Kindly corrected.

**Comment by axkibe** [comment]
Ah no wait a second

**Comment by axkibe** [comment]
How about this?
```
serverList = {
 "192.168.1.2",
 "192.168.1.3",
}


-- be carefull non of them is a parent directory of another
sourceList =
{
        "/var/www/html/synchronized",
        "/var/someplace/synchronized",
}

for _, server in ipairs( serverList ) do
  for _, source in ipairs( sourceList ) do
    sync{
          default.rsync,
          delete = 'running',
          source=source,
          target=server .. ':' .. source,
          delay = 0,
          rsync={rsh ="/usr/bin/ssh -l steven -i /home/steven/.ssh/id_rsa", _extra = {"--chmod=Fo=rw,Fg=rw"},}
    }
  end
end
```

**Comment by stevenhasanuddin** [comment]
Hey Axel,

First I tried,

`          target=server:source,`

which didn't seem to be right syntax.

Yours works perfectly!

`          target=server .. ':' .. source,`

I have tested and the synchronization works without any issue!

Thanks so much for your help!

**Comment by UndiFineD** [comment]
thank you so much for this, here is mine.
```
serverList = {
 "192.168.0.8",
}


-- be carefull non of them is a parent directory of another
sourceList =
{
        "/boot",
        "/etc",
        "/bin",
        "/sbin",
        "/root",
        "/lib",
        "/lib32",
        "/lib64",
        "/opt",
        "/srv",
        "/usr",
        "/var",
        "/home",
}


for _, source in ipairs( sourceList ) do
  for _, server in ipairs( serverList ) do
  sync{
    default.rsync,
    source=source,
    target="/mnt/backup/" .. source,
    delay = 60,
    rsync ={
      binary   = "/usr/bin/rsync",
      archive  = true,
      --backup   = true,
      checksum = true,
      --copy_dirlinks = true,
      copy_links = true,
      hard_links = true,
      owner = true,
      perms = true,
      times = true,
      update = true,
    }
  }
  end
end
```
