### ISSUE TITLE
fatal error: signal.h: No such file or directory

### ISSUE THREAD

**Issue by goodryb** [axkibe/lsyncd#377]
when  I install the program，it's return an error message

OS: CentOS Linux release 7.2.1511 (Core)

\# make

[ 11%] Building C object CMakeFiles/lsyncd.dir/lsyncd.c.o

In file included from /root/lsyncd-master/lsyncd.c:18:0:

/root/lsyncd-master/lsyncd.h:24:20: fatal error: signal.h: No such file or directory

 #include \<signal.h\>
                    ^
compilation terminated.

make[2]: *** [CMakeFiles/lsyncd.dir/lsyncd.c.o] Error 1

make[1]: *** [CMakeFiles/lsyncd.dir/all] Error 2

make: *** [all] Error 2

**Comment by axkibe** [comment]
This is very likely not a Lsyncd issue, but you don't have the necessary package installed on your system.

Please try asking on your distros forums, reopen if sure its a Lsyncd issue.
