### ISSUE TITLE
Syncing one source to multple targets in lsyncd 2.0

### ISSUE THREAD

**Issue by axkibe** [axkibe/lsyncd#38]
Originally filed by pkbook...@gmail.com on 2010-12-14T18:45:11

What steps will reproduce the problem?
1. sudo lsyncd [options] [source] [target] [target]
2.
3.

What is the expected output? What do you see instead?
In previous versions I believe you were able to sync one source to multiple targets. When I supply the syntax for multiple targets I get an error that says I'm only allowed one config file. So Lsyncd is reading one of my targets as the location of the config file. 

What version of the product are you using? On what operating system?
lsyncd 2.0 Ubuntu 10.0.4 Server

Please provide any additional information below.
Is syncing one source to multiple targets even possible with 2.0? If it is how would I accomplish that without getting the error? Is this a bug? Thanks for your help. Love your work by the way!

**Comment by Taisgeal** [comment]
Hello Axel,

I have recently come across this and find it much better than GlusterFS or DRBD as a solution to keeping servers in sync. Thank you very much for your hard work in setting up and making available such a fantastic tool.

My problem is that my conf file is only working on the first target server.For reference, here it is -

settings  {
	logfile = "/var/log/lsyncd/lsyncd.log",
	statusFile = "/var/log/lsyncd/lsyncd.status"
}

servers ={
	"x.x.x.x",
	"x.x.x.x"
}

for _, server in ipairs(servers) do

sync {
	default.rsyncssh,
	delete = true,
	source = "/src",
	host = server,
	targetdir = "/target",
        rsync = {
        archive = true,
	perms = true,
	owner = true,
	_extra = {"-a"},
	},
	delay = 5,
	maxProcesses = 4,
}
end

Thank you for any help or pointers.

Kind Regards.

**Comment by Taisgeal** [comment]
My apologies. The problem was an incorrect ssh key.

Thanks again.

Kind Regards,
