### ISSUE TITLE
syncing issue when remote host is unavailable

### ISSUE THREAD

**Issue by good2go3** [axkibe/lsyncd#381]
Hello,

I am experiencing an issue while I am syncing a local directory with a target on a  remote server when the remote is unreachable.

Newly created files in the source local dir are not synchronized on the remote server when it come back up. As a result my servers are no longer mirrored.

As a workaround, I restart lsyncd on a regular basis to perform the init rsync.

But, do you have any settings allowing to queue all non applied changes?

Thank you for your support

**Comment by axkibe** [comment]
Actually Lsyncd is designed to do exactly this and normally it works.

Please try collect log files of a minimal example where it doesn't work.

**Comment by good2go3** [comment]
The following is a sample of lsyncd.log

Basically, sftp01-down files have been created in source folder when the remote server was unreachable.

Then, I start the remote server and created  sftp01-up files and only these files were syncing.
 
Mon May 30 13:32:23 2016 Normal: Rsyncing list
/sftp01-down1
/sftp01-down2
/sftp01-down3
/sftp01-down4
/sftp01-down5
ssh: connect to host 10.128.4.21 port 22: No route to host
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(605) [sender=3.0.9]
Mon May 30 13:32:41 2016 Normal: Finished a list = 12
Mon May 30 13:35:31 2016 Normal: Rsyncing list
/sftp01-up1
/sftp01-up2
/sftp01-up3
/sftp01-up4
/sftp01-up5
Mon May 30 13:35:32 2016 Normal: Finished a list = 0

**Comment by axkibe** [comment]
Which Lsyncd version is this?

**Comment by axkibe** [comment]
"Mon May 30 13:32:41 2016 Normal: Finished a list = 12"

This is the problem, exit code 12 should normally be a Retry, and it is marked as such in the exitcode table. However, I dimly remember there was some issue with the exitcode code that fixed a few versions back.

**Comment by axkibe** [comment]
Closing this, as I suppose this is already fixed with an update Lsyncd version.
