### ISSUE TITLE
How to force lsyncd use specific private ssh key?

### ISSUE THREAD

**Issue by Demitrius** [axkibe/lsyncd#382]
Try setup specific key file.
Setting options like `rsh` or `_extra` don't help.

How can I force lsyncd use other than id_rsa private ssh key?

I try config:

settings {
    delay               = 10,
    maxProcesses        = 3,
    logfile             = "/var/log/lsyncd.log",
    insist              = true,
    nodaemon            = true
}

targetlist = {
    "apix@192.168.220.100"
}

for _, server in ipairs(targetlist) do
    sync {
        default.rsyncssh,
        delete  = false,
        source  = "/opt/jmitty_test",
        rsync   = {
            binary              = "/usr/bin/rsync",
            archive             = true,
            perms               = true,
            owner               = true,
            _extra              = {"-a"},
            update              = true,
            protect_args        = true,
            sparse              = true,
            temp_dir            = "/opt/jmitty_test_tmp",
            **rsh            = "/usr/bin/ssh -i /root/.ssh/rock_lsyncd",**
            compress            = true
        },
        ssh = {
            port                = 10022,
            **_extra              = {"-i /root/.ssh/rock_lsyncd"}**
        },
        host    = server,
        targetdir       = "/opt/jmitty_test"
    }
end

**Comment by axkibe** [comment]
I suppose you're issue is that you use space seperated arguments in _extra. There is no word / space parsing there, neither in Lsyncd nor in ssh. 

You likely need:
_extra = {"-i", "/root/.ssh/rock_lsyncd"}

**Comment by Demitrius** [comment]
Thanks, works!

**Comment by Tender-Liu** [comment]
lsyncd 可以不用指定私钥--我们可以使用别的方法
案例：
```bash
vim  /home/{user}/.ssh/config
host "xx.xx.xx.xx"
    HostName xx.xx.xx.xx
    User {user}
    Port 2222
    IdentityFile ~/.ssh/root.pem
```
```bash
vim /etc/lsyncd.conf

settings {
 
    logfile = "/var/log/lsyncd/lsyncd.log",
    pidfile = "/var/run/lsyncd.pid",
    statusFile = "/var/log/lsyncd/lsyncd.status",
    statusInterval = 5,
    nodaemon = false,
    maxProcesses = 1,
    maxDelays = 2,
    inist = ture,
    insist = 1,
}
 
 
sync {
    default.rsyncssh,
    source = "/opt/jenkins-script",
    host="xx.xx.xx.xx",
    targetdir = "/opt/jenkins-script",
    exclude = { 
        "logs/**" 
    },

    rsync = {
        binary = "/usr/bin/rsync",
        archive = true,
        compress = true,
        verbose = true,
        owner = true,
        perms = true,
        links = true,
        whole_file = false,
    }
 
}
```
我们利用登录别名，自定义私钥文件即可

**Comment by juangacovas** [comment]
You can use the IdentitiesOnly=yes option along with IdentityFile (see
ssh_config
man page <http://linux.die.net/man/5/ssh_config>)
