### ISSUE TITLE
Problem start lsyncd

### ISSUE THREAD

**Issue by marcelodelta** [axkibe/lsyncd#384]
$ lsyncd -rsyncssh -nodaemon . root@192.168.0.105 /var/www/html/Temp
Error: There cannot be command line syncs and config file together.

**Comment by axkibe** [comment]
Options must be first.
```
$ lsyncd -nodaemon -rsyncssh . root@192.168.0.105 /var/www/html/Temp
```

**Comment by marcelodelta** [comment]
Thanks axkibe.
Now the problem is another.

$ lsyncd -nodaemon -rsyncssh . root@192.168.0.105 /var/www/html/Temp

Warn: Using /dev/fsevents which is considered an OSX internal interface.
Warn: Functionality might break across OSX versions (This is for 10.5.X)
Warn: A hanging Lsyncd might cause Spotlight/Timemachine doing extra work.
Error: Cannot access /dev/fsevents monitor! (1:Operation not permitted)

**Comment by axkibe** [comment]
A this is OSX, currently I don't advice using Lsyncd on OSX, sorry, the interface is old and has bugs with exchange events.

Otherhwise Lysncd must currently be run on OSX to use this direct access.

**Comment by axkibe** [comment]
I suppose I can close this, sorry for the OSX backend being so lousy. It was once an experiment, that not got updated much.

**Comment by mikeschinkel** [comment]
@marcelodelta — 

I was able to resolve this issue, no problem.  **You just need to give macOS permission** _(at least on macOS 12.7.4 Monterey)._

1. In _"System Settings"_ select _"Security & Privacy"._
2. Then click the lock icon in the bottom-left corner and enter your administrator password to unlock the settings dialog.
3. Select the _"Privacy"_ tab.
4. Scroll down on the left-side panel and select _"Full Disk Access"_.
5. Click on the `[+]` button under the right-side panel.
6. Find `lsyncd`, select it, and click the `[Open]` button.
7. Click the lock icon in the bottom-left corner to re-lock the settings.
8. And finally close your _"System Settings"_ dialog.

HOWEVER, I immediately ran into this issue: [Error: unknown event(831) in fsevents}(https://github.com/lsyncd/lsyncd/issues/244).

<hr> 

@axkibe — 

From what it looks like you decided several years ago to stop supporting macOS.  

If that is still that case it would be really nice if you were to **update your `README` warning macOS users** not to spend time trying to get it working. I just spend half a day trying to get it working only to have all the work made moot by a show stopping bug.

OTOH if you have decided to revise support for macOS then here is my config I got working — other than `unknown event(831)` bug — in case it helps anyone else.

```lua
local homeDir = os.getenv("HOME")
local projectDir = homeDir .. "/Projects/my-project"
local lsyncdDir = projectDir .. "/lsyncd"
local sshKey = homeDir .. "/.ssh/mikeschinkel@my-server.local"

settings {
    logfile = lsyncdDir .. "/lsyncd.log",
    statusFile = lsyncdDir .. "/lsyncd.status",
    nodaemon   = false,
    inotifyMode = "CloseWrite or Modify",
    statusInterval = 30,
    maxProcesses = 1,
}

sync {
    default.rsyncssh,
    source = projectDir,
    host = "my-server.local",
    targetdir = "/path/to/target/dir/on/debian/linux/vm",
    delete = true,
    exclude = { "/sync.sh" },
    rsync = {
        binary = "/usr/local/bin/rsync",
        archive = true,
        compress = true,
        verbose = true,
        _extra = {
            "--rsync-path='/usr/local/bin/rsync.sh'",
            "--omit-dir-times",
            "--omit-link-times",
        },
    },
    ssh = {
        port = 22,
        identityFile = sshKey,
        options = {
            StrictHostKeyChecking = "no",
            User = "mikeschinkel",
        },
    },
}
```

**Comment by Zhenya-Barannik** [comment]
Same bug on Os X 12.5.1 (21G83). I am not using lsyncd it seems.
```sh
05:27:59 Normal: --- Startup ---
05:27:59 Normal: recursive full rsync: ... -> ...
05:28:00 Normal: Startup of ... -> ... finished.
05:28:01 Error: unknown event(831) in fsevents.
```
