### ISSUE TITLE
one source, two (or more) targerts?

### ISSUE THREAD

**Issue by mdiehn** [axkibe/lsyncd#388]
Hello Axel,

I'm sure you've told us this before, but I can't figure out the right search terms to unveil that telling. :-)

So, can we do this? One source to multiple targets? I want to sync changes from my app server to it's  HA partner on the LAN and it's DR server across the ocean.

Thanks,
Mike

**Comment by axkibe** [comment]
Sure, just duplicate the sync statement with different targets.

You can even make a loop

```
targets = {
 'target1.myplace.com:/targetdir', 
 'target2.myplace.com:/targetdir'
}

for _, target in ipairs(targets) do
  sync{ default.rsync,
    source="/sourcedir",
    target=target
  }
end
```

**Comment by mdiehn** [comment]
I assumed that if I did

```
sync{ default.rsync, source='/sourcedir', target='target1:/var/dir' }
sync{ default.rsync, source='/sourcedir', target='target2:/var/dir' }

```
that would .... wait. Doh!!! Of *course* there would only be one set of inode watches, 'cause you aren't stupid, and yes there would have to be different rsync processes for each target.

OK, thanks for doing that bit of thinking for me.

**Comment by axkibe** [comment]
Yes, there is explcitly code that stops from duplicate inode watches to be creates, also if one source is the subdirectory of the other.
 sync{ default.rsync, source='/sourcedir', target='target1:/var/dir' }
 sync{ default.rsync, source='/sourcedir/onlythis', target='target2:/var/dir' }

I reopen the issue tough as an improvement to the manual, that question appeared a few times.

**Comment by axkibe** [comment]
Done.

http://axkibe.github.io/lsyncd/faq/multiple-targets/
