### ISSUE TITLE
Sync with git repository

### ISSUE THREAD

**Issue by cristian-marin-hs** [axkibe/lsyncd#389]
Hello,

I'm trying to use lsyncd to sync a repository from local computer to a remote host over ssh.

All is good, the files are syncing, but when I do a 'git checkout' to switch the branch locally I'm encountering an issue. The new source files are copied to the remote host, but the branch still remains the old one, when I do 'git branch'.

After I restart the lsyncd process (note: I'm using osx on the local host), the branch gets updated on the remote host. Looking at the logs from the rsync after lsyncd restart, I noticed this:

```
Fri Jun 24 18:15:27 2016 Normal: recursive startup rsync: /path/to/source/ -> remote_hostname:/mnt/remotesync/ 
sending incremental file list
repo/.git/HEAD
repo/.git/config
repo/.git/logs/HEAD
repo/.git/logs/refs/heads/
repo/.git/logs/refs/heads/new_branch
repo/.git/refs/heads/
repo/.git/refs/heads/new_branch
repo/some_modified_folder/
repo/another_modified_folder/
etc..
sent 132,200 bytes  received 2,823 bytes  20,772.77 bytes/sec
total size is 127,663,293  speedup is 945.49
Fri Jun 24 18:15:33 2016 Normal: Startup of "/path/to/source/" finished: 0
```

Does it have something to do with modified time on those files and dirs? If yes, how can I fix this? Or somehow, it gets stuck on those updates until I kill lsyncd and start it again.

The config file looks like this:

```
settings {
    logfile = "/path/to/lsyncd.log",
    statusFile = "/path/to/lsyncd.status",
}
sync {
    default.rsyncssh,
    source = "/path/to/source/",
    host = "remote_hostname",
    targetdir = "/mnt/remotesync",
    rsync = { 
        binary = "/usr/local/bin/rsync",
        archive = true,
        links = true,
        perms = true,
        executability = true,
        verbose = true
    }
}
```

I tried with some other options for the sync {} setting, such as whole_file, ignore_times, checksum, but was no luck.

Thank you,
Cristi.

**Comment by axkibe** [comment]
Hmm, maybe first try default.rsync instead of default.rsyncssh, to see if its an issue there.

**Comment by cristian-marin-hs** [comment]
Thank for the reply.
I tried today with default.rsync and it's still the same :(. Is there a way that I can look deeper into this, so I can understand what is going on at a lower level?

**Comment by axkibe** [comment]
You can start Lsyncd with "-log Exec" then it will log exactly how its calling rsync. Otherwise I don't know fom the informations provided.

Logs from when Lsyncd gets "stuck" would be very helpful.

**Comment by c-m** [comment]
Hi,
I used "-log Exec", but I didn't see any unusual stuff going on. The only valuable info was how rsync is called:
```
Exec: /usr/local/bin/rsync [--delete] [--ignore-errors] [-lptgcsovD] [-r] [source] [destination]
```
Running this `rsync` command by hand after switcing branches in git, all the files are updated at once (including `.git/HEAD`, `.git/log/HEAD`, etc.). What can possibly go wrong at the `lsyncd` level? I saw that it works with fsevents for event monitoring, so the problem might come from here?

Thanks!

**Comment by axkibe** [comment]
A yes, it might be the "exchange" event that Lsyncd's fsevents code isn't able to recognize. OSX has a special command/event for two files swapping place, possible git uses this.

In this case, sorry Lsyncd won't work properly on OSX until it's fsevent code is completely rewritten to use the FsEvents daemon instead of /dev/fsevents directly.

**Comment by cristian-marin-hs** [comment]
I just used a tool - https://github.com/rianhunter/gfslogger that prints all the fsevents logs and I didn't find the EXCHANGE event, although this might have been possible, since git puts a .lock on some files to avoid concurrency. 
What I did see were actually some events happening during these locks. For example, on .git/HEAD file, that contains the path of the current branch (`.git/ref/head/branch_name`):

```
# Event
  type           = CREATE FILE
  pid            = 71848 (}ÿ)
  # Details
    # type       len  data
    STRING        63  string = /Users/cristian-marin/dev_tryouts/source/nagios/.git/HEAD.lock
    DEV            4  dev    = 0x1000004 (major 1, minor 4)
    INODE          4  ino    = 18541840
    MODE           4  mode   = -rw-r--r-- (0x0081a4, vnode type VREG)
    UID            4  uid    = 502 (cristian-marin)
    GID            4  gid    = 20 (staff)
    INT64          8  int64  = 481382471033322
    DONE (0xb33f)
# Event
  type           = CONTENT MODIFIED
  pid            = 71848 (}ÿ)
  # Details
    # type       len  data
    STRING        63  string = /Users/cristian-marin/dev_tryouts/source/nagios/.git/logs/HEAD
    DEV            4  dev    = 0x1000004 (major 1, minor 4)
    INODE          4  ino    = 18539990
    MODE           4  mode   = -rw-r--r-- (0x0081a4, vnode type VREG)
    UID            4  uid    = 502 (cristian-marin)
    GID            4  gid    = 20 (staff)
    INT64          8  int64  = 481382472242322
    DONE (0xb33f)
# Event
  type           = CONTENT MODIFIED
  pid            = 71848 (}ÿ)
  # Details
    # type       len  data
    STRING        63  string = /Users/cristian-marin/dev_tryouts/source/nagios/.git/HEAD.lock
    DEV            4  dev    = 0x1000004 (major 1, minor 4)
    INODE          4  ino    = 18541840
    MODE           4  mode   = -rw-r--r-- (0x0081a4, vnode type VREG)
    UID            4  uid    = 502 (cristian-marin)
    GID            4  gid    = 20 (staff)
    INT64          8  int64  = 481382472318183
    DONE (0xb33f)
# Event
  type           = RENAME
  pid            = 71848 (}ÿ)
  # Details
    # type       len  data
    STRING        63  string = /Users/cristian-marin/dev_tryouts/source/nagios/.git/HEAD.lock
    DEV            4  dev    = 0x1000004 (major 1, minor 4)
    INODE          4  ino    = 18541840
    MODE           4  mode   = -rw-r--r-- (0x0081a4, vnode type VREG)
    UID            4  uid    = 502 (cristian-marin)
    GID            4  gid    = 20 (staff)
    STRING        58  string = /Users/cristian-marin/dev_tryouts/source/nagios/.git/HEAD
    DEV            4  dev    = 0x1000004 (major 1, minor 4)
    INODE          4  ino    = 18541720
    MODE           4  mode   = -rw-r--r-- (0x0081a4, vnode type VREG)
    UID            4  uid    = 502 (cristian-marin)
    GID            4  gid    = 20 (staff)
    INT64          8  int64  = 481382472391771
    DONE (0xb33f)
```

**Comment by cristian-marin-hs** [comment]
@axkibe is there reason for the behaving regarding the above output?
I'll try compiling this project with debug flags and see if I'll find something relevant during my workflow

**Comment by axkibe** [comment]
There isn't more output with recompiling, you can specify "-log all" on call for maximum logging.

**Comment by axkibe** [comment]
Duplicate if #204
