### ISSUE TITLE
Lsyncd Error :There can only be one config file in command line.

### ISSUE THREAD

**Issue by sudeepmk** [axkibe/lsyncd#391]
Hello everyone,
I am pretty new to Linux bash. I am trying to mirror two folders using lsyncd command. Here are the steps I followed.

1 - Install the lsyncd package
2- Run the following code: 
Sudo lsyncd /home/dxterity1/NGSNAS1/Screen Shots /home/dxterity1/DataStore/Screenshots

I am getting an error : There can only be one config file in command line.

I would really appreciate if anyone can show me some insight.

Thanks

**Comment by astatham** [comment]
try
    sudo lsyncd -rsync /home/dxterity1/NGSNAS1/Screen Shots /home/dxterity1/DataStore/Screenshots

**Comment by axkibe** [comment]
As astaham said.
