### ISSUE TITLE
Simultaneous replicate files with multiple targets

### ISSUE THREAD

**Issue by Ara4Sh** [axkibe/lsyncd#394]
Hello 

Im using Lsyncd to sync my /var/www between 3 hosts.
lsyncd first sync 1 server and then go to another  
can I use lsyncd to simultaneous syncing between 3 hosts ? 

```
settings {
        delay   = 1,
        maxProcesses = 3,
        logfile = "/var/log/lsyncd.log",
        statusFile = "/tmp/lsyncd.stat",
        statusInterval = 1

}
sync {
    default.rsync,
    source = "/var/www",
    target = "server1:/var/www",
    rsync    = {
        archive  = true,
        compress = true,
        perms    = true,
        owner    = true,
        update   = true,
        whole_file = true
   }
}
sync {
    default.rsync,
    source = "/var/www",
    target = "server2:/var/www",
    rsync    = {
        archive  = true,
        compress = true,
        perms    = true,
        owner    = true,
        update   = true,
        whole_file = true
   }
}
sync {
    default.rsync,
    source = "/var/www",
    target = "server3:/var/www",
    rsync    = {
        archive  = true,
        compress = true,
        perms    = true,
        owner    = true,
        update   = true,
        whole_file = true
   }
}

thanks
```

**Comment by axkibe** [comment]
Yes.

You can also use a loop in the config file to avoid copy/pasting stuff:
```
servers = { 'server1', 'server2', server3' }
for _, server in ipairs( servers ) do
  sync {
    default.rsync,
    source = "/var/www",
    target = server .. ":/var/www",
    rsync    = {
        archive  = true,
        compress = true,
        perms    = true,
        owner    = true,
        update   = true,
        whole_file = true
     }
  }
end
```

**Comment by Episodio1** [comment]
Hi, axkibe.
Will that code run 3 rsync simultaneosly or one process after the other?

**Comment by axkibe** [comment]
If you set global maxProcesses high enough, yes.

**Comment by Episodio1** [comment]
Thanks axkibe.
I've got several doubts but I have put them over a diagram so you better understand know my simple architecture with 2 storages (each storage should keep the same files).
In my system there won't be any file modifications or removals, it will just be a simple file copy ("rsync -a") because files and folders will be static (we don't have to deal with synching problems).

![lsyncsolution1](https://cloud.githubusercontent.com/assets/4375891/17969480/23c77f28-6aca-11e6-9d80-f50bf81fe076.gif)

What do you think?

**Comment by axkibe** [comment]
I don't know why you mean by lsyncd processes, you should run one Lsyncd dameon on the source host, with two sync{} commands, so they are only using the watches once as they share them.

1) Should not, albeit Lsyncd has a global and a per sync{} command maxProcess count, if global is less than the per sync{}, one of the targets may wait on the process of the other finish. However if you set maxProcess for each sync to 1 and the global to 2 they will not affect each other. Lsyncd keeps seperate lists for each target.

2) Yes. Lsyncd will keep trying to rerun rsync for ever on any error that is a network on it's base (e.g. target host unreachable)

3) I don't understand the question? But maybe the Lsyncd status file is what you need, in this Lsyncd will write what it is currently trying to transfer, what is stacked etc.

**Comment by Episodio1** [comment]
> "I don't know why you mean by lsyncd processes,"

Yes, sorry. I meant the 2 rsync transfer processes.

> 3) I don't understand the question? 

As I am deleting files after a while, I want to exclude the files that weren't transferred, so I don't delete them until they are copied succesfully to both storages. :)
Hmmm, ok, I'll read status file then.

Thank you!

**Comment by axkibe** [comment]
When you delete the file and it hasn't been transfered yet, Lsyncd will only remember the delete and try to execute it (as it doesn't know for sure if it has been partially transfered after all).

**Comment by Episodio1** [comment]
I have lsyncd configured with update = false.
I just copy files, same behaviour as " rsync -a ").

**Comment by Episodio1** [comment]
Delete = false ;)

**Comment by axkibe** [comment]
I suppose this is solved?

**Comment by Episodio1** [comment]
I am not who opened this thread, but my question is answered. :)

**Comment by tisc0** [comment]
Hi all,
I'm trying to use the amazing lsyncd to sync a few files in a directory on multiple target.
Let's just say /etc/php.ini to sync it on a cluster.
But it doesn't work exactly well : my file is synced at every restart or lsyncd, but in between, and even if it's triggered, the process exit with code 23 on each node (log file says), and my /etc/php.ini is not updated on the target (until I restart lsyncd daemon).
Here is what I did :

settings {
   logfile      = "/var/log/lsyncd.log",
   statusFile   = "/var/run/lsyncd.status",
   pidfile      = "/var/run/lsyncd.pid",
   insist       = 1
}

myNodes1 = {
        "node1",
        "node2",
        "node3",
}
myNodes2 = {
        "node1",
        "node2",
}

for _, server in ipairs(myNodes1) do
        sync {
            default.rsync,
            source    = "/etc",
            target    = server .. ":/etc",
            delay     = 3,
            exclude = { '*.swp', '*.swx' },
            rsync     = {
                 binary   = "/usr/bin/rsync",
                archive  = true,
                compress = true,
                _extra = { "--files-from=/etc/lsyncd/etc.list" }
            }
        }
end

My /etc/lsyncd/etc.list :
/php.ini

Wondering what I do wrong.
Thanks in advance for any advice !

**Comment by axkibe** [comment]
You must not use "--files-from" in _extra.

**Comment by tisc0** [comment]
OK... but what's the way to achieve what I want then ? 
All the point of syncing only specific files seemed to rely on that option.

**Comment by tisc0** [comment]
```
for _, server in ipairs(myNodes3) do
        sync {
            default.rsync,
            source    = "/etc",
            target    = server .. ":/etc",
            delay     = 3,
            --exclude = { '*.swp', '*.swx' },
            rsync     = {
                binary   = "/usr/bin/rsync",
                archive  = true,
                compress = true,
               _extra = {
                        "--include=php.ini",
                        "--exclude=*"
                }
            }
        }
end
```

Did it that way, and it works. [Thks Marc Rouleau for the tip](http://unix.stackexchange.com/questions/207730/lsyncd-is-it-possible-to-sync-individual-files-from-a-list).
Is that still shocking  ?
Would still be interesting to have a way to use a single file list of inclusion.

**Comment by xrchz** [comment]
It's so common for people to want to sync a single file, or a specific list of files. It's strange for `lsyncd` to be so opposed to supporting this functionality.

**Comment by axkibe** [comment]
I'm not opposed to it, it simply hasn't been done. I don't think, that watches on files would be the way to go, but still marking said the directory and having "include" filter lists to only include the files wanted. Lsyncd currently supports only exclude filters. However adding inclusion filters makes things a tad more complicated, since having only exclusion, the order of applying filter rules doesn't matter, with exclusions and inclusions it does.

What I'm opposed to is using _extra with paramaters Lsyncd uses itself to communicate with rsync especially -files-from. In hindsight I think it was a bad idea to add "_extra" as general purpose workaround, for people knowning exactly what they are doing, at all, since said people could patch Lsyncd anyway...

**Comment by codingforpleasure** [comment]
I'm using the latest version: 2.2.3,
and I have been trying to sync between to local folders (selective copy - not all files),
so I have took 3 simple approaches,
unfortunately neither of them work:

```
sync {
    default.direct,
    source  = homeDir ,
    target  = destDir ,
     rsync = { _extra = {
                          "--files-from=" .. homeDir .. "/.config/lsyncd/files.list",
                         }
            }
}
```

or 

```
sync {
    default.direct,
    source  = homeDir ,
    target  = destDir ,
    rsync = { _extra = { "--include=.zshrc", "--exclude=*" } }
}
```
or 
 
```
sync {
    default.direct,
    source  = "/src-try",
    target  = "/dst-try",
    --rsync = { _extra = { "--include=a.txt", "--exclude=*" } ,
    rsync = { _extra = {
                          "--include=.zshrc",
                          "--include=.tmux.conf",
                          "--include=.vimrc",
		          "--exclude=.*",
     	                  "--exclude=*",
	                    }
            }
}

```
All 3 fails, I have noticed if some files gets updated in the src folder all modified files would get copied to dst folder although they not appear in the include statement ... bummer :/
How can I accomplish this?? any suggestion, please.

**Comment by axkibe** [comment]
don't use _extra, 2.2.3 has the "filter" feature.

**Comment by codingforpleasure** [comment]
Ohh wow, thank you @axkibe.  great job!!! 
Exactly what i needed, ran the unit test filter-rsync.lua looks promising (much better than writing inlet).

Kudos for the efforts developing lsyncd! :1st_place_medal:

**Comment by marcelin** [comment]
Please need help to exclude files
