### ISSUE TITLE
Call a script only when whole rsync process is complete

### ISSUE THREAD

**Issue by paul-norman** [axkibe/lsyncd#395]
Hi,

I don't see a way to trigger a shell script only when the **whole** rsync process has completed. I don't need to know the details of each modified file or anything like that, just have a shell script be triggered if **anything** has been modified after the sync (but **not** if nothing is changed). I see the lpostcmd [example](https://github.com/axkibe/lsyncd/blob/master/examples/lpostcmd.lua) could possibly do this if the maxProcesses is limited to 1 (far from ideal), but I don't seem to be able to get a slightly simplified (local) version of this script to actually trigger the shell script:

``` lua
local rsync_local_post_commit = {

    default.rsync,

    checkgauge = {
        default.rsync.checkgauge,
        target = true,
        postcmd = true,
    },

    maxProcesses = 1,

    action = function(inlet)
        local event = inlet.getEvent()
        local config = inlet.getConfig()

        if event.etype == "Blanket" then
            local isPostcmd = rawget(event, "isPostcmd")

            if isPostcmd then
                spawn(event, config.postcmd)
                return
            else
                return default.rsync.action(inlet)
            end
        end

        local sync = inlet.createBlanketEvent()
        sync.isPostcmd = true

        return default.rsync.action(inlet)
    end,

    collect = function(agent, exitcode)
        local isPostcmd = rawget(agent, "isPostcmd")

        if not agent.isList and agent.etype == "Blanket" and isPostcmd then
            if exitcode == 255 then
                return "again"
            end
            return
        else
            return default.collect(agent, exitcode)
        end
    end,

    prepare = function(config, level, skipTarget)
        return default.rsync.prepare(config, level, skipTarget)
    end
}

sync {
    rsync_local_post_commit,
    source = "/local-source", 
    target = "/local-target", 
    delay = 5, 
    rsync = {
        archive = true, 
    },
    postcmd = "/path/to/lsyncd-post-commit.sh",
}
```

Have I just made a simple error? The shell script is executable and runs fine manually.

Additionally, the folders in question have quite a few files in them (20k+) and it's possible all could change at once, so presumably limiting the maxProcesses would be a bad thing here. Assuming my config above can be fixed to trigger the shell script, is the best thing to do to use something like this without the maxProcesses limit, but have its shell script just modify the timestamp on a single file in a separate directory (a lot) and then use a second (extremely similar) Lsyncd process to monitor the directory containing that single file and then run the actual post-commit shell script from that Lsyncd process only if that file changes? This seems very convoluted, is it necessary?

Thanks for taking the time to read this!

Cheers,

Paul

_As an aside, wouldn't an extension to Lsyncd that trivialised this case be extremely helpful in general? Ideally it's be something like:_

``` lua
sync {
    default.rsync, 
    source = "/local-source", 
    target = "/local-target", 
    delay = 5, 
    rsync = {
        archive = true, 
    },
    onProcessFinish = "/path/to/lsyncd-post-commit.sh",
}
```

**Comment by paul-norman** [comment]
For anyone wanting the same thing, the spawn line should simply read:

```lua
spawnShell(event, config.postcmd)
```

To make this work. However, using this script raises another issue, the process randomly crashes simply writing the same two lines over and over many times a second to the log:

```
Mon Sep 12 11:22:56 2016 Normal: Finished a list after exitcode: 0
Mon Sep 12 11:22:56 2016 Normal: Calling rsync with filter-list of new/modified files/dirs

Mon Sep 12 11:22:56 2016 Normal: Finished a list after exitcode: 0
Mon Sep 12 11:22:56 2016 Normal: Calling rsync with filter-list of new/modified files/dirs

Mon Sep 12 11:22:56 2016 Normal: Finished a list after exitcode: 0
Mon Sep 12 11:22:56 2016 Normal: Calling rsync with filter-list of new/modified files/dirs

Mon Sep 12 11:22:56 2016 Normal: Finished a list after exitcode: 0
Mon Sep 12 11:22:56 2016 Normal: Calling rsync with filter-list of new/modified files/dirs

Mon Sep 12 11:22:56 2016 Normal: Finished a list after exitcode: 0
Mon Sep 12 11:22:56 2016 Normal: Calling rsync with filter-list of new/modified files/dirs
```

Which means that files are no longer kept in sync. I have put a cron in place to restart Lsyncd regularly which bandages this issue, but it is a real problem. What is causing this please?

**Comment by axkibe** [comment]
Why don't you simply replace rsync by a bash script that does the rsync and then does whatever you want to do.

```
#!/bin/bash
"/usr/bin/rsync $@"
result=$?
(
  if [ $result -eq 0 ]; then
     echo "my commands";
  fi
) >/dev/null 2>/dev/null </dev/null

exit $result
```

Just be careful you do not alter the return value or the in/out/err streams Lsyncd uses to communicate with rsync.

**Comment by paul-norman** [comment]
Thanks for the quick reply, Axel. It's really appreciated! That definitely does seem like an idea worth trying. How exactly do I instruct Lsyncd to do this? I'm looking at the examples and the docs, but it's not at all clear to me (I'm a PHP developer and this is all pretty alien)! 

I just modified one of the examples in a very small way to achieve the above, but there doesn't seem to be anything similar to this case... 

As an aside, for my local (actually Amazon EFS) scenario, I thought that rsync was overkill and initially tried the default.direct config, but it only seemed to update the target for newly created files (not files with just a new timestamp or permission change). Moving to the rsync driver worked perfectly. Is this the expected behaviour?

**Comment by axkibe** [comment]
Thats likely that the default.direct doesn't update timestamps and/or permissions.

I'd have to check the examples like the postcmd from above, to be honest, the examples are badly maintained.

You can change the binary Lsyncd calls for example with
rsync = {
  binary = '/usr/local/bin/my-rsync-wrapper',
}

**Comment by paul-norman** [comment]
That's great (and very simple!). Just to be 100% clear, my lsyncd.conf file can become something like:

```lua
settings {
    logfile = "/var/log/lsyncd/lsyncd.log",
    statusFile = "/var/log/lsyncd/lsyncd.status",
}
sync {
    default.rsync, 
    source = "/local-source", 
    target = "/local-target", 
    delay = 5, 
    rsync = {
        binary = "/path/to/bash/handler.sh", 
        archive = true, 
    },
    exclude = { "/relative/folder/to/exclude" },
}
```

And then the handler.sh can be something like:

```shell
#!/bin/bash
/usr/bin/rsync "$@"
result=$?
(
  if [ $result -eq 0 ]; then
     source /path/to/lsyncd-post-commit.sh;
  fi
) >/dev/null 2>/dev/null </dev/null

exit $result
```
Fingers crossed this operates with fewer crashes! (I'll give it a try and let you know later today)

**Comment by paul-norman** [comment]
Just to report back, this method seems to work perfectly with no crashes at all. Thanks again!

**Comment by axkibe** [comment]
Great I'll include it in the FAQ or Examples section of the manual.

**Comment by axkibe** [comment]
Done.

http://axkibe.github.io/lsyncd/faq/postscript/
