### ISSUE TITLE
rsyncssh identity flag not working

### ISSUE THREAD

**Issue by mengesb** [axkibe/lsyncd#396]
I tried the following configuration and was unable to get the configuration to identify with the identity file:

```
sync {default.rsyncssh,source="/var/www/cobbler",host="lsyncd@s03.np.a.anaplan.com",targetdir="/mnt/amznefs/cobbler/repo_mirror",rsync={archive=true,compress=false,whole_file=false},ssh={identityFile="/home/lsyncd/.ssh/lsyncd-909ee35eb26f2dd64148a15ad579cc42b83bc30b"}}
```

The documentation doesn't specify that it is a flag available for `ssh` however when I parsed through the code, this appeared to be a valid flag.

Could I get some clarification on this?

**Comment by rlabrecque** [comment]
I ran into this as well. It was because I was on 2.1.5 from ubuntus package repo.

This is only available in 2.1.6. Unfortunately compiling this with the limited documentation is insanely difficult. It doesn't even list the version of Lua that it requires.

**Comment by axkibe** [comment]
It works for any lua Version 5.1 and after.

5.2 and 5.3 need to have the compatiblity flag turned on which would be a smart thing for distros to do. Ubuntu obviously has.

I'll update the documentation with this

**Comment by axkibe** [comment]
Fixed the manual to include the ssh.identifyFile and ssh.options parameter.
And added requirements to the "building" page.
