### ISSUE TITLE
wrong pid in pid-file

### ISSUE THREAD

**Issue by axkibe** [axkibe/lsyncd#40]
Originally filed by wolfgang...@gmx.at on 2011-01-10T22:34:10

In the new release 2.0.0 the option --pidfile writes the wrong pid into the pid file: 

As the function write_pidfile() is called before daemonize(), the pid of the first process is written, not the pid of the daemon. So start scripts which check that number do not work right.

**Comment by stanislav-zaprudskiy** [comment]
@axkibe was that really fixed? I'm observing the wrong PID problem with version `2.2.1`. For instance, pidfile says 21198, while `ps` shows 21199 for the running daemon.

https://github.com/axkibe/lsyncd/blob/d444ccb2d2ac155c93b659bba7a96f5be0991ddf/lsyncd.c#L1615-L1625

**Comment by axkibe** [comment]
Seems like it was not fixed, dunno what I thought/said on 2011.

Fixed it now in git HEAD.

Thx for noticing.

**Comment by axkibe** [comment]
I remember now what happened, back then it was fixed, but later I changed it back due to another complaint about lsyncd silently dying when the pid file couldn't be written.

Well in this version, the pid file is tried to be written after fork() so the pid matches, but before stdin/stdout detachment, so the complaint should be visible if it cannot be written.
