### ISSUE TITLE
lsyncd -direct doesn't preserve mode and ownership

### ISSUE THREAD

**Issue by tylercubell** [axkibe/lsyncd#400]
`lsyncd -direct /foo /bar` doesn't preserve mode and ownership. 

Is there a way to make a true 1-to-1 copy that preserves all original attributes?

**Comment by axkibe** [comment]
Just use default.rsync for local syncing.

**Comment by tylercubell** [comment]
When I read "Default.direct can be used to keep two local directories in sync with better performance than using default.rsync." on [Lsyncd - Config Layer 4](http://axkibe.github.io/lsyncd/manual/config/layer4/), I was thinking `direct` might make more sense in this situation. Oh well...

I tried `default.rsync` like you suggested and while I was able to solve the mode and ownership problem, it doesn't seem to keep files in sync after the initial sync. Am I missing something?

```lua
sync {
    default.rsync,
    source    = "/foo",
    target    = "/bar",
    rsync     = {
        archive  = true
    }
}
```

**Comment by axkibe** [comment]
is /foo a networked drive?

**Comment by tylercubell** [comment]
Yes.

**Comment by axkibe** [comment]
Then it won't work, because Lsyncd doesn't receive file system notificiations from the kernel. This is an issue with network filesystems which do not support this.

Lsyncd has to be running where the files are local
