### ISSUE TITLE
lsyncd-2.1.5 rsyncssh ignores ssh _extra

### ISSUE THREAD

**Issue by davidfavor** [axkibe/lsyncd#402]
Request to know correct way to specify an ssh key file. Thanks.

Running in debug mode, no _extra contents added to exec, so password prompt issued.

---

Debug command...

lsyncd -nodaemon -log Exec /etc/lsyncd/lsyncd.conf.lua
16:47:06 Normal: recursive startup rsync: /scratch/net8.bizcooker.com/lxc/ -> net11.bizcooker.com:/scratch/net8.bizcooker.com/lxc/./ excluding
_wp-debug.log_
16:47:06 Exec: /usr/bin/rsync [<] [_wp-debug.log_] [--exclude-from=-] [--delete] [--ignore-errors] [-gpsoltD] [--temp-dir=/tmp/] [--rsh=ssh -p 22] [-r] [/scratch/net8.bizcooker.com/lxc/] [net11.bizcooker.com:/scratch/net8.bizcooker.com/lxc/./]
16:47:06 Exec: one-sweeped pipe
root@net11.bizcooker.com's password: 

---

Config file...

-- debug: lsyncd -nodaemon -log Exec /etc/lsyncd/lsyncd.conf.lua

settings {
  logfile        = "/var/log/lsyncd/lsyncd.log",
  statusFile     = "/var/log/lsyncd/lsyncd.status",
  statusInterval = 20,
  maxDelays      = 10,
  maxProcesses   = 4,
  insist         = true,
}

sync {

  default.rsyncssh,

  source      = "/scratch/net8.bizcooker.com/lxc/.",
  host        = "net11.bizcooker.com",
  targetdir   = "/scratch/net8.bizcooker.com/lxc/.",

  excludeFrom = "/etc/lsyncd/lsyncd.excludes",

  rsync = {
     archive    = true,
     compress   = false,
     whole_file = false,
     temp_dir   = "/tmp/"
  },

  ssh = {
    port   = 22,
    _extra = {
      "-l", "root",
      "-i", "/root/.ssh/backups.rsa",
      "-o", "StrictHostKeyChecking=no"
     }
  }

}

**Comment by axkibe** [comment]
You have to specifiy the _extra stuff to rsync as well to pass to it's ssh usage

Lsyncd should do this automatically for the options it recognizes, but not for the _extra workaround

**Comment by dreibh** [comment]
Adding the ssh _extra paramters to the rsync block just causes rsync to complain about the unknown (SSH) parameters. The only possibility to specify additional SSH parameters seem to be to use "default.rsync" instead of "default.rsyncssh", and then add an "rsh" entry with the right call of ssh. But I had to success in getting additional SSH parameters applied with "default.rsyncssh".

**Comment by dreibh** [comment]
This configuration is working for me:

settings {
   logfile        = "/var/log/lsyncd.log",
   statusFile     = "/var/log/lsyncd.status",
   insist         = true,
   log            = "scarce",
   statusInterval = 60
}

sync {
   default.rsync,
   source    = "/monroe/results/data/",
   target    = "<USER>@<SERVER>:<PATH>/,
   delete    = false,
   exclude   = { "/*.dat", "/*.sdat", "/.*" },
   maxDelays = 15,
   rsync = {
      archive  = true,
      compress = true,
      rsh      = "/usr/bin/ssh -p22 -i/etc/lsyncd/id_lsyncd.pub -oVerifyHostKeyDNS=yes -oStrictHostKeyChecking=no -oPasswordAuthentication=no",
      _extra   = { "--remove-source-files" }
   }
}

**Comment by dreibh** [comment]
This configuration is working for me:
`settings {
   logfile        = "/var/log/lsyncd.log",
   statusFile     = "/var/log/lsyncd.status",
   insist         = true,
   log            = "scarce",
   statusInterval = 60
}

sync {
   default.rsync,
   source    = "/monroe/results/data/",
   target    = "USER@HOST:PATH/",
   delete    = false,
   exclude   = { "/*.dat", "/*.sdat", "/.*" },
   maxDelays = 15,
   rsync = {
      archive  = true,
      compress = true,
      rsh      = "/usr/bin/ssh -p22 -i/etc/lsyncd/id_lsyncd.pub -oVerifyHostKeyDNS=yes -oStrictHostKeyChecking=no -oPasswordAuthentication=no",
      _extra   = { "--remove-source-files" }
   }
}
 ```

**Comment by jahmoh82** [comment]
I'm having the same issue:
it does duplicate files and folder to remote but its shows user and group as 1002

I'm using version 2.2.2 of Lsyncd

here is my setting:
```
settings {
	logfile = "/var/log/lsyncd/lsyncd.log",
        statusFile = "/var/log/lsyncd/lsyncd.status"
}

sync {
      	default.rsyncssh,
        source="/home",
        host="157.**.174.**",
        targetdir="/home/",
        delete = "running", -- prevents deletion of files on startup (ie when a server comes back online, don't delete files that are $
        delay = 5, -- run every 5 seconds instead of default 20
        exclude = {
                "/home/backup",
        },
	rsync = {
                archive = true, -- use the archive flag in rsync
                perms = true, -- Keep the permissions
                owner = true, -- Keep the owner
                compress = true,
                acls = true,
                xattrs = true,
                _extra = {"-a"}, -- Sometimes permissions and owners isn't copied correctly so the _extra can be used for any flag in $
        },
	delay = 5
}
```
