### ISSUE TITLE
Preserving owner:group from source to target?

### ISSUE THREAD

**Issue by arctwelve** [axkibe/lsyncd#403]
I have two servers: source-server and target-server. I want use lsyncd to sync files in a directory on source-server to another directory on target-server.

In my ssh daemon, on both servers, I have root logins disabled (`PermitRootLogin no`) so I can't use the root user to run lsyncd over ssh.

I created a user 'syncer' on both servers that has a key-pair allowing password-less ssh logins from source-server to target-server. So this works without a password prompt:

`[syncer@source-server]$ ssh syncer@target-server`

My lsyncd.conf looks like this:

```
settings = {
    logfile = "/var/log/lsyncd.log",
    statusFile = "/var/log/lsyncd.stat",
    statusInterval = 2
}


sync {
    default.rsync,
    source="/var/www/html/",
    target="target.server.ip:/backup/",
    rsync = {
        rsh ="/usr/bin/ssh -l syncer -i /home/syncer/.ssh/id_rsa",
        compress = true,
        acls = true,
        xattrs = true,
        archive = true
    }
}
```

And it works except the owner of replicated files on the target server is always 'syncer'. The permissions of the source are respected and replicated correctly on the target. I just can't figure out a way to preserve the owner (and group) of the replicated files. (i.e., if the file on source is owned by 'deknuth', I would like the file on target to also be owned by 'deknuth' -- not 'syncer').

TIA

**Comment by axkibe** [comment]
This is something only root can do.

Or you can hack around the user the CAP_CHOWN permission.

http://unix.stackexchange.com/questions/318625/how-to-grant-a-user-rights-to-change-ownership-of-files-directories-in-a-directo

However note, a user who has CAP_CHOWN can make himself root anyway. 

Anyway, this is nothing Lsyncd, its general unix.

**Comment by jahmoh82** [comment]
I'm having the same issue:
it does duplicate files and folder to remote but its shows user and group as 1002

I'm using version 2.2.2 of Lsyncd

here is my setting:
```
settings {
	logfile = "/var/log/lsyncd/lsyncd.log",
        statusFile = "/var/log/lsyncd/lsyncd.status"
}

sync {
      	default.rsyncssh,
        source="/home",
        host="157.**.174.**",
        targetdir="/home/",
        delete = "running", -- prevents deletion of files on startup (ie when a server comes back online, don't delete files that are $
        delay = 5, -- run every 5 seconds instead of default 20
        exclude = {
                "/home/backup",
        },
	rsync = {
                archive = true, -- use the archive flag in rsync
                perms = true, -- Keep the permissions
                owner = true, -- Keep the owner
                compress = true,
                acls = true,
                xattrs = true,
                _extra = {"-a"}, -- Sometimes permissions and owners isn't copied correctly so the _extra can be used for any flag in $
        },
	delay = 5
}
```

**Comment by axkibe** [comment]
Dude, stop spamming my bug tracker and please cleanup the mess you did, report it _once_,. Thank you
