### ISSUE TITLE
delete = "running" not working

### ISSUE THREAD

**Issue by Kyoshiro-san** [axkibe/lsyncd#407]
Neither delete = false nor delete = running work with my setup.
I'm using rsyncssh.

> $ cat /etc/lsyncd/lsyncd.conf.lua 
> settings {
>   insist = true,
>   delay = 2,
>   statusFile = "/var/run/lsyncd.stat",
>   statusInterval = 1,
>   delete = "running",
> 
> }
> 
> dofile("/etc/lsyncd/dodir.lua")
> dodir("/etc/lsyncd/sync.d")

> $ cat /etc/lsyncd/sync.d/store_replication.conf.lua 
> sync {
>   default.rsyncssh,
>   source = "/var/www/storage/files",
>   targetdir = "/var/www/storage/files",
>   host = "xxxxx",
>   rsync = {
>           verbose = true,
>           update = true,
>           whole_file = true,
>           rsh = 'ssh -l storage -i /var/www/storage/.ssh/id_rsa -o StrictHostKeyChecking=no',
>           temp_dir = '/var/www/storage/tmp',
>     
>   },
>   ssh = {
>           _extra = { '-l', 'storage', '-o', 'StrictHostKeyChecking=no', '-i', '/var/www/storage/.ssh/id_rsa' },
>     
>   },
> }
> 

I tried adding _extra = { '--no-delete' } to rsync options but then lsyncd fails at startup with exit code 1.
I also tried with delete = false but no luck.

The problem is I'm using lsyncd in a mirror mode, on 2 servers both running a server, and it might cause loss of data if : 
* both lsyncd are down
* files are being created on both servers

In that case, whenever I start lsyncd on the first server, it'll delete what's not existing locally from the other server.

**Comment by axkibe** [comment]
the delete parameter is part of sync{} not settings{}

**Comment by Kyoshiro-san** [comment]
Indeed, my bad, works as expected.
Thanks a lot.

**Comment by axkibe** [comment]
Note to myself: There should be a checkgauge for settings{} as well, so it should throw an Error

**Comment by axkibe** [comment]
Next Lsyncd version will error out already on invokation time if you put a "Delete" entry in settings{}
