### ISSUE TITLE
Error/bug in layer 1 documentation

### ISSUE THREAD

**Issue by shmedia** [axkibe/lsyncd#410]
The documentation for layer 1 [here](https://axkibe.github.io/lsyncd/manual/config/layer1/) or [here as markdown](https://github.com/axkibe/lsyncd/blob/gh-pages/manual/config/layer1/index.md) contains a subtle bug.

The first example which shows the default.rsync code will only work correctly if only one file is synced. 
```lua
   local paths = elist.getPaths()
...
   spawn(elist, "/usr/bin/rsync",
       "<", paths,
```

That's because the line `"<", paths,` will expand to multiple arguments instead of one list of arguments. 
The current [default.rsync](https://github.com/axkibe/lsyncd/blob/master/default-rsync.lua#L196) in the repo does not have this issue, as the paths are concatenated.
```lua
local filter0 = table.concat( filterI, '\000' )
...
spawn( ...
		'<', filter0,
		...
		'--from0',
```
Here is an example logfile showing what happens if multiple files are synced with the code from the layer 1 documentation:
```
Fri Nov 25 14:49:17 2016 Normal: rsyncing list:
Fri Nov 25 14:49:17 2016 Normal:   /video/testfile4.tmp
Fri Nov 25 14:49:17 2016 Normal:   /video/testfile5.tmp
Fri Nov 25 14:49:17 2016 Normal:   /video/testfile6.tmp
Fri Nov 25 14:49:17 2016 Normal:   /video/testfile7.tmp
Fri Nov 25 14:49:17 2016 Normal:   /video/testfile8.tmp
Fri Nov 25 14:49:17 2016 Normal:   /video/testfile9.tmp
Fri Nov 25 14:49:17 2016 Normal:   /video/testfile10.tmp
Fri Nov 25 14:49:17 2016 Exec: /usr/bin/rsync [<] [/video/testfile4.tmp] [/video/testfile5.tmp] [/video/testfile6.tmp] [/video/testfile7.tmp] [/video/testfile8.tmp] [/video/testfile9.tmp] [/video/testfile10.tmp] [-Paud]  [--include-from=-] [--include=*/] [--exclude=*] [--prune-empty-dirs] [<FROM>] [<TO>]
Fri Nov 25 14:49:17 2016 Exec: one-sweeped pipe
Fri Nov 25 14:49:17 2016 Function: write( (Timestamp: 22944084.14) )
Fri Nov 25 14:49:17 2016 Statusfile: setting alarm: (Timestamp: 22944094.14)
Fri Nov 25 14:49:17 2016 Call: getAlarm( )
Fri Nov 25 14:49:17 2016 Alarm: runner.getAlarm returns: (Timestamp: 22944094.14)
Fri Nov 25 14:49:17 2016 Masterloop: going into select ( timeout 10 seconds )
building file list ...
rsync: change_dir "/video" failed: No such file or directory (2)
rsync: change_dir "/video" failed: No such file or directory (2)
rsync: change_dir "/video" failed: No such file or directory (2)
rsync: change_dir "/video" failed: No such file or directory (2)
rsync: change_dir "/video" failed: No such file or directory (2)
rsync: change_dir "/video" failed: No such file or directory (2)
```
It would be nice if you could provide a complete example there, or, if you want to keep the example in the documentation for its brevity, then please mention this shortcoming so that potential users don't try that code in production.

**Comment by axkibe** [comment]
I see, could you make a pull request?

**Comment by axkibe** [comment]
Thx, I changed that, albeit there are other things out of data on this page as well.
