### ISSUE TITLE
Does not work on macOS 10.12.1

### ISSUE THREAD

**Issue by jhgorse** [axkibe/lsyncd#411]
```
# sudo lsyncd -rsync /Users/username/Documents/dir server.local:/home/username/dir
Warn: Using /dev/fsevents which is considered an OSX internal interface.
Warn: Functionality might break across OSX versions (This is for 10.5.X)
Warn: A hanging Lsyncd might cause Spotlight/Timemachine doing extra work.
```
No exit code and no running process afterward.

**Comment by axkibe** [comment]
Try with -nodaemon

**Comment by jhgorse** [comment]
```
20:07:36 Normal: recursive startup rsync: /Users/jhg/Documents/work2016/openafs/read_concurrency/ -> deimos:/home/jhg/read_concurrency/
rsync: -lst: unknown option
rsync error: syntax or usage error (code 1) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-51/rsync/main.c(1337) [client=2.6.9]
```
So it is using the wrong rsync.

**Comment by axkibe** [comment]
Ya, the rsync by default is craaaazy old. That one doesn't handle white-spaces in filenames!

**Comment by bhyde** [comment]
Bearing in mind that one can not easily replace things in /usr/bin, like /usr/bin/rsync.  What's the chance that if a (a) build a better rsync, (b) put that in my path so it wins v.s. /usr/bin/rsync, and then (c) rebuild lsyncd so it doesn't invoke rsync with an absolute path (i.e. /usr/bin/rsync);  I will be able to work around this?

Or maybe a new parameter/config setting to point to the rsync executable.

**Comment by jhgorse** [comment]
@bhyde https://github.com/axkibe/lsyncd/issues/291#issuecomment-64248957

> (`brew install rsync`) and use `rsync = { binary = "/usr/local/bin/rsync" }`. Then -lts will be supported.

**Comment by axkibe** [comment]
PS: Lsyncd using an absolute path is a security feature. Otherwise a malicious user might override the standard binary.

**Comment by bhyde** [comment]
thanks!

**Comment by combs** [comment]
it is unusual to me that the binary version in /usr/local/bin/ is not preferred over /usr/bin/...

**Comment by DelightedD0D** [comment]
Is this mentioned anywhere in the docs? For me, this was difficult to find.

**Comment by axkibe** [comment]
If you desire please make a pull requests for the docs to improve them.

Absolute paths are to my problem pretty much standard in any place where security is a concern. Just look at some scripts from your distro in the /etc directory...

**Comment by burkestar** [comment]
Ok, I was piece together clues gathered from several places and got lsyncd working on Mac:

```
brew install rsync
brew install lsyncd
```

I was getting the SSH permission denied errors described, and figured out that the `~/.ssh/config` file was not being picked up for my user because of use of `sudo` when running `lsyncd` (so it uses root user's SSH config settings).

I created the following config file `~/.lsyncd`:
```
settings {
    logfile    = "/tmp/lsyncd.log",
    statusFile = "/tmp/lsyncd.status",
    nodaemon   = true,
}
sync {
    default.rsyncssh,
    source    = "/Users/dustin/workspace/shared-dir/",
    host = "dev",
    targetdir = "/shared-dir",
    rsync     = {
        binary   = "/usr/local/bin/rsync",
        archive  = true,
        compress = true,
   },
   ssh = {
       identityFile = "/Users/dustin/.ssh/id_rsa",
       options = {
          User = 'ubuntu'
       }
  }
}
```

I have `dev` defined in `~/etc/hosts` so that it resolves to the IP address, like:
```
10.50.12.34	dev
```

The key parts were defining the ssh.identityFile and ssh.options.User settings as documented in [Config Layer 4](https://axkibe.github.io/lsyncd/manual/config/layer4/)

Now I am able to run using:
```
sudo lsyncd ~/.lsyncd
```

Here are some relevant issues:
* https://github.com/axkibe/lsyncd/issues/301
* https://github.com/axkibe/lsyncd/issues/217

Hope that helps someone else and saves them an hour figuring this out. :)

**Comment by kumarunster** [comment]
@burkestar do you know similar alternative to lsyncd on Mac (want to sync my local dev folder to remote dev server vis ssh) which is working reliable and supported? I got lsyncd working here, but it only synchronizes on start. During the file changes it is printing "There are XX delays", printing changes in the pipeline but does not synchronize that files to the remote server. The amount of the delays is growing but nothing happens. So sad.
