### ISSUE TITLE
loading precompiled runner: runner: bad header in precompiled chunk

### ISSUE THREAD

**Issue by nosun** [axkibe/lsyncd#413]
my os is ubuntu 16.04
lua version is 5.2.4
after finished install lsyncd, I run it, find this mistake.

how do I fix this problem

**Comment by axkibe** [comment]
I guess the Lua compiler you used doesn't fit the Lua library you linked to.

In other words, you got two Lua's installed on your system and they conflict.

**Comment by nosun** [comment]
yes, I also installed luaJIT

**Comment by nosun** [comment]
yes, I found both lua5.1 and lua5.2 install on my ubuntu system,so I remove all of them, and then installed Lua5.2.

but then I met another mistake
"/usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)"

at cmake step. 

I try to fix it  but there is a few answer. 

Can you help me? Thanks!

**Comment by axkibe** [comment]
did you fully clean your lsyncd build directory (that is delete it completely and redownload it) after you changed your lua installations?

**Comment by nosun** [comment]
yes, I did it

**Comment by nosun** [comment]
today, I install the lsyncd again on my another  vps occur the error again:
```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find Lua (missing: LUA_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLua.cmake:113 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:9 (find_package)


-- Configuring incomplete, errors occurred!
See also "/opt/lsyncd-release-2.1.6/CMakeFiles/CMakeOutput.log".
```

system :  centos 6.5
lua: 1.5.4

**Comment by axkibe** [comment]
You need to install lua-dev

**Comment by nosun** [comment]
thanks, you are right, I fixed it

**Comment by Rikorose** [comment]
I ran into the same error. `FindLua.cmake` should first search for an corresponding lua executable and compiler instead of picking the first it sees:

```diff
diff --git a/cmake/FindLua.cmake b/cmake/FindLua.cmake
index ee7a63d..64662f8 100644
--- a/cmake/FindLua.cmake
+++ b/cmake/FindLua.cmake
@@ -32,10 +32,6 @@
 # Otherwise the module will search for any available Lua implementation

 # Always search for non-versioned lua first (recommended)
-SET(_POSSIBLE_LUA_INCLUDE include include/lua)
-SET(_POSSIBLE_LUA_EXECUTABLE lua)
-SET(_POSSIBLE_LUA_COMPILER luac)
-SET(_POSSIBLE_LUA_LIBRARY lua)

 # Determine possible naming suffixes (there is no standard for this)
 IF(Lua_FIND_VERSION_MAJOR AND Lua_FIND_VERSION_MINOR)
@@ -52,6 +48,11 @@ FOREACH(_SUFFIX ${_POSSIBLE_SUFFIXES})
   LIST(APPEND _POSSIBLE_LUA_LIBRARY "lua${_SUFFIX}")
 ENDFOREACH(_SUFFIX)

+LIST(APPEND _POSSIBLE_LUA_INCLUDE "include/lua")
+LIST(APPEND _POSSIBLE_LUA_EXECUTABLE "lua")
+LIST(APPEND _POSSIBLE_LUA_COMPILER "luac")
+LIST(APPEND _POSSIBLE_LUA_LIBRARY "lua")
+
 # Find the lua executable
 FIND_PROGRAM(LUA_EXECUTABLE
   NAMES ${_POSSIBLE_LUA_EXECUTABLE}
```

**Comment by krichter722** [comment]
Did the patch by @Rikorose get commited? If not, maybe you should open a PR since that eases the discussion of changes. It'd be nice if `lsyncd`'s build script could avoid that runtime error and refuse compilation until the user building the software chooses the correct parameters or setup the build system correctly.
