### ISSUE TITLE
How to remove source files _and_ folders?

### ISSUE THREAD

**Issue by evgenyvasilchenko** [axkibe/lsyncd#414]
Please advise how to remove SOURCE **files and folders** after they were successfully transferred? 
My current config below does that, but it does not delete copied **folders** from source.

```
sync {
        default.rsync,
        source  = "/opt/data/source/",
        target  = "/mnt/destination/",
        delay   = 60,
        delete  = false,

        rsync   = {
                archive  = true,
                _extra  = {"--remove-source-files"}
        }
}

```

**Comment by axkibe** [comment]
This is a rsync issue.

http://superuser.com/questions/676671/rsync-does-not-delete-source-directories
