### ISSUE TITLE
ubuntu 16.04 systemd issue

### ISSUE THREAD

**Issue by eugeneventer** [axkibe/lsyncd#419]
Hi @axkibe 

There seems to be an issue when I try to start lsyncd using systemd:
```sudo service lsyncd start && sudo service lsyncd status
● lsyncd.service - LSB: lsyncd daemon init script
   Loaded: loaded (/etc/init.d/lsyncd; bad; vendor preset: enabled)
   Active: active (exited) since Tue 2017-01-10 00:52:22 UTC; 22h ago
     Docs: man:systemd-sysv-generator(8)
    Tasks: 0
   Memory: 0B
      CPU: 0
```
Nothing in the configured lsync log file...

When I run lscynd manually with my config, things work fine. My config is located at `/etc/lsyncd/lsyncd.conf.lua`

Am I perhaps doing something wrong here?

Thanks!
Eugene.

**Comment by axkibe** [comment]
This isn't a Lsyncd issue.

If so, please be more specific what Lsyncd does wrong (and not a configuration issues with systemd)

PS: most likely it is due to lsyncd running as root and systemd environment instead of user environment, so it doesn't find your ssh identify or something like that, this just is not enough info.

**Comment by PatrickGrenier** [comment]
Hello,

I have the same problem and I would like to know how to start lsyncd as a simple user, not as root. is it possible ? We use ubuntu and no root ssh permission.

Patrick.

**Comment by Edenshaw** [comment]
I know this is closed, but for whoever person is having this issue, I have to create my own service for lsyncd. Next is the command that creates and enables the service (remember to change the user (my-linux-user):

`sudo tee /etc/systemd/system/lsyncd-user.service <<-EOF >/dev/null
    [Unit]
    Description=lsyncd-user-service
    After=network.target

    [Service]
    Type=simple

    User=my-linux-user
    Group=my-linux-user
    ExecStart=/usr/bin/lsyncd -log scarce /etc/lsyncd/lsyncd.conf.lua

    Restart=always
    RestartSec=5                        # Restart service after 5 seconds if node service crashes
    StandardOutput=syslog               # Output to syslog
    StandardError=syslog                # Output to syslog
    SyslogIdentifier=lsyncd-user-service

    [Install]
    WantedBy=multi-user.target
EOF

sudo systemctl enable lsyncd-user.service
sudo systemctl start lsyncd-user.service`
