### ISSUE TITLE
Older manual versions

### ISSUE THREAD

**Issue by acasademont** [axkibe/lsyncd#424]
Hi! 

We're using lsyncd 2.1.5 (the one that ships with Debian 7 Jessie) but we're having a very hard time finding documentation for that specific version, the old manual seems to have been removed from the wiki but the new website only documents the 2.2.x series and a lot of the options there don't work in our version.

Any chance to get back the old manual online? Thanks!

**Comment by axkibe** [comment]
The manual ought to always state since when an option is available since the 2.1 series.

If not please make a push request.

**Comment by axkibe** [comment]
I'm closing this, if there is anything that is wrongly documented in regards to Lsyncd 2.1.5 please reopen.
