### ISSUE TITLE
rsync: connection unexpectedly closed

### ISSUE THREAD

**Issue by oquidave** [axkibe/lsyncd#426]
Hello am trying to sync a local and remote folder at ip: 192.168.100.173 using lsyncd. However am running into issues to do with rsync failing. I test with rsync alone it works perfectly but it won't work with lsyncd. Am wondering what am doing wrong. 

tail -f /var/log/lsyncd/lsyncd.log
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.0]
Fri Feb 10 08:59:13 2017 Error: Temporary or permanent failure on startup of "/home/dokwii/work/docs/". Terminating since "insist" is not set.
Fri Feb 10 09:06:54 2017 Normal: recursive startup rsync: /home/dokwii/work/docs/ -> 192.168.100.173:/home/dokwii/backups/work_docs/
Permission denied, please try again.
Permission denied, please try again.
Permission denied (publickey,password).
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.0]

//With just rsync 
It works perfectly fine with just rsync 
 rsync -have 'ssh dokwii@192.168.100.173' /home/dokwii/work/docs/ /home/dokwii/backups/work_docs/
sending incremental file list

sent 523 bytes  received 12 bytes  1.07K bytes/sec
total size is 3.85M  speedup is 7,203.21

//my configs 
cat /etc/lsyncd/lsyncd.conf.lua 
settings {
        logfile = "/var/log/lsyncd/lsyncd.log",
        statusFile = "/var/log/lsyncd/lsyncd.status"
}

sync {
        default.rsyncssh,
        source = "/home/dokwii/work/docs",
        host = "192.168.100.173",
        targetdir = "/home/dokwii/backups/work_docs"
}

**Comment by axkibe** [comment]
My guess is, you are Lsyncd as a different user than you called rsync alone. 

PS: Since you called the targetdir "backups", note that live syncing only protects you from physical harddrive failure, and unwanted delete, will delete your "backup" too..

**Comment by oquidave** [comment]
Yes you are right. I had to add ssh keys for root and setup passwordless ssh for root. This is because lsync is running as root user. I wonder how I could set up lsync for non-root user though.

**Comment by axkibe** [comment]
I don't know, it depends on your distribution, or what other way you invoke Lsyncd, it's not a Lsyncd issue tough.
