### ISSUE TITLE
PID in lsyncd.pid is not correct

### ISSUE THREAD

**Issue by Bertutchio** [axkibe/lsyncd#427]
I've just upgraded my lsyncd to the version 2.2.1 on my mac and there is a problem with the pid.

The one in the file /var/log/lsyncd/lsyncd.pid is different than the one on the process list.

![pid](https://cloud.githubusercontent.com/assets/13383650/23013570/7ea0b096-f42b-11e6-90c1-900635c64a4c.png)

Am i doing something wrong or this is just a recent bug.

Thanks.

**Comment by axkibe** [comment]
Ah yes, this is arleady fixed in the GIT version. Sorry

**Comment by axkibe** [comment]
I just created a realese 2.2.2 that has this fix included.

(And other fixes over 2.2.1)
