### ISSUE TITLE
Cannot access /dev/fsevents monitor

### ISSUE THREAD

**Issue by christ-a-lix** [axkibe/lsyncd#428]
This command lsyncd /var/log/lsyncd/lsyncd.conf.lua gives me the following:
Warn: Using /dev/fsevents which is considered an OSX internal interface.
Warn: Functionality might break across OSX versions (This is for 10.5.X)
Warn: A hanging Lsyncd might cause Spotlight/Timemachine doing extra work.
Error: Cannot access /dev/fsevents monitor! (1:Operation not permitted)

I am using rsync 3.1.2, mac 10.12.3, lsyncd 2.2.2

**Comment by ValeriyMaslenikov** [comment]
Hi, I had the same issue, but it is solved for me by executing `lsyncd` with `sudo`

**Comment by axkibe** [comment]
Lsyncd needs to be ran as root.

However, the thing is, the whole OSX interface is dated. I currently don't advise using it, until someone rewrites the FsEvents Layer.

**Comment by wuservices** [comment]
I got it to work with sudo in brief testing as well on High Sierra. At first glance, it seemed to work pretty well, and I'm hoping to replace vagrant-gatling-rsync with it to quickly push dev changes to a remote environment.

Understood that it might not be in the best state now, but are there specific issues I might want to look out for, or if it works, should I be good to go?

Thanks for your work on this utility!

**Comment by axkibe** [comment]
The whole OSX line is no longer maintained, so I advise against using it. I'm not planning on maintaining  a FsEvents layers myself, however I'd accept somebody doing this for Lsyncd.

**Comment by noway** [comment]
What's the lsyncd alternative on MacOS then?

**Comment by timka** [comment]
@noway Not a real alternative but works for some cases like synching a cloned git repo to a remote development host (where it's cloned too).

```shell
fswatch --recursive --one-per-batch  . | while read line ; do rsync -ah --stats --delete-after ./ user@example.com:src/my-project --exclude=.direnv --exclude=.git ; echo ; date ; echo "\n" ; done
```
