### ISSUE TITLE
How to uninstall or reinstall lsyncd?

### ISSUE THREAD

**Issue by djester** [axkibe/lsyncd#429]
Hi!

I need to reinstall lsyncd to another target directory. But i not found uninstall option in make or cmake files. 

`make help` provide _clean_ option. But `make clean` do not delete old binary files.

Can i clean my lsyncd installation if i build it from source? I mean installation with defaut target.

Thanks & regards!

**Comment by axkibe** [comment]
http://stackoverflow.com/questions/19921017/cleaning-cmake-installed-files
