### ISSUE TITLE
lsyncd 2.1.6 doesn't track changes of symlinked files

### ISSUE THREAD

**Issue by timofeytt** [axkibe/lsyncd#430]
I have set `copy_links = true`. This transfers files on startup fine. However, when I change the actual files those changes don't get propagated to the remote destination. I'm guessing it's because the symlink file is not changed, but rather the source file of the symlink.

**Comment by axkibe** [comment]
Yes, Lsyncd doesn't track out of watched source symlinked files. Or in other words, the kernel doesn't notify Lsyncd about it.

Technically it could be coded that any encountered symlink is recognized and the target been watched (as long the target is not on a network drive). 

However, Lsyncd doesn't do this and I'm not planning to code that, it is not a trivial thing to do.
