### ISSUE TITLE
some source/targets omitted, skipped? (quietly)

### ISSUE THREAD

**Issue by lejeczek** [axkibe/lsyncd#431]
hi,
I have a setup as follows:
in lsyncd.conf

dofile( '/etc/lsyncd.d/whale-sysdata.to-dzien.lsyncd.conf' )
dofile( '/etc/lsyncd.d/whale-sysdata.to-rider.lsyncd.conf' )
dofile( '/etc/lsyncd.d/whale-sysdata.to-swir.lsyncd.conf' )

then each file as you can guess to to keep configuration for lsyncd from localhost to another server. In there I have a more less the same:

sync {
    default.rsyncssh,
    delay     = 5,
    maxDelays = 30,
    exclude   = ".*",
    rsync = { update = true, perms = true, acls = true, owner = true, group = true },
    host      = "swir",
    source    = "/root/bin",
    targetdir = "/root/bin",
    source    = "/etc/firewalld/services",
    targetdir = "/etc/firewalld/services",
    source    = "/yum.rpm/repo",
    targetdir = "/yum.rpm/repo",
    source    = "/var/lib/samba/Netlogon",
    targetdir = "/var/lib/samba/Netlogon",
    source    = "/etc/postfix",
    targetdir = "/etc/postfix",
}

there is two, three more sync { . But that one above, lsync omits some bits! I don't get /root/bin in logs and synced over to the server. Nor /var/lib/samba/Netlogon is not mentioned in the logs.
env: Centos 7.3 lsyncd-2.1.5-6.el7.x86_64

I'm not sure if something changed, I was pretty sure it had worked ok for long time.

**Comment by axkibe** [comment]
You need multiple calls to sync{}, each can have only one source and target see:

http://axkibe.github.io/lsyncd/faq/multiple-targets/
