### ISSUE TITLE
_extra suffix argument not work

### ISSUE THREAD

**Issue by ankyo** [axkibe/lsyncd#433]
_extra  = {
[[--suffix=~`date "+%y%d%m%H%M%S"` ]]
}

the date not work, it as string

**Comment by axkibe** [comment]
Lsyncd doesn not call the bash to call rsync, that would be a waste of ressources, does you cannot insert bash inclusions there.

If you need custom stuff like this, you'll need to code an appropriate Layer 1 configuration
https://axkibe.github.io/lsyncd/manual/config/layer1/
