### ISSUE TITLE
lsyncd logging

### ISSUE THREAD

**Issue by lastsky** [axkibe/lsyncd#440]
I'm trying to find why lsyncd stops working with error

~~~
Mon Apr 10 18:39:01 2017 Error: Backtrace 1 :[C]:-1
Mon Apr 10 18:39:01 2017 Error: Backtrace 2 :lsyncd.lua:3444
Mon Apr 10 18:42:12 2017 Error: in Lua: lsyncd.lua:3444: negative number of processes!
~~~

Nothing more informational. Found in --help message:

~~~
-log all will log all debug messages.
~~~

how can I add this to config at /etc/lsyncd.conf without touching systemd files or starting another instance?

**Comment by axkibe** [comment]
You can't. Logging categories are only configureable as invocation parameters. Sorry about that.

**Comment by lastsky** [comment]
thanks for clarify! closed...
