### ISSUE TITLE
_extra can not use empty param

### ISSUE THREAD

**Issue by sofire** [axkibe/lsyncd#442]
Like this:
_extra = {""}

will push all files( under root / ) to remote serve.

Is there something wrong?

**Comment by axkibe** [comment]
The way _extra works is, every entry is exactly one argument to the argv call, this is often not what a bash shell for example would parse. Dunno how rsync reacts when handed a zero-length string argument. You probably found out.

Suggested Solution: Don't use empty strings in _extra.

**Comment by sofire** [comment]
ok, thanks.
