### ISSUE TITLE
exclude not working

### ISSUE THREAD

**Issue by jaknoll** [axkibe/lsyncd#445]
The exclude directive in 'sync' doesn't seem to be working 100% for me.  It is excluding several items that I expected to be excluded, but some seem to be slipping through.

Configuration:

```
sync {
  default.rsync,
  source = "<source>",
  target = "<target>",
  delay= 5,
  rsync     = {
        archive   = true,
        verbose   = true,
    },
  exclude = {'.log' , 'system/server' , 'logs' , 'Log'},
}
```
Log during startup shows the exclude list.  Noticeably, the '.log' doesn't show up:
```
excluding
 logs
 Log
 system/server
```

And from later in the logs, you can see a directory with 'Logs' and ending in '.log' show up as a file that was sync'd:

```
sending incremental file list
Plex/config/Library/Application Support/Plex Media Server/Logs/Plex Media Server.log

sent 7,993 bytes  received 8,495 bytes  32,976.00 bytes/sec
total size is 1,984,163  speedup is 120.34
```

My understanding is that if an excluded text is found anywhere in the path the file would be excluded.  Have I misunderstood or is this a bug?

**Comment by axkibe** [comment]
I believe you need '*.log' and 'Log*' for the behavior you want.

**Comment by dante-til** [comment]
@axkibe Adding wildcard to the pattern worked for me. Thanks!

I had the same problem as @jaknoll because I wrongly interpreted the following quote from the manual
> Generally if any part of the pathname (see below Layer 3) of an event matches the text, it is excluded.

to mean that if any substring of the pathname is equal to the text, it is excluded. Now it seems to me that pathname parts are strictly file name and/or directory names.

**Comment by axkibe** [comment]
I see, pull requests to improve the manual area always welcome.

**Comment by dante-til** [comment]
Here is my pull request. #456

**Comment by pbroderi31** [comment]
Hello - I seem to be having a issue pretty similar in that I am unable to exclde sertain files from sysnching over from one server to another.  Here is my lsycnd.conf file:
 ```
 1
  2 settings {
  3         logfile = "/var/log/lsyncd/lsyncd.log",
  4         statusFile = "/var/log/lsyncd/lsyncd-status.log",
  5         statusInterval = 20
  6     }
  7 sync
  8         {
  9     default.rsync, delay=0,
 10     source="/usr/share/nginx/",
 11     target="10.1.108.87:/usr/share/nginx/",
 12     excludeFrom="/etc/lsyncd.exclude.txt",
 13     rsync= {
 14         owner = true,
 15         perms = true,
 16         group = true,
 17         compress = true,
 18         acls = true,
 19         verbose = true,
 20         rsh = "/usr/bin/ssh -p 22 -o StrictHostKeyChecking=no"}
 21 }

```
My lsyncd.exclude.txt is as follows as it is just a single line:  /usr/share/nginx/html/wp-config.phpBAK3/

I am just trying to exclude that file in my testing.  However it still copies over.  I have tried removing / at the enad and the satr but to no avail.  I am not sure where I am going wrong.  I have to say that this is a pretty awesome tool for synching data/files between two server.

Any help would be greatly appreciated.

Thank you.

**Comment by axkibe** [comment]
Exclusion are from sync root, not from filesystem root.

**Comment by pbroderi31** [comment]
Thank you Axkibe, I was able to figure it out by putting the following entry in my lsync.conf file

`exclude={ 'xxx-config*',' },`

Again, thank you.
