### ISSUE TITLE
Cannot make - lua not found

### ISSUE THREAD

**Issue by Bombdogs** [axkibe/lsyncd#447]
Trying to build this on an AWS linux AMI, not used cmake before, so this is highly likely user error, but I get the following error when trying to build...

```
[root@server build]# cmake ..
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find Lua (missing: LUA_LIBRARIES) (found version "5.1.4")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLua.cmake:120 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:9 (find_package)
```

lua and lua-devel are both installed...

```
# yum list installed | grep lua
lua.x86_64                           5.1.4-4.1.9.amzn1             installed    
lua-devel.x86_64                     5.1.4-4.1.9.amzn1             @amzn-main
```

What am I missing? Many thanks...

**Comment by Bombdogs** [comment]
Ohh yes user error indeed! I had some files left in the build/ directory from previous failed build (when I didn't have all the dependencies in place) - deleting these solved the problem. Normally I would do make clean, but cmake doesn't seem to have that option.

**Comment by axkibe** [comment]
"Normally I would do make clean, but cmake doesn't seem to have that option"

Thats why Lsyncd has a "distclean.sh" script in it's root directory.

**Comment by Bombdogs** [comment]
Thanks axkibe - I assume that's a common pattern for cmake-able projects - I will now know to look out for it in future, cheers!

**Comment by gsouf** [comment]
For those on ubuntu - could be because liblua is not installed.

For lua 5.2:

```
sudo apt-get install liblua5.2-dev
```
