### ISSUE TITLE
Why using IN_DONT_FOLLOW by default?

### ISSUE THREAD

**Issue by diego-treitos** [axkibe/lsyncd#448]
I am facing a problem where I would need symlinks files copied when they change. I am already using `copy_links` so the content of the symlink is copied instead of the symlink itself. However, the inotify is not being triggered when the targets of the symlinks change so I checked your code and I see that default mask uses IN_DONT_FOLLOW. Could that be optional? Is there any reason that I am not seeing to have that enabled by default?

**Comment by axkibe** [comment]
I doubt that inotify follow works that way, that when a file that is linked by a symlink that is in an directory that is being watched, will be notified.

**Comment by diego-treitos** [comment]
It actually does. I've tested with `inotifywait` tool.

```
cd /tmp
touch a
ln -s  a test
ln -s test test2
inotifywait -e close_write test2 &
echo "test" > a
```
You will see

```
test2 CLOSE_WRITE,CLOSE
```

So it followed the changes even through several symlinks

**Comment by axkibe** [comment]
You're creating the watch mark on the file tough, not on the directory.

**Comment by diego-treitos** [comment]
Yes I am. I didn't say anything about directories. I am using just files. In my particular case I am trying to sync certificates from letsencrypt, which creates symbolic links in `/etc/letsencrypt/live/<domain_name>/` for the current valid certificate and key files.

I have a different directory (`/srv/ssl`) with links to those files so all the links for all certificates and keys are in the same directory.
```
/srv/ssl/example.crt --> /etc/letsencrypt/live/example.com/fullchain.pem
/srv/ssl/example.key --> /etc/letsencrypt/live/example.com/privkey.pem
```

And then I want to sync `/srv/ssl` to `/etc/nginx/ssl` in several servers. I had it working except for the fact that it is not triggering due to `IN_DONT_FOLLOW`, although it syns on first lsync execution.

As you can see, this is quite a valid scenario to use `lsyncd` but unfortunately it doesn't work so I was wondering if there was a reason to use `IN_DONT_FOLLOW` by default.

**Comment by axkibe** [comment]
Well but Lsyncd works on directories not files.

**Comment by diego-treitos** [comment]
Ohh well, forgive my ignorance on this, but I thought that lsync used
inotify to watch changes on files inside directories.

Anyway I think lsync would be even more awesome if we could have more
control over inotify events. I guess I will use incron + rsync for now but
thanks a lot for giving me some insight on this.

Em 17/05/2017 2:08 da tarde, "Axel Kittenberger" <notifications@github.com>
escreveu:

**Comment by axkibe** [comment]
Putting marks on files instead of directories would tremendously increase the system load of Lsyncd and would also leave race conditions on new directories anyway.

Yes a small skript with incron+rsync seems to be sufficient, just take care to have it sophisticated enough to catch an change event, while rsync is running.

**Comment by axkibe** [comment]
I suppose this has been cared of.
