### ISSUE TITLE
Can't capture stdout/stderr

### ISSUE THREAD

**Issue by computerx138** [axkibe/lsyncd#449]
I'm trying to handle the output of lsyncd in no-daemon mode, but redirecting the output seems to stop the output.

This displays nothing:
`lsyncd /path/config 2>&1 | cat`

Config:
```
settings {
    nodaemon  = true
}
sync {
    default.rsyncssh,
    source    = "/home/path/",
    host      = "user@host",
    targetdir = "/home/path/",
    init      = false,
    exclude   = { ".git", "*___jb_*___", ".idea" },
    delay     = 0.5
}
```

Thanks

**Comment by axkibe** [comment]
Lsyncd doesn't line buffer flush stdout/stderr. Might be a good idea.

You can easily workaround this with:
stdbuf -o 0 lsyncd /path/config 2>&1 | cat

**Comment by computerx138** [comment]
Works beautifully, thank you.

Flushing on "Finish" would do tbh.

**Comment by axkibe** [comment]
This patch would work too:

```
diff --git a/lsyncd.c b/lsyncd.c
index 746f2d4..5ab21fd 100644
--- a/lsyncd.c
+++ b/lsyncd.c
@@ -2889,6 +2889,9 @@ main( int argc, char * argv[ ] )
        // gets a kernel parameter
        clocks_per_sec = sysconf( _SC_CLK_TCK );
 
+       setlinebuf( stdout );
+       setlinebuf( stderr );
+
        while( !term ) {
                main1( argc, argv );
        }
```

**Comment by axkibe** [comment]
This has been inserted as default into Lsyncd 2.2.3.

**Comment by ChristianCiach** [comment]
It's probably not a good idea to do that even in "daemon" mode. It took me forever to find out why lsyncd spams our journal on CentOS. Systemd seems to log everything from stdout into the journal/syslog.
