### ISSUE TITLE
Sould I set up a cron job for auto syncing?

### ISSUE THREAD

**Issue by sixthgalaxy** [axkibe/lsyncd#450]
I have configured lsyncd following your guide  on https://axkibe.github.io/lsyncd/manual/examples/. But syncing is not working, it works when I run the following command.
**lsyncd  -rsyncssh   /home  remotehost.org  backup-home/**

 Do I need running lsyncd on  the remote server as well? Do you I need to setup a cron job to get it working?

**Comment by weirdbricks** [comment]
Hi there, I'm not the author. 

If you are running rsync over SSH all you need on the remote server is that SSH is up and running. If your manual command `lsyncd -rsyncssh /home remotehost.org backup-home/` works without issue, then you most likely simply need someway to have lsyncd constantly running uninterrupted. 

For example you can have it running inside a screen session or you can even use monit to make sure it's always running in the background.

For example here's my lsyncd config:

```
settings {
	log        = all,
        logfile    = "/var/log/lsyncd.log",
        statusFile = "/tmp/lsyncd.status",
        pidfile    = "/var/run/lsyncd.pid",
        nodaemon   = false,
}
 
sync{
        default.rsyncssh,
        source    = "/some/awesome/source/directory",
        host      = "10.xxx.yyy.zzz",
        targetdir = "/even/awesomer/target/directory",
        delay     = 30,
        maxDelays = 10000,
        rsync     = {
                    compress = false,
                    checksum = true,
		    archive = true
        }
}
```

Then I add this configuration for Monit:

```
check process lsyncd pidfile /var/run/lsyncd.pid
 start program = "/usr/local/bin/lsyncd /usr/local/etc/lsyncd.conf"
 stop program  = "/bin/pkill lsyncd --signal 9"
```

and that's it - Monit will make sure lsyncd is always running.

Hope this helps!

**Comment by sixthgalaxy** [comment]
@weirdbricks- Thank you for your reply.
