### ISSUE TITLE
Using Excludes with Shell Scripts?

### ISSUE THREAD

**Issue by delmartechdude** [axkibe/lsyncd#451]
So I'm currently doing my rsyncs via a wrapper shell script because I wanted to use some rsync arguments that lsyncd doesn't support like `--filter`, which is actually quite different apparently from `exclude` Everything is working great, except that lsyncd is triggering the scripts on files that I really want filtered out. Nothing is getting synced because of the filters I have in place in my rsync commands in the script, but I would rather not have lsyncd busy all the time if it doesn't need to be. I also want the stuff I care about to get synced faster, instead of having to wait on lsyncd to stop "Retrying Modify" on the files I don't care about. I know if I was using exclude that it wouldn't be doing that, but since using the built-in rsync in lsyncd isn't an option for me, how can I exclude lsyncd from watching certain directories?

My current lua config file:
```
settings{
  statusFile = "/tmp/lsyncd.stat",
  logfile = "/var/log/lsyncd/lsyncd.log",
  statusInterval = 1,
  insist = true
}

core = {
  delay = 1,
  maxProcesses = 1,
  onCreate = "./opt/dosync.sh s",
  onModify = "./opt/dosync.sh s",
  onDelete = "./opt/dosync.sh s",
  onMove   = "./opt/dosync.sh s",
  onStartup = "./opt/dosync.sh s"
}

rep = {
  delay = 1,
  maxProcesses = 1,
  onCreate = "./opt/dosync.sh m",
  onModify = "./opt/dosync.sh m",
  onDelete = "./opt/dosync.sh m",
  onMove   = "./opt/dosync.sh m",
  onStartup = "./opt/dosync.sh m"
}



sync{ core, source = "/opt/git-root/core"}
sync{ rep, source = "/opt/rep"}
```

**Comment by axkibe** [comment]
Lsyncd 2.2.3 now natively supports filters.

**Comment by axkibe** [comment]
A bit more explanation, yes this is a twofold addition, not only need the filters to handed to rsync, Lsyncd also needs to filter these files in it's watch application and filter them itself, since during runtime it calls rsync with the --files-from parameter so rsync doesn't have to rescan the source tree on every call.

**Comment by delmartechdude** [comment]
Thank so much for adding this! Unfortunately we had to move onto using `Unison` because `lsyncd` just couldn't do what we needed, but we'll keep `lsyncd` in mind for next time now that it supports filters.
