### ISSUE TITLE
Event type problem

### ISSUE THREAD

**Issue by bobring** [axkibe/lsyncd#453]
I uploaded a file to my FTP server(CentOS 6.9 X86-64, Vsftpd 2.2.2, EXT4 filesystem), and then renamed it. My lsyncd-2.1.6  considered the rename operation as event "DELETE", and the latest version 2.2.2 considered the rename operation as event "DELETE" and "CREATE".

**Comment by axkibe** [comment]
See https://github.com/axkibe/lsyncd/issues/490#issuecomment-371825308

Move detection can break. I keep this as a bigger change for Lsyncd 3 to get fixed.
