### ISSUE TITLE
it would be great if "recursive" exclude worked

### ISSUE THREAD

**Issue by lejeczek** [axkibe/lsyncd#454]
hi,
having a dir, eg /top I'm trying to exclude any/all occurrences of folders with "logs" in names inside /top
I've tried: "**/logs" "*/logs" "*logs" "*logs*"
Does Lsyncd exclude recursively?
I cannot get it to work.
regards
L.

**Comment by axkibe** [comment]
logs/

**Comment by lejeczek** [comment]
nope, version 2.2.2
I have:
_targetnodes = {
...
_targetlist = {
...
for _, node in ipairs(_targetnodes) do
  for _, target in ipairs(_targetlist) do
    sync {
      default.rsyncssh,
      delay     = 5,
      maxDelays = 30,
      rsync     = { update = true, perms = true, acls = true, owner = true, group = true },
      exclude   = { ".*", ".log" },
      ..
end

and even these files get syncd: /home/server/logs/*log.
/home/server is in _targetlist
I've tried variety of combination and cannot get it to work, sorry.

**Comment by lejeczek** [comment]
I what I could see when I was listing a target dir - first listing showed no *log files but a second(s) later those also got there in the target.

**Comment by lejeczek** [comment]
status says:
..
Sync12 source=/opt/tomcat/
There are 0 delays
Excluding:
.*
*.log
..

but logs are synced. Is this a (serious) bug? (Asking so I'd know to stop trying)
rsync  version 3.1.2  both on source and target.

**Comment by lejeczek** [comment]
argh, painful to find out that lsyncd - in this respect - bellies up because of the "for loop" in the config.
Can you fix it? 
It would be a tremendous improvement, I'm guessing not only for me/us here, many must have it this/similar way, if lsyncd could handle these "things".
regards

**Comment by axkibe** [comment]
Sorry I currently don't have any time for any debug sessions. You got all the sources, you can run lsyncd with -log Exec to see how it calls rsync and see any possible effects.

From the manual
```
Generally if any part of the pathname (see below Layer 3) of an event matches the text, it is excluded. E.g. the file “/bin/foo/bar” matches the rule “foo”.
If the rule starts with a slash, it will only be matched at the beginning of the pathname
If the rule ends with a slash, it will only be matched at the end of a pathname
? matches any character that is not a slash.
* matches zero or more characters that are not a slash
** matches zero or more characters, this can be slashes.
```

But I still thing you simply use it wrongly.
'.*' would exclude any file or directory that starts with a .
'.log' would only exclude files or directories that are named exactly '.log'

If you want to exclude all directories called logs the rule is "logs" if it contains logs you need "*logs*", 

Any filename ending in .log would be "*.log".

Sorry, if this doesn't help you I don't have time right now for anything more. Consult the sources.

**Comment by lejeczek** [comment]
I realize I might have not been explicit enough. Problem(bug) is that
with config as follow(uses for loop)
`
_targetnodes = {
  "A",
  "B",
}
_targetlist = {
  "/root/bin",
  "/etc/firewalld/services",
  "/etc/samba",
...
}
for _, node in ipairs(_targetnodes) do
  for _, target in ipairs(_targetlist) do
    sync {
      default.rsyncssh,
      delay     = 5,
      maxDelays = 30,
      rsync     = { update = true, perms = true, acls = true, owner = true, group = true },
      exclude   = { '.*', '*.log', "logs/" },
      host      = node,
      source    = target,
      targetdir = target,
    }
  end
end
`
exclude fails to exclude any logs, both dirs and files. Even tough Lsync says (status + logs) it does exclude.

But! use NO loop, eg.:

sync {
      default.rsyncssh,
      delay     = 5,
      maxDelays = 30,
      rsync     = { update = true, perms = true, acls = true, owner = true, group = true },
      exclude   = { '.*', '*.log', "logs/" },
      host      = "rider",
      source    = "/opt/tomcat",
      targetdir = "/opt/tomcat",
    }

Then Lsync works as expected - it excludes '*.log', "logs/"

Do you see what I mean?

**Comment by axkibe** [comment]
No, honestly I think it is impossible the loop affects exclusion rules. 

Are you still certain Lsyncd misbehaves as you described? If yes, please reopen as new issue.
