### ISSUE TITLE
desktop notifications

### ISSUE THREAD

**Issue by gsouf** [axkibe/lsyncd#462]
Hi,

Would be glad to see a new feature that would allow to trigger a desktop notifications when a sync succeeded (or errored). 

The use case here is that I use lsyncd to work on local files that once updated are sent to a remote web server. Once file are synced I can check if all works correctly. Adding a notification will be very useful to know that I can check because sync has finished. 

I think it can also be useful in many other use cases.

Would you accept this feature to be implemented?

**Comment by znorris** [comment]
Perhaps you could implement this in your config by calling `notify-send` with [onAction](https://axkibe.github.io/lsyncd/manual/config/layer3/).

**Comment by gsouf** [comment]
That looks to be what I need! Didn't know about it. 
However I'm not sure there is an action that triggers when a sync has ended?

**Comment by axkibe** [comment]
I suggest going this way as laid out in the FAQs:

http://axkibe.github.io/lsyncd/faq/postscript/

**Comment by gsouf** [comment]
thanks @axkibe  That would work but, but a bit more complex that I would expect.  Perfect solution would be to point to a script when sync completed. If you think it's too complex to implement in lsyncd I will accommodate with this solution.

**Comment by axkibe** [comment]
The issue with this is,it complicates things what to do if that script to call when sync is completed fails.
