### ISSUE TITLE
Errors not visible to ansible.

### ISSUE THREAD

**Issue by AvtechScientific** [axkibe/lsyncd#469]
I configure lsyncd 2.1.6 using ansible 2.2.1.0 on Debian9. Restart handler is:
```
- name: restart lsyncd
  service:
    name: lsyncd
    state: restarted
```
which should be the same as running following from the command line:
`service lsyncd restart`

I don't know whether the problem is with ansible or with lsyncd, but when there errors in the config files, ansible's restart handler reports restarting lsyncd without errors (which is wrong - nothing works, and if I try to restart it manually from the command line, as above, I do see an error message). With other packages ansible does report errors on restart, that's why I assumed there is something wrong with lsyncd's error message handling.

Thank you!

**Comment by axkibe** [comment]
I know nothing about ansible, but since errors work fine if you try to start lsyncd from command line, I suppose this is in your ansible configuration..

**Comment by AvtechScientific** [comment]
Theoretically the issue might be that lsyncd makes error output to stdout, so I see it when running it from command line, however ansible expects it in stderr, doesn't see it and so assumes that everything went OK. I'm not saying that is the issue it's just an idea what could be wrong...

**Comment by axkibe** [comment]
No errors are reported on stderr by Lsyncd.
