### ISSUE TITLE
lsyncd won't start-up - SELinux policy prevents this sender from sending this message to this recipient?

### ISSUE THREAD

**Issue by sarlindo** [axkibe/lsyncd#470]
Running on **RHEL 7.2** and on the master lsyncd selinux is disabled and permissive on the target hosts, yet I keep getting this message and lsyncd won't startup.

**Master:**

[root@ip-172-X-X-X etc]# sestatus
SELinux status:                 disabled

**Target:**

[ec2-user@ip-172-X-X-X .ssh]$ sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   permissive
Mode from config file:          permissive
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      28

**The Error:**

[root@ip-172-X-X-X ~]# systemctl start lsyncd
Error getting authority: Error initializing authority: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An SELinux policy prevents this sender from sending this message to this recipient, 0 matched rules; type="method_call", sender="(null)" (inactive) interface="org.freedesktop.DBus" member="Hello" error name="(unset)" requested_reply="0" destination="org.freedesktop.DBus" (bus) (g-dbus-error-quark, 9)

**My lsyncd conf file:**

```
settings {
logfile = “/var/log/lsyncd/lsyncd.log”,
statusFile = “/var/log/lsyncd/lsyncd-status.log”,
statusInterval = 20
}

sync {
default.rsync,
source=”/data/sftp/”,
target=”ec2-user@xxxxxx:/data/sftp/”,
rsync = {
compress = true,
acls = true,
verbose = true,
archive = true,
perms = true,
owner = true,
rsh = “/usr/bin/ssh -p 22 -o StrictHostKeyChecking=no” }
}
```

**Comment by axkibe** [comment]
I got no idea what this is about, if it's anything Lsyncd doesn't do correctly, please reopen with more specifics, otherwise I suggest reporting this to Redhat.
