### ISSUE TITLE
Version: 2.2.2 fails to sync

### ISSUE THREAD

**Issue by we-sell-bags** [axkibe/lsyncd#472]
Version: 2.2.2

it seems that when it is run inside a centos7 container under openstack even when the daemon is running it will not sync, UNLESS the  root user is logged in.

below is listed the first run:

`sudo systemctl status lsyncd
● lsyncd.service - Live Syncing (Mirror) Daemon
   Loaded: loaded (/usr/lib/systemd/system/lsyncd.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2017-10-18 10:31:15 HKT; 1 day 23h ago
 Main PID: 5760 (lsyncd)
   CGroup: /system.slice/lsyncd.service
           └─5760 /usr/bin/lsyncd -nodaemon /etc/lsyncd.conf

Oct 18 10:31:15 romulus.novalocal systemd[1]: Started Live Syncing (Mirror) Daemon.
Oct 18 10:31:15 romulus.novalocal systemd[1]: Starting Live Syncing (Mirror) Daemon...`

even if the files are changed, they will not resync until the root/owner logs in and retouches the files

config file could not be any simpler.

`
settings{
	logfile = "/var/log/lsyncd.log",
	statusFile = "/tmp/lsyncd.stat",
	statusInterval = 2,
}

sync{
	default.rsync,
	maxDelays = 10000,
	source="/var/log/tomcat/",
	target="/nfs/synology/production/",
}`

**Comment by axkibe** [comment]
I suppose whoever writes the files in first place does this via another mount, so the events are not fired.

**Comment by we-sell-bags** [comment]
nope .. not possible

there are no external mounts accessed by other users , the files are generated in   /var/log/tomcat, by the system loggers and copied to an external mount. (via lsyncd)
when the "root" user is logged in and if a change is made to the file via  some system, they are replicated, but if the root user is not logged in, they do not appear to replicate.

its as if the process "dies" or somehow "deep sleeps"

**Comment by axkibe** [comment]
Could it be that the nfs target is only mounted/reachable when root is logged in?

**Comment by we-sell-bags** [comment]
nope!!!
there would be errors in the logs and it would not account for why some files are duplicated.

I STRONGLY suspect the JAVA JVM is not using the correct calls(monitored), since this log file is written by the JAVA engine, whereas the others are written by "system"

**Comment by axkibe** [comment]
Try adding this to settings:

inotifyMode = "Modify"

Maybe your tool is never closing the files.

**Comment by we-sell-bags** [comment]
Which is completely possible with a Java log file.

**Comment by jahmoh82** [comment]
I'm having the same issue:
it does duplicate files and folder to remote but its shows user and group as 1002

I'm using version 2.2.2 of Lsyncd

here is my setting:
```
settings {
	logfile = "/var/log/lsyncd/lsyncd.log",
        statusFile = "/var/log/lsyncd/lsyncd.status"
}

sync {
      	default.rsyncssh,
        source="/home",
        host="157.**.174.**",
        targetdir="/home/",
        delete = "running", -- prevents deletion of files on startup (ie when a server comes back online, don't delete files that are $
        delay = 5, -- run every 5 seconds instead of default 20
        exclude = {
                "/home/backup",
        },
	rsync = {
                archive = true, -- use the archive flag in rsync
                perms = true, -- Keep the permissions
                owner = true, -- Keep the owner
                compress = true,
                acls = true,
                xattrs = true,
                _extra = {"-a"}, -- Sometimes permissions and owners isn't copied correctly so the _extra can be used for any flag in $
        },
	delay = 5
}
```
