### ISSUE TITLE
synchronisation fail for some folders

### ISSUE THREAD

**Issue by boerti71** [axkibe/lsyncd#474]
Hi
I'm synchronizing between 2 Raspberries the /var/www folders and subfolders.
it works fine for 3 of 4 folders, one is struggling, permission denied.
I deleted the hole folder and subfolders from the struggling folder, executed the sync again and it synchronize once, but not a second time.
I'm uploading with Netbeans new php files on server 1, after 5 seconds he syncronizes with server 2.

any idea why one specific folder is struggling?

**Comment by axkibe** [comment]
Possibly:
http://axkibe.github.io/lsyncd/faq/nothing-after-startup/

**Comment by boerti71** [comment]
the strange thing is that it's working for 4 folders, but not for the 5th.
**at the main server are the following folder rights:**
drwxr-xr-x 3 www-data www-data 4096 nov 11  2016 exd.web.com
drwxr-xr-x 3 www-data www-data 4096 nov  4  2016 finance.web.com
drwxr-xr-x 3 www-data www-data 4096 nov  4  2016 hms.web.com
drwxr-xr-x 2 www-data www-data 4096 nov  3  2016 html
drwxr-xr-x 3 www-data www-data 4096 nov  4  2016 web.com
-rwxr-xr-x 1 www-data www-data   20 nov  3  2016 phpinfo.php
drwxr-xr-x 3 www-data www-data 4096 nov  4  2016 weather.web.com

**folder rights at remote:**
drwxr-xr-x 3 www-data www-data 4096 nov 11  2016 exd.web.com
drwxr-xr-x 3 www-data www-data 4096 nov  4  2016 finance.web.com
drwxr-xr-x 3 www-data www-data 4096 nov  4  2016 hms.web.com
drwxr-xr-x 2 www-data www-data 4096 nov  3  2016 html
drwxr-xr-x 3 www-data www-data 4096 nov  4  2016 web.com
-rwxr-xr-x 1 www-data www-data   20 nov  3  2016 phpinfo.php
drwxr-xr-x 3 www-data www-data 4096 nov  4  2016 weather.web.com

**when I upload to main server a file who is in exd.web.com:**
sender] _exit_cleanup(code=0, file=main.c, line=1183): about to call exit(0)
Tue Nov  7 17:35:19 2017 Normal: Startup of "/var/www/" finished: 0
Tue Nov  7 17:35:46 2017 Normal: Rsyncing list
/exd.web.com/public/Units/HeatP.php
opening connection using: ssh -p 22 192.168.1.6 rsync --server -svvvnldogtpRe.Lsfx  (7 args)
protected args: --no-r --delete . /var/www/  (4 args)
building file list ...
[sender] make_file(exd.web.com,*,2)
[sender] pushing local filters for /var/www/exd.web.com/
[sender] make_file(exd.web.com/public,*,2)
[sender] pushing local filters for /var/www/exd.web.com/public/
[sender] make_file(exd.web.com/public/Units,*,2)
[sender] pushing local filters for /var/www/exd.web.com/public/Units/
[sender] make_file(exd.web.com/public/Units/HeatP.php,*,0)
done
send_file_list done
send_files starting
server_recv(2) starting pid=4098
recv_file_name(exd.web.com)
recv_file_name(exd.web.com/public)
recv_file_name(exd.web.com/public/Units)
recv_file_name(exd.web.com/public/Units/HeatP.php)
received 4 names
recv_file_list done
get_local_name count=4 /var/www/
generator starting pid=4098
delta-transmission enabled
recv_generator(exd.web.com,0)
[generator] pushing local filters for /var/www/exd.web.com/
send_files(0, exd.web.com)
exd.web.com/
recv_generator(exd.web.com/public,1)
[generator] pushing local filters for /var/www/exd.web.com/public/
recv_generator(exd.web.com/public/Units,2)
[generator] pushing local filters for /var/www/exd.web.com/public/Units/
recv_generator(exd.web.com/public/Units/HeatP.php,3)
generate_files phase=1
recv_files(4) starting
send_files(1, exd.web.com/public)
exd.web.com/public/
send_files(2, exd.web.com/public/Units)
exd.web.com/public/Units/
send_files(3, exd.web.com/public/Units/HeatP.php)
exd.web.com/public/Units/HeatP.php
send_files phase=1
recv_files(exd.web.com)
recv_files(exd.web.com/public)
recv_files(exd.web.com/public/Units)
recv_files(exd.web.com/public/Units/HeatP.php)
recv_files phase=1
generate_files phase=2
send_files phase=2
send files finished
total: matches=0  hash_hits=0  false_alarms=0 data=0
recv_files phase=2
recv_files finished
generate_files phase=3
generate_files finished
sent 164 bytes  received 1,106 bytes  846.67 bytes/sec
total size is 14,444  speedup is 11.37 (DRY RUN)
[sender] _exit_cleanup(code=0, file=main.c, line=1183): about to call exit(0)

**when I upload to main server a file who is in  hms.web.com**
Tue Nov  7 17:35:47 2017 Normal: Finished (list): 0
Tue Nov  7 17:36:01 2017 Normal: Deleting list
/var/www//hms.web.com/public/HeatP/HeatPLOG.php.new
Permission denied, please try again.
Permission denied, please try again.
Permission denied (publickey,password).
Tue Nov  7 17:36:01 2017 Normal: Retrying (list): 255
Tue Nov  7 17:36:06 2017 Normal: Deleting list
/var/www//hms.fweb.com/public/HeatP/HeatPLOG.php.new
Permission denied, please try again.
Permission denied, please try again.
Permission denied (publickey,password).
Tue Nov  7 17:36:07 2017 Normal: Retrying (list): 255

any idea, tipp?

**Comment by axkibe** [comment]
You are doing the permissions wrong. Anyway, I'm 99.99999% sure, this is not a Lsyncd issue.

**Comment by boerti71** [comment]
ok, thank you:-)
