### ISSUE TITLE
rsync chown, chmod option bug

### ISSUE THREAD

**Issue by ritchietam** [axkibe/lsyncd#478]
here is my config:
settings {
    logfile      ="/var/log/lsyncd.log",
    statusFile   ="/var/log/lsyncd.status",
    inotifyMode  = "CloseWrite",
    maxProcesses = 8,
    maxDelays    = 1,
    }

sync{
    default.rsync,
    source="/var/lib/jenkins/workspace/ttttt",
    target="/data/www/ttttt",
    exclude={ ".git", "TAGS", "tags", ".gitignore" },
    init=false,
    delete=true,
    rsync = {
        compress=true,
        verbose=true,
        perms=false,
        chmod=775,
        owner=true
    }
}
ERROR: rsync: --chmod=755: unknown option

Anybody show me your config file which display how to use the chmod, chown, usermap, groupmap options?

**Comment by axkibe** [comment]
You likely got an too old rsync.

**Comment by ritchietam** [comment]
thanks

**Comment by ritchietam** [comment]
Fri Dec  1 19:24:00 2017 Normal: --- Startup, daemonizing ---
Fri Dec  1 19:25:00 2017 Normal: Calling rsync with filter-list of new/modified files/dirs
/index.html
/
Fri Dec  1 19:25:00 2017 Exec: /usr/local/bin/rsync [<] [/index.html
/] [-vzsolpt] [--chmod=nginx:nginx] [--chown=775] [-r] [--delete] [--ignore-errors] [--force] [--from0] [--include-from=-] [--exclude=*] [/var/lib/jenkins/workspace/sown/] [/data/www/sctown/]
Fri Dec  1 19:25:00 2017 Exec: one-sweeped pipe
rsync: Invalid argument passed to --chmod (nginx:nginx)
rsync error: syntax or usage error (code 1) at main.c(1575) [client=3.1.3dev]
Fri Dec  1 19:25:00 2017 Error: Failure with a list with exitcode = 1
Fri Dec  1 19:25:00 2017 Error: Critical exitcode.

**Comment by ritchietam** [comment]
this is part of my configure
    rsync = {
        binary="/usr/local/bin/rsync",
        compress=true,
        verbose=true,
        owner=true,
        chown="775",
        chmod="nginx:nginx",
        perms=true
    }

but I use the https://download.samba.org/pub/rsync/nightly/rsync-HEAD-20170123-0003GMT.tar.gz rsync version

**Comment by svenha** [comment]
You confused chown and chmod. The log even told you :-)

**Comment by ritchietam** [comment]
Can you show me a config example

**Comment by ritchietam** [comment]
Anybody can show you configure examples,thanks

**Comment by nazarovkv** [comment]
Hi, in your case it gonna be like this:
2 examples:
**Incorrect:**
rsync = {
binary="/usr/local/bin/rsync",
compress=true,
verbose=true,
owner=true,
chown="775", -- INCORRECT
chmod="nginx:nginx", -- INCORRECT
perms=true
}

**Correct**:
rsync = {
binary="/usr/local/bin/rsync",
compress=true,
verbose=true,
owner=true,
chown="nginx:nginx", -- CORRECT
chmod="775", -- CORRECT
perms=true
}

Feel the difference :-)

**Comment by ritchietam** [comment]
thank for all of your reply

**Comment by ZherebcovSergey** [comment]
ritchietam, did you manage to solve the problem?

I have
> rsync  version 3.1.1  protocol version 31
> Copyright (C) 1996-2014 by Andrew Tridgell, Wayne Davison, and others.
> Web site: http://rsync.samba.org/

On "Linux MEG-WEB-4 4.10.0-40-generic #44~16.04.1-Ubuntu SMP Thu Nov 9 15:37:44 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux"

And the following option does not work

```
      sync{
            default.rsync,
            delete = 'running',
            source=source,
            target=server .. ':' .. source,
            delay = 0,
            rsync = {
              owner=true,
              perms=true,
              chown="www-data:www-data"
            }
      } 
```

I got 

> Error: error preparing /root/.lsyncd/lsyncd.config: Parameter "rsync.chown" unknown. (if this is not a typo add it to checkgauge)

But 
`rsync -a --chown=www-data:www-data`
works fine

**Comment by axkibe** [comment]
chown was added to Lsyncd with 2.2.0, I suppose yours is older

**Comment by ZherebcovSergey** [comment]
`lsyncd -version`

> Version: 2.1.5

```
apt-get update
apt-get install --only-upgrade lsyncd
```

> lsyncd is already the newest version (2.1.5-2).

**Comment by nazarovkv** [comment]
You need to clone source code from lsyncd git repo, then build it (pls read the manual how to build lsyncd 2.2.0), and then start using it:-)

**Comment by ZherebcovSergey** [comment]
Thanks

**Comment by lejeczek** [comment]
I have very similar problem with 2.2.2 ver @Centos 7.
chmod seems okey, target gets perms fixed,
chown does not seem to work, target gets root ownership (but rsync does what's expected)

Any suggestions on hot to troubleshoot?
many thanks, L.

**Comment by nazarovkv** [comment]
@lejeczek what version of rsync is used? What is source ownership, is it differs from **root**?

**Comment by lejeczek** [comment]
source is root:root
rsync is everywhere the same, Centos everywhere.
$ rsync --version
rsync  version 3.1.2  protocol version 31

thanks.

**Comment by nazarovkv** [comment]
@lejeczek Try creating on target host missing user/group.

**Comment by lejeczek** [comment]
Why would I want to do that?
If that was the reason then it would have been very... very silly.
Also sort of defeat purpose of chown.

**Comment by nazarovkv** [comment]
@lejeczek Regarging http://man7.org/linux/man-pages/man1/rsync.1.html **--owner** option works only for super-user.

**Comment by lejeczek** [comment]
And lsyncd runs with root privileges, at least by default on Centos 7. And prove of it that is the resulting files on the target get root:root.

**Comment by nazarovkv** [comment]
@lejeczek can you provide config of lsyncd?

**Comment by lejeczek** [comment]
`settings {
  logfile    = "/var/log/lsyncd.log",
  statusFile = "/var/run/lsyncd.status",
  nodaemon   = false,
  insist = true,
}

sync {
      default.rsyncssh,
      delay     = 5,
      maxDelays = 30,
      rsync     = { verbose = true, update = false, perms = false, chmod = 750, chown = "jt455:mslab", },
      exclude   = { '.*', '*.log', 'logs/' },
      host =
      source = 
      target =
}`

**Comment by lejeczek** [comment]
for those you might need it, here, watch for the difference with the line in my last comment:
..
rsync     = { verbose = true, owner=true, group = true, perms = true, update = false, chmod = 750, chown = "Auser:Bgroup" }

nara.

**Comment by okansahin** [comment]
I'm still getting 

> Error: error preparing /etc/lsyncd.conf: Parameter "chown" unknown. ( if this is not a typo add it to checkgauge )

with

`rsync = { verbose = true, owner=true, group = true, perms = true, update = false, chmod = 750, chown = "apache:apache" }
`

Lsync version is 2.2.2 and rsync version is 3.1.2  protocol version 31

**Comment by nazarovkv** [comment]
In rsync section of lsyncd.conf try using "_extra" key.
See referernce: https://axkibe.github.io/lsyncd/manual/config/layer4/

**Comment by nazarovkv** [comment]
And replace: 
```
sync {
default.rsyncssh,
....
```
With
```
sync {
default.rsync,
....
```

**Comment by okansahin** [comment]
But if I change rsyncssh to rsync the ssh config errors at this time. Is there any way to do it without extra parameter? Here is my full config,

`sync{
	default.rsyncssh, 
	source="/home/www", 
	host="10.10.0.3", 
	targetdir="/home/www/", 
	exclude = {"/home/www/system/logs"},
	delay=5, 
	delete="running",
	ssh = {
		port=3322,
		identityFile='/root/.ssh/id_rsa'
	},
	rsync = { verbose = true, owner=true, group = true, perms = true, update = false, chmod = 750, chown = "apache:apache" }	
}
`

**Comment by nazarovkv** [comment]
Create ~/.ssh/config file for user under which lsyncd run(I guess `root` user in your case) with next content:
```
Host 10.10.0.3 #Or whatever IP is used to connect
     Port 3322
     IdentityFile /root/.ssh/id_rsa
```
```
sync{
	default.rsync,
	source="/home/www",
	targetdir="10.10.0.3:/home/www/", -- once again, this IP must match IP in ~/.ssh/config
	exclude = {"/home/www/system/logs"},
	delay=5,
	delete="running",
	rsync = { 
			verbose = true, 
			owner=true, 
			group = true, 
			perms = true, 
			update = false, 
			chmod = 750, 
			chown = "apache:apache" 
	}
}
```

**Comment by okansahin** [comment]
It works as expected. Thank you.

**Comment by nazarovkv** [comment]
> It works as expected. Thank you.

You’re welcome!
