### ISSUE TITLE
Is there a way to to ignore non-zero status code from spawn?

### ISSUE THREAD

**Issue by itemir** [axkibe/lsyncd#479]
I am testing a new lua config for a cloud service that uses external cli commands to upload and delete files. In some instances (like creating several files and deleting them immediately afterwards), external processes that have been spawned can return non-zero error codes. These can be expected (like when trying to delete a file that doesn't exist). When this happens lsyncd exists with "Error: Critical exicode"

Is there a way to check the return code from spawn within the lua script, and selectively ignore and log the error instead of exiting the main process?

**Comment by axkibe** [comment]
You can see the default collect function, it quieries the "exitcodes" table
https://github.com/axkibe/lsyncd/blob/master/default.lua#L91

You can override that function with your own, or provide your exitcodes table.
For rsync this is for example:
https://github.com/axkibe/lsyncd/blob/master/default.lua#L313

Which you can see is simply activated in the default rsync config here:
https://github.com/axkibe/lsyncd/blob/master/default-rsync.lua#L666

**Comment by itemir** [comment]
Perfect, thank you. I have overwritten the collect function and it did the job.
