### ISSUE TITLE
Lsync multiple directories

### ISSUE THREAD

**Issue by Qtrain** [axkibe/lsyncd#480]
Is there any way to specify multiple source/target directories, like the following:

```
sync {
    default.rsyncssh,
    source="/etc/nginx/",
    source="/srv/",
    host="root@192.168.192.110",
    targetdir="/etc/nginx/",
    targetdir="/srv",


    rsync = {
        archive = true,
        perms = true,
        owner = true,
        _extra = {"-a"},
}
```

**Comment by axkibe** [comment]
Technically the question is slightly different, but the answer is still the same:
http://axkibe.github.io/lsyncd/faq/multiple-targets/

**Comment by gauravcanon** [comment]
My lsyncd is only sync first section of config
`settings  {
	logfile = "/var/log/lsyncd/lsyncd.log",
	statusFile = "/var/log/lsyncd/lsyncd.status"
}


--Sync

sync {
	default.rsync,
	source = "/home/gaurav/Temp/pa/",
	target = "/home/gaurav/pawpra/pa/"
}

sync {
        default.rsync,
        source = "/home/gaurav/Temp/connect/",
        target = "/var/www/connect/"
}
`
`cat /var/log/lsyncd/lsyncd.status`
```
Lsyncd status report at Thu Dec 14 07:30:23 2017

Sync1 source=/home/gaurav/Temp/pa/
There are 0 delays
Excluding:
  nothing.


Inotify watching 5 directories
  1: /home/gaurav/Temp/pa/
  2: /home/gaurav/Temp/pa/js/
  3: /home/gaurav/Temp/pa/fonts/
  4: /home/gaurav/Temp/pa/img/
  5: /home/gaurav/Temp/pa/css/

```

What i am doing worng . even restarted lsyncd

**Comment by Qtrain** [comment]
@axkibe 

It looks like you can sync multiple directories to multiple different targets.  Last time I checked, it didn't seem possible to sync multiple directories on ONE source node to ONE target.

**Comment by axkibe** [comment]
Sure, just run the sync command multiple times for the same target.
