### ISSUE TITLE
Permission denied after first sync

### ISSUE THREAD

**Issue by madskills700** [axkibe/lsyncd#485]
Hello, i have a trouble while using lsyncd.
First sync was successful, but next sync's fail with ssh error "Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password)"
My config (project dirs and names some changed):
`settings{`
`  logfile="/var/log/lsyncd/lsyncd.log",`
`  statusFile="/var/log/lsyncd/lsyncd.status",`
`  statusinterval=20`
`}`

`sync{`
`   default.rsyncssh,`
`  source="/srv",`
`  host="172.26.7.204",`
`  delay=5,`
`  targetdir="/home/user/project_backup",`
`  rsync = {`
`      compress=true,`
`      group=true,`
`      owner=true,`
`      checksum=true,`
`      hard_links=true,`
`      perms=true,`
`      update=true,`
`      xattrs=true,`
`      rsh="/usr/bin/ssh -p 22 -l user -i /home/user/.ssh/id_rsa -o StrictHostKeyChecking=no"`
`  }`
`}`

I think after first sync service trying to connect ssh with root username, but i need to connect with my username. Maybe it is not a bug, but in documentation i cant find another way. Ssh server and keys are correct and configured, because first sync was successful.

Some logs are [here](http://sprunge.us/EOKU)

**Comment by axkibe** [comment]
Just use "default.rsync" without ssh. It's simpler since you don't have to configure both manipulation channels that way, where you missed here one.

**Comment by madskills700** [comment]
My config works fine, if i add 'user@' to host and put keyfile in /root/.ssh
Hmm, '-i /home/user/.ssh/id_rsa' in rsh={} is not working (only works one time) or i made a mistake. 
Thanks for help!
