### ISSUE TITLE
Lsyncd is not fully support Lua 5.3

### ISSUE THREAD

**Issue by terranisu** [axkibe/lsyncd#487]
Hello @axkibe,

When I use layer 3 config and run `lsyncd 2.2.2` on `Lua 5.3` (macOS El Capitan), in my case sync configuration looks like this:
```
-- Ansible managed
cmd = ...a simple bash script which runs unison...

unison = {
  maxProcesses = 1,
  delay = 3,
  onStartup = cmd,
  onAttrib = cmd,
  onCreate = cmd,
  onDelete = cmd,
  onModify = cmd,
  onMove = cmd,
}

sync {
  unison,
  source = "/Users/user/path/to/source",
  target = "ssh://user@host//apps/path/to/target",
  exitcodes = { [0] = "ok", [1] = "again", [2] = "again", [3] = "die" },
}
```

it gives me such error:
```
10:03:21 Normal: --- Startup, daemonizing ---
10:03:21 Normal: --- Startup, daemonizing ---
Tue Jan  9 10:03:21 2018 Error: in Lua: ...d-20171206-58915-1xdqiml/lsyncd-release-2.2.2/lsyncd.lua:4850: Access of non-existing global "loadstring"
Tue Jan  9 10:03:21 2018 Error: Backtrace 1 :[C]:-1
Tue Jan  9 10:03:21 2018 Error: Backtrace 2 :...d-20171206-58915-1xdqiml/lsyncd-release-2.2.2/lsyncd.lua:608
Tue Jan  9 10:03:21 2018 Error: Backtrace 3 :...d-20171206-58915-1xdqiml/lsyncd-release-2.2.2/lsyncd.lua:4850
```

I've checked the code and after brief googling, I've learned the problem is `loadstring` function, that has been removed from `Lua 5.3` completely (in `Lua 5.2` this function is already deprecated). You have to use the `load` function instead.
To make `lsyncd` be able to run on `Lua 5.3` I've come up with a small and straightforward fix. However, I'm not quite sure it's a good one:
https://github.com/catawiki/lsyncd/commit/1a7e01dfd5fe8c9d89ae8741ed4a25c8aaa84790

What do you think? Shall I propose such PR to fix the issue?

**Comment by axkibe** [comment]
Fixed it, thank you. I suppose we can drop Lua5.1 compatibility for Lsyncd by now.
