### ISSUE TITLE
Question: If source is in the rsync protocol

### ISSUE THREAD

**Issue by seonghobae** [axkibe/lsyncd#489]
```sh
root@vultr:~# lsyncd -rsyncssh cran-rsync@cran.r-project.org: /mnt/obj/CRAN
Error: rsyncssh needs 3 arguments
root@vultr:~# lsyncd -rsync cran-rsync@cran.r-project.org: /mnt/obj/CRAN
Error: failure getting absolute path of [cran-rsync@cran.r-project.org:]
Error: Cannot access source directory: cran-rsync@cran.r-project.org:
```

I want to the lsyncd, alternative software of the rsync, but I can not run if the source is in the rsync:// protocol. Is this behaviour not acceptable in the lsyncd software?

**Comment by axkibe** [comment]
Lsyncd needs to run where the source is physically located, otherwise the event notification system when the source changed does not work.
