### ISSUE TITLE
My exclude list seems not to work

### ISSUE THREAD

**Issue by rvencu** [axkibe/lsyncd#491]
Here is my config, I need to exclude for instance php files and they are still uploaded. Actually all the files are uploaded to the remote server even  like no exclude list is present

`----
-- User configuration file for lsyncd.
--
-- Simple example for default rsync, but executing moves through on the target.
--
-- For more examples, see /usr/share/doc/lsyncd*/examples/
-- 
settings {
	logfile = "/var/log/lsyncd.log",
    statusFile = "/var/log/lsyncd.stat",
    statusInterval = 2,
}

sync{
	default.rsync,
	source="/home/dentfix/public_html/",
	target="u14696022443734412@push-12.cdnsun.com:/public/",
    rsync={
        rsh = "/usr/bin/ssh -l root -i /root/.ssh/id_rsa_cdn",
        prune_empty_dirs = true
    },
    exclude = { '*audit-log', 'wflogs', '*temp-write-test*', 'igcache' , 'livehelp', 'disqus', 'cgi-bin', '*.ht*', '.ics', '.csv', '.ini', '.well-known', '.php*', '.htm*', '.cgi*', 'error_log', '.sh', '.txt', '.xml', '.dump', '.crt', '.iso*', '.zip', '.pdf', '.rar', '.tar', '.gz', '.mo', '.po', '.json' },
}`

**Comment by axkibe** [comment]
Shouldn't it be '*.json', '*.po' and so on?

**Comment by rvencu** [comment]
Apparently yes still in docs the example is set without * so I got confused about it. Thanks

**Comment by axkibe** [comment]
I see, corrected in the docs, I wonder if it's always been there wrong or the ```'*'``` was somehow lost in the transistion from gollum to jekyll based doc system.
