### ISSUE TITLE
How to run .lua config on system startup

### ISSUE THREAD

**Issue by matej86** [axkibe/lsyncd#494]
Hello,

I am running Ubuntu 16.04.4 OS on both local and remote pc. 

I have successfully configured lsyncd to sync a local folder to a remote folder using ssh. It is working like a charm, really.

I start lsyncd using this command lsyncd ~/lsyncd/securitycam.lua

I need to make my local pc to autostart this command on every boot.

Do I need to create a service for this (if so, how)? Or do I to put this command in /etc/rc.local?

thanks

**Comment by axkibe** [comment]
Please direct requests of help to the lsyncd user group
https://groups.google.com/forum/#!forum/lsyncd

This is only for issues and discussions regarding the development of Lsyncd.
