### ISSUE TITLE
Lsyncd service failure

### ISSUE THREAD

**Issue by matej86** [axkibe/lsyncd#495]
Hi,

I need help configuring the service for Lsyncd.

I created a service for the last version of Lsyncd based on the patter I found [issue #438](https://github.com/axkibe/lsyncd/issues/438).

Every time I start the service and I check the status of the service I see the following error:

● lsyncd-sorveglianza.service - lsyncd
   Loaded: loaded (/etc/systemd/system/lsyncd-sorveglianza.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since mar 2018-03-20 09:26:06 CET; 937ms ago
  Process: 3388 ExecStart=/usr/local/bin/lsyncd -nodaemon /etc/lsyncd/sorveglianza.lua (code=exited, status=255)
 Main PID: 3388 (code=exited, status=255)

mar 20 09:26:06 ServerBS systemd[1]: lsyncd-sorveglianza.service: Unit entered failed state.
mar 20 09:26:06 ServerBS systemd[1]: lsyncd-sorveglianza.service: Failed with result 'exit-code'.
mar 20 09:26:06 ServerBS systemd[1]: lsyncd-sorveglianza.service: Service hold-off time over, scheduling restart.
mar 20 09:26:06 ServerBS systemd[1]: Stopped lsyncd.
mar 20 09:26:06 ServerBS systemd[1]: lsyncd-sorveglianza.service: Start request repeated too quickly.
mar 20 09:26:06 ServerBS systemd[1]: Failed to start lsyncd.

This is the configuration of the service:

[Unit]
Description=lsyncd
After=network.target

[Service]
Type=simple
PIDFile=/var/run/lsyncd.pid
ExecStart=/usr/local/bin/lsyncd -nodaemon /etc/lsyncd/sorveglianza.lua
ExecReload=/bin/kill -HUP $MAINPID
Restart=always

[Install]
WantedBy=multi-user.target

**Comment by axkibe** [comment]
Please direct requests of help to the lsyncd user group
https://groups.google.com/forum/#!forum/lsyncd

This is only for issues and discussions regarding the development of Lsyncd.

**Comment by matej86** [comment]
mm I doubt my question will be visible enough on a google group? Who is using google groups??

**Comment by axkibe** [comment]
Question 2: https://groups.google.com/forum/#!managemembers/lsyncd/members/active

I don't see it my task to help people setting up Lsyncd who arent familiar enough with Linux. Sorry, I jsut don't have time for this.

Lsyncd as systemd service is long used, and default in Debian/Ubuntu (albeit the Lsyncd version there is a bit old as far I know). It will be improved to Lsyncd 3, but it's possible now already.

However, if you find an actual bug to Lsyncd please use "Issues" service here, otherwise this isn't the place.

**Comment by matej86** [comment]
Since the lsyncd into the ubuntu repository is not updated to the last
version, I was forced to download it from the github site and there is no
services..... I created one but it doesn't work. Also, the guide of lsyncd
doesn't tell anything about the service. It should.
Anyway, thank you for your precious help, really.........


Il mar 20 mar 2018, 11:04 Axel Kittenberger <notifications@github.com> ha
scritto:
