### ISSUE TITLE
An "make" error Arhlinux

### ISSUE THREAD

**Issue by lumazer** [axkibe/lsyncd#501]
uname -a
Linux 4.15.14-1-ARCH #1 SMP PREEMPT Wed Mar 28 17:34:29 UTC 2018 x86_64 GNU/Linux

extra/lua 5.3.4-2 [installed]

$ make
[ 11%] Linking C executable lsyncd
CMakeFiles/lsyncd.dir/lsyncd.c.o: In function `l_exec':
lsyncd.c:(.text+0x176c): undefined reference to `lua_rotate'
lsyncd.c:(.text+0x1826): undefined reference to `lua_rotate'
lsyncd.c:(.text+0x18af): undefined reference to `lua_rotate'
CMakeFiles/lsyncd.dir/lsyncd.c.o: In function `load_runner_func':
lsyncd.c:(.text+0x371c): undefined reference to `lua_rotate'
CMakeFiles/lsyncd.dir/lsyncd.c.o: In function `main1':
lsyncd.c:(.text+0x4a02): undefined reference to `lua_rotate'
CMakeFiles/lsyncd.dir/lsyncd.c.o:lsyncd.c:(.text+0x4a99): more undefined references to `lua_rotate' follow
collect2: error: running ld complete with code 1
make[2]: *** [CMakeFiles/lsyncd.dir/build.make:198: lsyncd] Error 1
make[1]: *** [CMakeFiles/Makefile2:132: CMakeFiles/lsyncd.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by axkibe** [comment]
You're not linking against the same library as you're compiling against. I suggest removing all lua libraries but one.

**Comment by lumazer** [comment]
It realy is. Thanks a lot!
