### ISSUE TITLE
Lsync runned but not sync files

### ISSUE THREAD

**Issue by swood** [axkibe/lsyncd#506]
I have a strange question. My config below, lsyncd started, but files don't sync to remote host:

settings {
        logfile = "/var/log/lsyncd/lsyncd.log",
        statusFile = "/var/log/lsyncd/lsyncd.status",
        inotifyMode = "Modify",
        insist       = true,
        statusInterval = 10,
}
sync{default.rsync,
        source = "/data/site.ru",
        target = "10.10.10.12:/data/site/",
        excludeFrom = "/etc/lsyncd/logs_exclude.list",
        init   = false,
        rsync = {
                compress = true,
                archive  = true,
                whole_file = false,
                _extra = {"--bwlimit=50000"},
        }
}

Probably my config is wrong?
How I checked? On the source place I created a file and waiting for the same file on the target server, but nothing happens.

**Comment by axkibe** [comment]
Well look into the log file what happens.

If it doesn't contain enough info, run Lsyncd with "-log all"

**Comment by swood** [comment]
The log looks like this:

Sun Apr 29 23:16:15 2018 Call: inotifyEvent( )
Sun Apr 29 23:16:15 2018 Inotify: got event Modify 57d4093af0f61936ff7a4cf675e6e3baf5067573(6760)
Sun Apr 29 23:16:15 2018 Function: delay( Sync1, Modify, /data/attachments/5/7/57d4093af0f61936ff7a4cf675e6e3baf5067573, (nil) )
Sun Apr 29 23:16:16 2018 Delay: New Modify: /data/attachments/5/7/57d4093af0f61936ff7a4cf675e6e3baf5067573
Sun Apr 29 23:16:16 2018 Call: cycle( )
Sun Apr 29 23:16:16 2018 Function: cycle( (Timestamp: 68231068.24) )
Sun Apr 29 23:16:16 2018 Call: getAlarm( )
Sun Apr 29 23:16:16 2018 Function: getAlarm( )
Sun Apr 29 23:16:16 2018 Masterloop: going into select ( no timeout )
Sun Apr 29 23:16:16 2018 Call: inotifyEvent( )
Sun Apr 29 23:16:16 2018 Inotify: got event Modify c6e7f91d6fecdf562767e29aa14edd2d4c481217(6963)
Sun Apr 29 23:16:16 2018 Function: delay( Sync1, Modify, /data/attachments/c/6/c6e7f91d6fecdf562767e29aa14edd2d4c481217, (nil) )
Sun Apr 29 23:16:16 2018 Delay: New Modify: /data/attachments/c/6/c6e7f91d6fecdf562767e29aa14edd2d4c481217
Sun Apr 29 23:16:16 2018 Call: inotifyEvent( )
Sun Apr 29 23:16:16 2018 Inotify: got event Modify 57d4093af0f61936ff7a4cf675e6e3baf5067573(6760)
Sun Apr 29 23:16:16 2018 Function: delay( Sync1, Modify, /data/attachments/5/7/57d4093af0f61936ff7a4cf675e6e3baf5067573, (nil) )

**Comment by axkibe** [comment]
Looks to me like those files might get excluded.
What does 
```excludeFrom = "/etc/lsyncd/logs_exclude.list",```
contain, or what happens if you leave the exclusions away?

**Comment by swood** [comment]
Nothing extremely horrible, I hope:

# cat /etc/lsyncd/logs_exclude.list
.ssh
/*/app/*/log/*
/*/app/*/logs/*
/*/lib/symfony/cache/*
/*/attachments_cache/*
/*/logs/*
/*/log/*
/*/cache/*

**Comment by axkibe** [comment]
Hmmm, from the log snipped you posted, my guess is, that Lsyncd stashed the modify event due to some still running operation.

Can you please restart Lsyncd and post the log from start?

BTW: If you use init=false, the specific source directories like /5/7/ do have to be available on the target. Lsyncd won't create them in that case.

**Comment by swood** [comment]
Hmmm....why the previous version was created directories and current don't?
I have a very big storage for about 2Tb and each start of lsyncd is a huge slow...
Yeah, I can do that, but I wish to send this log to you directly if you don't mind.

**Comment by axkibe** [comment]
IMO the deal with "init=false" was always that the target has to have the directory structure in place. I'm not sure about that tough.

About the log, I don't want to skim through a hugh log anyway. Can't you make a minimal example of what doesn't work?

**Comment by swood** [comment]
I've added "init=true" to my config and received a very interesting output at the end of the log:

Mon Apr 30 23:00:28 2018 Call: getAlarm( )
Mon Apr 30 23:00:28 2018 Function: getAlarm( )
Mon Apr 30 23:00:28 2018 Alarm: runner.getAlarm returns: (true)
Mon Apr 30 23:00:28 2018 Masterloop: immediately handling delays.
Mon Apr 30 23:00:28 2018 Call: cycle( )
Mon Apr 30 23:00:28 2018 Function: cycle( (Timestamp: 68316520.79) )
Mon Apr 30 23:00:28 2018 Function: invokeActions( "Sync1", (Timestamp: 68316520.79) )
Mon Apr 30 23:00:28 2018 Error: in Lua: /usr/src/lsyncd/lsyncd.lua:2842: attempt to call field 'init' (a boolean value)
Mon Apr 30 23:00:28 2018 Error: Backtrace 1 :/usr/src/lsyncd/lsyncd.lua:2842
Mon Apr 30 23:00:28 2018 Error: Backtrace 2 :/usr/src/lsyncd/lsyncd.lua:4564

**Comment by axkibe** [comment]
init=true is not valid, init must be either unset (default function) a function as described in layer 1 or false.

**Comment by saulzy** [comment]
source ssh-copy-id to target: 10.10.10.12

**Comment by axkibe** [comment]
I suppose this is solved.
