### ISSUE TITLE
Is there is way to know if particular set of files are finished syncing? 

### ISSUE THREAD

**Issue by piyushcs** [axkibe/lsyncd#507]
I can see in lsyncd log that a file create, modify event has been triggered, based on that rsync or any bash command is triggered, but doing regex on logs is probably not a good idea, I want to provide a list, based on that need to know if all the files are finished syncing.
Lets assume files are static for now.

**Comment by axkibe** [comment]
Look at default.lua, there you have the default ```collect``` function which is called when a subprocess finished, succesfully or with error. You can overload with your code -- which can be an altered copy that does look into singular agents and lists. For singular items you can get it's path with .path for list with .getPaths( ).

**Comment by piyushcs** [comment]
Is there way to specify max retry count somewhere for exitcodes.

**Comment by axkibe** [comment]
Again with your own collect overload, you should be able to do that.

I don't know by heart if you can assign custom variables to events for your counter. If not you can store it in a weak table

**Comment by axkibe** [comment]
I guess, I can close this now?
