### ISSUE TITLE
where  does the "--filter" should be configured?

### ISSUE THREAD

**Issue by cjw0202** [axkibe/lsyncd#510]

**Comment by cjw0202** [comment]
@saulzy Thanks a lot, and i know it ,use "_extra " can make it.

**Comment by axkibe** [comment]
_extra is the wrong way, listen to @saulzy, he was right.

**Comment by cjw0202** [comment]
@axkibe but it works .and my directory has many variety of files,i synchronize only one varitey of file.
so,i need to list all files?

**Comment by axkibe** [comment]
It creates a lot of unncessary load. Thats why use of _extra is discoruaged, since many people using it, don't know what they're doing.

As said, listen to @saulzy, he posted correct. Otherwise if it works for you, good for you, but for the record, as this issue keeps being archived, this is not the proper way.

**Comment by cjw0202** [comment]
why not add both "include" and "exclude"? @axkibe

**Comment by axkibe** [comment]
filter and filterFrom has been added to Lsyncd 2.2.3

**Comment by cjw0202** [comment]
but i don't known how to use it. can you give me an example? Thanks

**Comment by saulzy** [comment]
There is no filter and filterFrom in the manual. I also want to know how to use it.

**Comment by axkibe** [comment]
neither filter nor exclude are exclusive to default.rsyncssh mode. both work for default.rsync mode as well.

filter and filterFrom use the same syntax as rsync. You are right that I forgot to update the manual.You can see an usage example in the testsuite:
https://github.com/axkibe/lsyncd/blob/master/tests/filter-rsync.lua

Yes, with filter you don't need exclude anymore. It's a more powerful feature.

**Comment by cjw0202** [comment]
@axkibe Danke

**Comment by saulzy** [comment]
I recommend that the manual be international. I can try to translate it into Chinese. Although my English is poor.

**Comment by axkibe** [comment]
You're certainly welcome to that. However work is currently underway for Lsyncd 3 which also the manual will have some significant changes. So I suggest to wait a few weeks (or even months) and then translate the one for Lsyncd 3 right away.
