### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by wittyprince** [axkibe/lsyncd#512]
[wangchen@centos7 lsyncd-release-2.1.6]$ cmake .
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Lua: /usr/local/lib/liblua.a;/usr/lib64/libm.so (found version "") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wangchen/software/lsyncd-release-2.1.6
[wangchen@centos7 lsyncd-release-2.1.6]$ make
Scanning dependencies of target manpage
[ 10%] Built target manpage
[ 20%] Generating defaults.out
Compiling built-in default configs
[ 30%] Generating runner.out
Compiling built-in runner
[ 40%] Generating runner.c
Generating built-in runner linkable
[ 50%] Generating defaults.c
Generating built-in default configs
Scanning dependencies of target lsyncd
[ 60%] Building C object CMakeFiles/lsyncd.dir/lsyncd.c.o
[ 70%] Building C object CMakeFiles/lsyncd.dir/runner.c.o
[ 80%] Building C object CMakeFiles/lsyncd.dir/defaults.c.o
[ 90%] Building C object CMakeFiles/lsyncd.dir/inotify.c.o
[100%] Linking C executable lsyncd
CMakeFiles/lsyncd.dir/lsyncd.c.o: In function `l_exec':
lsyncd.c:(.text+0x1610): undefined reference to `lua_objlen'
lsyncd.c:(.text+0x1684): undefined reference to `lua_objlen'
CMakeFiles/lsyncd.dir/lsyncd.c.o: In function `register_lsyncd':
lsyncd.c:(.text+0x3054): undefined reference to `luaL_register'
CMakeFiles/lsyncd.dir/inotify.c.o: In function `register_inotify':
inotify.c:(.text+0x9f5): undefined reference to `luaL_register'
/usr/local/lib/liblua.a(loadlib.o): In function `lookforfunc':
loadlib.c:(.text+0x4c2): undefined reference to `dlsym'
loadlib.c:(.text+0x509): undefined reference to `dlerror'
loadlib.c:(.text+0x536): undefined reference to `dlopen'
loadlib.c:(.text+0x5ad): undefined reference to `dlerror'
/usr/local/lib/liblua.a(loadlib.o): In function `gctm':
loadlib.c:(.text+0x741): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
make[2]: *** [lsyncd] Error 1
make[1]: *** [CMakeFiles/lsyncd.dir/all] Error 2
make: *** [all] Error 2
[wangchen@centos7 lsyncd-release-2.1.6]$ lua -v
Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio
[wangchen@centos7 lsyncd-release-2.1.6]$ cmake --version
cmake version 3.11.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
[wangchen@centos7 lsyncd-release-2.1.6]$ rsync --version
rsync  version 3.1.3  protocol version 31
Copyright (C) 1996-2018 by Andrew Tridgell, Wayne Davison, and others.
Web site: http://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, hardlinks, symlinks, IPv6, batchfiles, inplace,
    append, no ACLs, xattrs, iconv, symtimes, prealloc

rsync comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
are welcome to redistribute it under certain conditions.  See the GNU
General Public Licence for details.
[wangchen@centos7 lsyncd-release-2.1.6]$

**Comment by axkibe** [comment]
Please use a newer version of Lsyncd instead of 2.1.6.

You are missing "-dl". I don't know why on a few systems this isn't default. If you google those error messages, you'll find how to fix it CFLAGS. It's not Lsyncd specific.

**Comment by wittyprince** [comment]
thank u, now i use lsyncd-2.2.2 and lua-5.1.4, cmake version 3.11.2, rsync version 3.1.3, and it works, but you said Requirements Lua >= 5.2 on page https://axkibe.github.io/lsyncd/manual/building/, is lua-5.1.4 OK?

**Comment by axkibe** [comment]
The manual refers to the latest version of Lsyncd which is 2.2.3

Lsyncd 2.2.2 was Lua 5.1 or Lua 5.2
Lsyncd 2.2.3 is Lua 5.2 or Lua 5.3

This is due it being difficult enough to support two Lua versions at the same time, 3 ist much harder.

**Comment by wittyprince** [comment]
OK, thank u very much.
