### ISSUE TITLE
Dynamically changing the synchronization targets?

### ISSUE THREAD

**Issue by xiaoerli520** [axkibe/lsyncd#515]
Can dynamically change the synchronization targets according to the dynamic IP list?
Such like we have an IP list stored in redis, I want to know lsyncd is able to read the dynamic IP list  and change targes dynamically? 
without reloading lsyncd is better because we have a lot of files to sync,and require file been synced in 2 secs.

**Comment by piyushcs** [comment]
You can write your own plugin, for inotify events, the code will be executed when file event is triggered. For more details see the examples. So you can specify your own function which will read ip list stored in redis and then call **rsync** **scp** etc. Using that you can do it, lsyncd directly doesn't support it.
