### ISSUE TITLE
syncd: [receiver] internal abbrev error on appdata_ocnudqtqmhau/preview/296742 (security.selinux, len=44)!

### ISSUE THREAD

**Issue by Githopp192** [axkibe/lsyncd#533]
IMG_xxxxx file has vanished: "/xxxxx/xxxx/cache/IMG_xxxxxx_193938.jpg-chunking-261435200-0.UQofQXVNQ1V2snAr.part"
lsyncd: [receiver] internal abbrev error on appdata_ocnudqtqmhau/preview/296742 (security.selinux, len=44)!
lsyncd: rsync error: protocol incompatibility (code 2) at xattrs.c(644) [receiver=3.1.2]
lsyncd: 21:21:58 Error: Failure (list): 2 
lsyncd: 21:21:59 Error: Critical exitcode.

Affectect version:

Name        : lsyncd
Arch        : x86_64
Version     : 2.2.2
Release     : 1.el7

centos-release-7-5.1804.1.el7.centos.x86_64

**Comment by axkibe** [comment]
looks like a rsync failure. Make sure to have the most recent stable rsync on both sides, see if it persists if it does, enable 'log=Execute' and report to rsync development

**Comment by Githopp192** [comment]
yes ..thx 4 your quick answer .. this might be true .. anyway .. configured a lsyncd-automatic restart script for that matters .. :-)

**Comment by Githopp192** [comment]
will close this ticket .. seems to be clear and fixed
