### ISSUE TITLE
lsyncd doesn't appear to work with 'sudo rsync'

### ISSUE THREAD

**Issue by djneely** [axkibe/lsyncd#547]
I've manually setup a script to rsync the data from one web server to another. However, came across lsyncd and wanted to give it a shot. It appears I'm not able to rsync across as another user and execute the 'sudo rsync' to therefor set perms/times accordingly. The config I have in place is:

> settings {
> 	logfile = "/var/log/lsyncd.log",
> 	statusFile = "/var/log/lsyncd-status.log"
> }
> 
> sync {
> 	default.rsync,
> 	insist,
> 	source = "/srv/site",
> 	target = "replicate@web-2:/srv/site",
> 	rsync = {
> 		archive = true,
> 		perms = true,
> 		owner = true,
> 		_extra = {"-a", "-e ssh", "--rsync-path='sudo rsync'"},
> 	}
> }

The logs are showing:

> ==> /var/log/lsyncd.log <==
> bash: sudo rsync: command not found
> rsync: connection unexpectedly closed (0 bytes received so far) [sender]
> rsync error: remote command not found (code 127) at io.c(235) [sender=3.1.2]

From the same machine I'm able to run the rsync script manually and works fine:

> rsync -avze ssh --rsync-path='sudo rsync' /srv/site  replicate@loadmax-web-2:/srv/

Is this an lsyncd issue or is my config just jacked up? I tried various other configs to slim it down and try to eliminate any items but ultimately same issue no matter what I seemed to try.

**Comment by djneely** [comment]
Inevitably after reporting this I stubbled across the solution. Aploogies for this. 

I removed the 'sudo rsync' from the _extra and saw the additional config option:

rsync_path = "sudo rsync"

And I'm all good now. Sorry about that and great product.

**Comment by shinnoch** [comment]
i'm having the same issue.

Where in the config file did you place rsync_path = "sudo rsync" ?

**Comment by derekneely** [comment]
@shinnoch here is a sample of one of my sync configs:

sync {
	default.rsync,
	insist,
	source = "/srv/dir_to_sync",
	target = "root@server2:/srv/dir_to_sync",
	rsync = {
		rsync_path = "sudo rsync",
		_extra = {"-a", "-e ssh"}
	}
}

**Comment by shinnoch** [comment]
@derekneely   Thank you for replying.  

It doesn't work for me and lsyncd doesn't start, if rsync-path option is omitted lsyncd starts without issues.

error in log: Normal: Retrying startup of /var/www/html/ -> 192.168.1.1:/var/www/html/: 12 

here's a sample of my config.  



sync    {
        default.rsync,
        delete = true,
        source = "/var/www/html/",
        target = "192.168.1.1:/var/www/html/",
        exclude  = { '*.tar', '*.tar.gz', },
rsync={ rsh ="/usr/bin/ssh -l user -i /home/user/.ssh/id_rsa  -o UserKnownHostsFile=/home/user/.ssh/known_hosts",
        compress = false,
        rsync-path = "sudo rsync",
        _extra   = { '--archive', '--delete', '--links', '--verbose' },
        }
}

**Comment by derekneely** [comment]
Maybe there is a difference in our versions? The config I provided is running on lsyncd 2.1.5.

**Comment by shinnoch** [comment]
@derekneely
> 
> 
> Maybe there is a difference in our versions? The config I provided is running on lsyncd 2.1.5.

Yep that might be it, i'm running on 2.2.2

I'll update if I'm able to resolve.   thanks again.

**Comment by DISMike** [comment]
Is there a way to do this in the latest version?
