### ISSUE TITLE
add delete to commandline option.  

### ISSUE THREAD

**Issue by vans163** [axkibe/lsyncd#557]
the delete flag is a very important one.  currently it can only be set in the config file, this does not allow a 1 liner to run lsyncd

```
lsyncd -nodaemon -insist -delay 0 --delete false -rsyncssh /local user@serv /remote
```

This is perfect for almost all use cases. Is it possible to add it as cmdline option or to -rsyncssh?

Also I think its a bad idea for ANY data deletions to happen by default.  I am familiar with rsync so I know it can make things go poof, i made a backup of my db in working folder, rsync local dir into working folder, db went poof :P.  Needed the no deletes option as I am syncing source code to a remote, and the remote end already has stuff like a db.

**Comment by axkibe** [comment]
Actually with the Lsyncd 3.0 rewrite I was planning to remove this kind of  command line parameterization all together. However allow stdin as alternative for a config file, so if you wanted you still could do a one liner.

Yes, delete by default was a bad idea, I fully agree to that. Also something that should be changed with 3.0, if I get a motivation push to finish that rewrite.

**Comment by vans163** [comment]
Like I would have no problem with the config file, but for some reason it was not reading from /dev/fd/63 :(.  Like via a tempfd, i was starting 
```
lsyncd <(echo {...})
error: /dev/fd/63 not found
```

But it works for others like
```
cat <(echo "hello")
hello
```
And cool good to know a rewrite is in the works.  So far I compiled it myself and changed the delete = true, to a false, and it fills all my needs. Maybe slightly faster sync (even with delay 0) is all id want, it still seems to take 1-2 seconds, even tho my server is 30ms away.

**Comment by axkibe** [comment]
Yes config file as stdin doesn't work with lsyncd 2.x... I added code for it for 3.0
