### ISSUE TITLE
Critical rsyncssh failure 

### ISSUE THREAD

**Issue by eldok2** [axkibe/lsyncd#564]
lsyncd fails after some runs, unexpectedly. Files are copied, and rsync's works fine. 

```
settings {
   logfile = "/var/log/lsyncd/lsyncd.log",
   statusFile = "/var/log/lsyncd/lsyncd-status.log",
   statusInterval = 5,
   insist = true
}
servers = {
 "server1",
}

for _, server in ipairs(servers) do
sync {
    default.rsyncssh,
    source="/home/folder/",
    host=server,
    targetdir="/home/folder/",
    excludeFrom="/etc/lsyncd/lsyncd-excludes.txt",
    rsync = {
        archive = true,
        hard_links = true,
        verbose = true,
        rsh = "/usr/bin/ssh -p 22 -o StrictHostKeyChecking=no -E /var/log/lsyncd/lsyncd-ssh.log -vv"
    },
    exitcodes = {
            _verbatim = true,
            [2] = 'again'
    }
}
end
```

In the log, after transmitting all the files I can see the following

```
Invalid packet at end of run (16340) [sender]
rsync error: protocol incompatibility (code 2) at main.c(789) [sender=3.1.0]
Wed Jun 26 12:39:15 2019 Error: Failure (list): 2
Wed Jun 26 12:39:15 2019 Error: Critical exitcode.
```

Nothing that can add in the ssh log.

Source is an Ubuntu 14 with rsync 3.1.0 and lsyncd 2.1.5
Destination is an Ubuntu 18 with rsync 3.1.2

**Comment by axkibe** [comment]
This is almost certainty a rsync not lsyncd problem. I suggest bringing rsync on source and target uptodate.

**Comment by eldok2** [comment]
@axkibe thanks for your reply. And thanks for your work.
The protocol version for both is the exact same one, and this shouldn't be an issue, but I'll do that. At least I'll make them match rsync versions. 

Either way, why is it not retrying when I'm explicitly telling that the errorcode 2 should be retried? Am I misplacing something or missing something?

**Comment by axkibe** [comment]
with rsyncssh you have rsyncExitCodes and sshExitCodes, as this are different programs it uses.

**Comment by eldok2** [comment]
Thanks @axkibe , will adjust that and try changing rsync version and/or forcing the protocol version just in case.
