### ISSUE TITLE
lsyncd fails to start 

### ISSUE THREAD

**Issue by rtwk** [axkibe/lsyncd#572]
I have lsyncd verison 2.1.6 working perfectly on one machine. settings option looks like this : 

settings = {
        logfile = "/var/log/lsyncd/lsyncd.log",
        statusFile = "/var/log/lsyncd/lsyncd.status",
	statusIntervall = 1,
	nodaemon = false
}

On another, machine, with verions 2.2.3-1, this does not work asking to remove = sign from settings. Even after it is removed, it fails to start. 
Please help to fix the issue.

**Comment by Rajkumar-Unix** [comment]
Use settings as mentioned below.

settings {
        logfile = "/var/log/lsyncd.log",
        statusFile = "/var/log/lsyncd.stat",
        statusInterval = 1,
        insist = true,
}

**Comment by axkibe** [comment]
"Even after it is removed, it fails to start."

Would be useful to say why it doesn't want to start. Reopen if you have more infos, thx.
