### ISSUE TITLE
Unknown --usermap name on receiver: oracle

### ISSUE THREAD

**Issue by cdshrewd** [axkibe/lsyncd#574]
I use lsyncd+rsync to sync files from linux 6.8 to linux 7.4. I want to change user and group for target.My lsyncd version is 2.2.3.My rsync version is 3.1.3.But it gives the following errors. 
18:55:16 Normal: --- Startup ---
18:55:16 Normal: recursive startup rsync: /app/source/ -> 192.168.2.7::target/
sending incremental file list
Unknown --usermap name on receiver: oracle
Unknown --groupmap name on receiver: dba

The  configuration:
lsyncd.conf
[root@test6 source]# cat /etc/lsyncd.conf 
settings {
    logfile ="/var/log/lsyncd.log",
    statusFile = "/tmp/lsyncd.status",
    inotifyMode="CloseWrite",
    maxProcesses=16,
    statusInterval = 10,
    nodaemon   = true,
}
sync {
    default.rsync,
    source="/app/source",
    target="192.168.2.7::target",
    delay=1,
    maxProcesses=1,
    rsync = {
     binary = "/usr/local/bin/rsync",
     archive = true,
     compress = true,
     verbose = true,
     owner=true, 
     group = true, 
     perms = true, 
     chown="oracle:dba",
    rsh="/usr/bin/ssh -p 10022 -o StrictHostKeyChecking=no"
   }
}
[root@test6 source]# 

rsyncd.conf

uid =  root
gid = root
max connections=2
log file=/var/log/rsyncd/rsyncd.log
pid file=/var/run/rsyncd.pid
lock file=/var/run/rsyncd.lock
[target]
path = /app/target
read only = no
list = yes

**Comment by axkibe** [comment]
This is not a Lsyncd issue, but a rsync settings issue. You're forcing a user/group id thats not available on the target.

**Comment by cdshrewd** [comment]
> This is not a Lsyncd issue, but a rsync settings issue. You're forcing a user/group id thats not available on the target.

But I am sure that user 'oracle' in group 'dba' exists on the target.
The following is the check output:
[root@cspxfz ~]# id oracle
uid=54321(oracle) gid=1000(oinstall) groups=1000(oinstall),54322(dba),54323(oper),54324(backupdba),54325(dgdba),54326(kmdba),54327(asmdba),54330(racdba)
[root@cspxfz ~]#
