### ISSUE TITLE
Excluded directories are monitored and synced

### ISSUE THREAD

**Issue by Sherlock1979** [axkibe/lsyncd#575]
Hi,

I seem to have some issue with the exclude option. Can you please help me understand if my configuration was incorrect or if it was a bug. Thank you.

Version info: Ubuntu 18.04, lsyncd 2.1.6-1 (installed from ubuntu repository with apt).

Below are some relevant snippets from my lsyncd.status file. For instance please look at how some files from /tmp are still in the delays list and also how the /tmp folder is being watched by lsyncd inotify. I have removed irrelevant parts and pieces with potentially sensitive information (e.g. directory names with usernames) but happy to provide full config, log, and status files in private.

As a side-note, in my config the sync source is defined as "/" however in the status file I see // and also the inotify watch list starts with // (see below). I am not sure if it is related or if I need to fix it somehow.

    Lsyncd status report at Fri Sep 20 08:45:22 2019

    Sync1 source=//
    There are 1354 delays
    active Init 
    ...
    block  Modify /tmp/#30945261
    block  Modify /tmp/#30945020
    block  Modify /tmp/#30943097
    ...
    Excluding:
    ...
    **/Tmp/*
    *.tmp
    **/TMP/*
    **/tmp/**
    **/temp/**
    ...
    Inotify watching 296660 directories
    ...
      295979: //tmp/
      295980: //tmp/snap.canonical-livepatch_cZgCsE/
    ...
      295983: //tmp/snap.canonical-livepatch/
    ...
      295992: //tmp/snap.0_canonical-livepatch_kxQYR2/
      295993: //tmp/.X11-unix/
      295994: //tmp/.XIM-unix/
      295995: //tmp/.font-unix/
      295996: //tmp/.Test-unix/
    ...
      295998: //tmp/snap.canonical-livepatch_VsRM3o/
      295999: //tmp/.ICE-unix/
    ...
      296001: //tmp/hsperfdata_root/
    ...

Thanks,
David

**Comment by axkibe** [comment]
Please use Lsyncd 2.2.3 and reopen the bug if it still persits. I'm sorry but I won't bother with old versions. The updates had a reason.
