### ISSUE TITLE
move operation not working

### ISSUE THREAD

**Issue by kuznetcoff777** [axkibe/lsyncd#576]
I have 2 servers.
Two disks on each of them sda (/storage) and sdb (/storage-archive)
Sda and sdb on each server must be synced.

I have such config on main server:

```
settings {
    logfile = "/var/log/lsyncd.log",
    statusFile = "/var/log/lsyncd-status.log",
    statusInterval = 1,
    insist = 1
}

sync {
   default.rsyncssh,
   source="/storage",
   host="server-2",
   targetdir="/storage",
   exclude={ "/input-temp/*", ".*", "*.tmp" },
   delete = 'running',
   rsync = {
     archive = true,
     compress = false,
     whole_file = false,
   },
   ssh = {
     port = 22
   }
}

```

Just one folder is syncing. Also i made /storage/archive folder (for it will be under one /storage location) and bind it to sdb in fstab
/storage-archive                   /storage/archive none    bind    0 0

I have a script which moves files from /storage  to /storage/archive when reach 90% of sda capacity and another script that vanish old files from /storage-archive when reach 90% of sdb capacity.

When move operaion happens on main server, lsync does not repeat it. For example, i move file test.txt from /storage to /storage/archive/ (from sda to sdb). So on slave server it just syncs file /storage/archive/test.txt instead of to repeat operation move /storage/test.txt to /storage/archive/test.txt

So it makes additional sync operations which leads to not necessary disk/net operations.

How can i resolve it?

**Comment by axkibe** [comment]
Please use the most recent version of Lsyncd. Reopen this bug if this still happens with 2.2.3
