### ISSUE TITLE
Bug in move operation

### ISSUE THREAD

**Issue by kuznetcoff777** [axkibe/lsyncd#577]
Checked it on latest version
/usr/local/bin/lsyncd  -version
Version: 2.2.3

I have 2 servers.
Two disks on each of them:
fast ssd - sda (/storage) 
and 
slow hdd - sdb (/storage-archive)

Sda and sdb on each server must be synced.

I have such config on main server:

```
settings {
    logfile = "/var/log/lsyncd.log",
    statusFile = "/var/log/lsyncd-status.log",
    statusInterval = 1,
    insist = 1
}

sync {
   default.rsyncssh,
   source="/storage",
   host="server-2",
   targetdir="/storage",
   exclude={ "/input-temp/*", ".*", "*.tmp" },
   delete = 'running',
   rsync = {
     archive = true,
     compress = false,
     whole_file = false,
   },
   ssh = {
     port = 22
   }
}

```

Just one folder is syncing. Also i made /storage/archive folder (for it will be under one /storage location) and bind it to sdb in fstab
/storage-archive                   /storage/archive none    bind    0 0

I have a script which moves files from /storage  to /storage/archive when reach 90% of sda capacity and another script that vanish old files from /storage-archive when reach 90% of sdb capacity.

When move operaion happens on main server, lsync does not repeat it. For example, i move file test.txt from /storage to /storage/archive/ (from sda to sdb). So on slave server it just syncs file /storage/archive/test.txt instead of to repeat operation move /storage/test.txt to /storage/archive/test.txt. And also leaves /storage/test.txt on slave server, even on master it is absent.

So it makes additional sync operations which leads to not necessary disk/net operations.

How can i resolve it?

P.s. Is there any way to add in logs name of file transfering and progress of it, becase sometimes it is not so informative, as it could be...

**Comment by axkibe** [comment]
> When move operaion happens on main server, lsync does not repeat it. For example, i move file test.txt from /storage to /storage/archive/ (from sda to sdb). So on slave server it just syncs file /storage/archive/test.txt instead of to repeat operation move /storage/test.txt to /storage/archive/test.txt. And also leaves /storage/test.txt on slave server, even on master it is absent.

Can you please rewrite this, I don't quite understand what the issue is. What do you expect and what is happening instead?

If you move a file from one file system to another, I wouldn't be surprised if Lsyncd doesn't recognize it a move, put transfers the file using normal rsync. This is mainly due to limitation of the inotify event system mechanism.

You get way more logs if you start Lsyncd with "-log all" option. Also for testing things out nodaemon = true maybe useful.

**Comment by kuznetcoff777** [comment]
"If you move a file from one file system to another, I wouldn't be surprised if Lsyncd doesn't recognize it a move, put transfers the file using normal rsync. This is mainly due to limitation of the inotify event system mechanism." - i think this is the case.

Yes, i move files from one file system to another and i wanted for les sync operations happen after such move operations.

**Comment by kuznetcoff777** [comment]
And one more thing about move.
A launched with -log all.
and do:
mv /storage/input/test.txt to /storage/input/test-2.txt 

In logs i see (grep by name of file):

Thu Sep 26 14:56:06 2019 Inotify: got event Move test.txt(60404) to test-2.txt(60404)
Thu Sep 26 14:56:06 2019 Function: delay( Sync1, Move, /input/test.txt, /input/test-2.txt )
Thu Sep 26 14:56:06 2019 Delay: New Move: /input/test.txt -> /input/test-2.txt
Thu Sep 26 14:56:21 2019 Normal: Moving input/test.txt -> input/test-2.txt
Thu Sep 26 14:56:21 2019 Exec: /usr/bin/ssh [-p] [22] [192.168.255.254] [mv] ['/storage/test.txt'] ['/storage/test-2.txt'] [||] [rm] [-rf] ['/storage/test.txt']
Thu Sep 26 14:56:21 2019 Normal: Finished Move /storage//input/test.txt: 0
Thu Sep 26 14:56:21 2019 Delay: Finish of Move on /storage//input/test.txt = 0


So everything worked normally, on remote storage move operation happened.

But when i turn off lsync, do the same move operation, turn on lsync (delete=true)
And files are now look like this:
server-main have file /storage/input/test-2.txt 
server-slave have files /storage/input/test.txt and /storage/input/test-2.txt 

 In logs i see nothing by the name of file (grep by name of file). Strange behaviour. I mean why /storage/input/test.txt was not deleted on remote host?

**Comment by axkibe** [comment]
works for me, I doubt you had delete=true configured correctly/restarted properly or made some other error.

**Comment by kuznetcoff777** [comment]
```
sync {
   default.rsyncssh,
   source="/storage",
   host="server-2",
   targetdir="/storage",
   exclude={ "/input-temp/*", ".*", "*.tmp" },
--   delete = 'running',
   delete = 'true',
   rsync = {
     archive = true,
     compress = false,
     whole_file = false,
--     bwlimit = 10000
   },
   ssh = {
     port = 22
   }
}
```
