### ISSUE TITLE
start message in log reports exclusions in non-deterministic order

### ISSUE THREAD

**Issue by svenha** [axkibe/lsyncd#579]
Some of my logs from lsyncd 2.2.2 are confusing because the order of directories changes:

    Wed Oct  9 11:37:34 2019 Normal: --- Startup, daemonizing ---
    Wed Oct  9 11:38:07 2019 Normal: recursive startup rsync: /data4/ -> /data4m/ excluding
    tmp/
    lost+found/

And after a restart (e.g. from an OVERFLOW event), the order might be reversed.

**Comment by axkibe** [comment]
Thats the way it is. The order is not deterministic, but shouldn't matter.

**Comment by svenha** [comment]
Yes, it is only a minor problem. For humans and log tools, it is a more complicated to check for certain patterns in logs.

**Comment by axkibe** [comment]
Yes in future I plan to add an option to do this. If humans and log tools are not needed, it's just a waste of CPU to sort it tough.
