### ISSUE TITLE
*suggest* mention path of lsyncd.conf.lua

### ISSUE THREAD

**Issue by felixlberg** [axkibe/lsyncd#584]
Its sad that in NO way it is documented that the config is under '/etc/lsyncd/lsyncd.conf.lua'. Not here on github and not on the official documentation. This makes it extreme frustrating to see all these options in documentation but not having a possibility to change them without further research on other websites or searches.

**Comment by axkibe** [comment]
Because it's nowhere coded that way in Lsyncd, I suppose this due to the service file of your distrubution that puts it there?

**Comment by felixlberg** [comment]
Ah ok thx of the info..
