### ISSUE TITLE
Only sync when launch after upgrade to 10.15.1 

### ISSUE THREAD

**Issue by erichuang1994** [axkibe/lsyncd#587]

**Comment by nikbrain** [comment]
have the same problem

**Comment by motoronik** [comment]
I have too this problem. Files are synchronized once, after running lsyncd. 
I think the problem with inotify, because in the logs I see it.

**Log file: lsyncd.log**
_____
Wed Dec 18 15:01:43 2019 Normal: --- Startup, daemonizing ---
Wed Dec 18 15:01:43 2019 Normal: recursive startup rsync: PATH_TO_PROJECT_1 -> PATH_TO_REMOTE_MACHINE
.idea
.git
Wed Dec 18 15:01:44 2019 Normal: Startup of "/Users/r.nikolin/Projects/billing/" finished: 0
_____

**Log file: lsyncd.status**
_____
Lsyncd status report at Wed Dec 18 14:59:07 2019

Sync1 source=PATH_TO_PROJECT_1
There are 0 delays
Filtering:
  nothing.

Inotify watching 0 directories
_____

**Comment by stygiansabyss** [comment]
I have been seeing the same thing.  I am using ssh to handle this, but i see the same thing in the status log with nothing being watched.  I have yet to find anything that has made any change whatsoever.

**Comment by AleksShirokov** [comment]
Have the same problem as well right after updating to 10.15.3 (Catalina). 

Tried a bunch of things including giving rsync , lsyncd access to File System, removing all filtering options, changing target directories. Nothing worked

**Comment by lightAfire** [comment]
has the same problem

**Comment by axkibe** [comment]
Honestly I dropped OSX support for quite a while now. Sorry. If someone wants to do this, he or she has to fork this project.

**Comment by stef1205** [comment]
I noticed that 10.15.3 is adding "/System/Volumes/Data" as prefix to the path returned by fsevents.

So this issue can be fixed by removing this prefix in fsevents.c / handle_event

Works fine in 10.15 after that

**Comment by danieljl** [comment]
Hi @stef1205, can you share the changes you made?

**Comment by stef1205** [comment]
Sure, here you go.

There might other things I was testing but look for the two strncmp lines that test if the path starts with "/System/Volumes/Data”

SK

**Comment by DylanFouche** [comment]
Hey @stef1205 (or @danieljl ) could you please make these changes public? I am facing the same issue as I'm sure many people are. Alternatively, if you share your changes with me, I'd be happy to open a pull request.

**Comment by DylanFouche** [comment]
Note: I managed to resolve this issue on 10.15.6 without touching source code by simply prepending "/System/Volumes/Data/" to the source path defined in my config file.

**Comment by stef1205** [comment]
Hello Dylan,

My solution was to get rid of "/System/Volumes/Data" in fsevents.c:

	if (etype) {
		if (!path) {
			printlogf(L, "Error", "Internal fail, fsevents, no path.");
			exit(-1);
		}
		if (isdir < 0) {
			printlogf(L, "Error", "Internal fail, fsevents, neither dir nor file.");
			exit(-1);
		}
		load_runner_func(L, "fsEventsEvent");
		lua_pushstring(L, etype);
		lua_pushboolean(L, isdir);
		l_now(L);
		if (!strncmp( path, "/System/Volumes/Data", 20)) {
			path += 20;
		}
		lua_pushstring(L, path);
		if (trg) {
			if ( !strncmp( trg, "/System/Volumes/Data", 20 )) {
				trg += 20;
			}
			lua_pushstring(L, trg);
		} else {
			lua_pushnil(L);
		}

   	 	if (lua_pcall(L, 5, 0, -7)) {
			exit(-1); // ERRNO
		}
		lua_pop(L, 1);
	}
}
