### ISSUE TITLE
Lsyncd 2.2.2 ownership and permission issue

### ISSUE THREAD

**Issue by mostyn-grp** [axkibe/lsyncd#588]
I'm having an issue where files are been copied to the remote server except the owner/group of replicated files on the target server is always '1002'. The permissions of the source are respected and replicated correctly on the target. I just can't figure out a way to preserve the owner (and group) of the replicated files.

Lsyncd Version: 2.2.2

my setting below:

```
settings {
    logfile = "/var/log/lsyncd/lsyncd.log",
    statusFile = "/var/log/lsyncd/lsyncd.status"
}

sync {
    default.rsyncssh,
    source="/home",
    host="1*52.*.15",
    targetdir="/home/",
    delete = "running", -- prevents deletion of files on startup (ie when a server comes back online, don't delete files that are new on the backup)
    delay = 5, -- run every 5 seconds instead of default 20
    exclude = {
        "/home/backup",
    },
    rsync = {
        archive = true, -- use the archive flag in rsync
        perms = true, -- Keep the permissions
        owner = true, -- Keep the owner
        compress = true,
        acls = true,
            xattrs = true,
        _extra = {"-a"}, -- Sometimes permissions and owners isn't copied correctly so the _extra can be used for any flag in rsync
    }
}
```

lsyncd log error:

```
Dec 15 21:42:47 server1.*.group lsyncd[21033]: sending incremental file list
Dec 15 21:42:47 server1.*.group lsyncd[21033]: rsync: failed to set times on "/home/admin/conf": Operation not permitted (1)
Dec 15 21:42:47 server1.*.group lsyncd[21033]: admin/conf/
Dec 15 21:42:47 server1.*.group lsyncd[21033]: sent 5,387 bytes  received 160 bytes  3,698.00 bytes/sec
Dec 15 21:42:47 server1.*.group lsyncd[21033]: total size is 2,849,404,839  speedup is 513,683.94
Dec 15 21:42:47 server1.*.group lsyncd[21033]: rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1178) [sender=3.1.2]
```

**Comment by axkibe** [comment]
You need to be root at the target to change ownership of files, this is not a lsyncd issue.
Also don't use _extra, especially not with -a. Thats exactly the reason why the manual says you shouldn't be using it, if you don't know exactly what you're doing.

**Comment by mostyn-grp** [comment]
@axkibe thank you for your reply.

I have tried without `_extra -a` the result was always same, lsyncd on both servers is run under root.

**Comment by axkibe** [comment]
What you mean with "lsyncd on both servers is run" Are you using a master-master setup? Lsyncd should only be running on master and use rsync/ssh to connect to the slave. master-master setups are not supported, and you should be using something else if you want to.
Anyway, I'm sure this is not a Lsyncd issue, as you can see in the line:
Dec 15 21:42:47 server1.*.group lsyncd[21033]: rsync: failed to set times on "/home/admin/conf": Operation not permitted (1)
