### ISSUE TITLE
lsyncd is terminated after running for a while.

### ISSUE THREAD

**Issue by Crispy13** [axkibe/lsyncd#591]
command: 
lsyncd -nodaemon -rsyncssh ./ "id"@"ipaddress" /data/backup/

- no password required to login via ssh. (predefined key?)

printed messages:
...
12:56:33 Normal: Moving /Example_on_BRATS2018_SNUBH_T1CE-Copy3.ipynb -> /200113.ipynb
12:56:33 Error: in Lua: default-rsyncssh.lua:92: attempt to call local 'path2' (a string value)
12:56:33 Error: Backtrace 1 :default-rsyncssh.lua:92
12:56:33 Error: Backtrace 2 :lsyncd.lua:1960
12:56:33 Error: Backtrace 3 :lsyncd.lua:3511

How could i prevent this error from raising?

**Comment by axkibe** [comment]
Which Lsyncd version?

**Comment by Crispy13** [comment]
lsyncd's version is 2.1.5
Ubuntu's version is 16.04.

**Comment by axkibe** [comment]
Please update to 2.2.3 and reopen if the problem presists.

**Comment by Crispy13** [comment]
It seems that Ubuntu 16.04 has the version of 2.1.5 lsyncd only in their repository.
"sudo apt get install lsyncd" only installs 2.1.5 lsyncd, not 2.2.3

**Comment by axkibe** [comment]
This is something you should ask the Ubuntu community about.
Lsyncd upstream has a cmake, where you can locally install it, if you want to put it in a package instead, this is an issue if your distro.

**Comment by Crispy13** [comment]
> This is something you should ask the Ubuntu community about.
> Lsyncd upstream has a cmake, where you can locally install it, if you want to put it in a package instead, this is an issue of your distro.

Thank you axkibe.
