### ISSUE TITLE
sync when files are removed on destination

### ISSUE THREAD

**Issue by jostra** [axkibe/lsyncd#593]
How to configure lsyncd to sync file back from source server (re-transfer) if they are removed on destination server?
It only sync file back if lsyncd is restarted. 
I'm using  lsyncd-2.2.2-1.el7 on rhel 7.7

Thanks

**Comment by axkibe** [comment]
Yes restart Lsyncd. Otherwise Lsyncd has no way of knowing what you'd remove on the target server.

**Comment by jostra** [comment]
So, there is no external tracking mechanism?

**Comment by axkibe** [comment]
What do you mean with external?
Lsyncd is a software designed to track a local source data tree and keep a remote one in sync.

**Comment by jostra** [comment]
I thought some external script to track changes on remote server?

**Comment by axkibe** [comment]
This is not what Lsyncd is designed for.

**Comment by jostra** [comment]
OK. Do you have any plan in future to track  changes on remote server?

**Comment by axkibe** [comment]
No, because it's not in the design goals.

**Comment by jostra** [comment]
ok thanks. Do you now for any other solution that can manage this situation?

**Comment by axkibe** [comment]
Run rsync as a cron job?

**Comment by jostra** [comment]
ok thanks. Have a nice day.
