### ISSUE TITLE
Can't make rsync filter xattrs

### ISSUE THREAD

**Issue by ashak** [axkibe/lsyncd#603]
I'm trying to work out how I can use lsyncd to sync some files with extended attributes to some cephfs (which has its own extended attributes that I shouldn't touch).

Rsync docs say:
> To prevent any attributes from being deleted, you could specify a receiver-only rule that excludes all names:
>                   --filter='-xr *'

I tested a slightly tweaked version of their example in an attempt to just apply to xattrs starting with ceph and it seems to work as expected if I run rsync on the command line. But I can't seem to work out how to make it work via lsyncd

Since lsyncd supports filters it seemed like a config that was something like this would work:
```
settings {
    nodaemon = true,
}
sync {
    default.rsync,
    source    = "/mnt/local",
    target    = "/mnt/backup",
    rsync     = {
      acls       = true,
      archive    = true,
      hard_links = true,
      xattrs     = true,
      verbose    = true,
    },
    filter     = {
      '-xr ceph.*',
    },
}
```
However it doesn't seem to work, I still get errors in my output that suggests rsync is trying to remove the ceph xattrs

```
06:47:43 Normal: --- Startup ---
06:47:43 Normal: recursive startup rsync: /mnt/local/ -> /mnt/backup/ filtering
- xr ceph.*
sending incremental file list
./
rsync: rsync_xal_set: lremovexattr("/mnt/backup/.","ceph.dir.entries") failed: Operation not supported (95)
rsync: rsync_xal_set: lremovexattr("/mnt/backup/.","ceph.dir.files") failed: Operation not supported (95)
```

I enabled some logging by adding -log Exec to my command line args and it tells me the rsync command is this:

`06:48:18 Exec: /usr/bin/rsync [<] [- xr ceph.*] [--filter=. -] [--delete] [--ignore-errors] [-XgHvtpsolAD] [-r] [/mnt/local/] [/mnt/backup/]`

I don't totally understand what that's doing (although i'm guessing something with stdin?) so I can't easily test whether that works by running the same command directly.

In both outputs there's a space between the '-' and the 'xr'. Which doesn't seem right? But that's mostly me clutching at straws since I think everything is correct.

I even tried specifying my own --filter using the _extra in the rsync section of the config, like this:
```
          _extra     = {
            "--filter='-xr ceph.*'",
          }
```

But that gives me a different error:

> 07:07:19 Normal: --- Startup ---
> 07:07:19 Normal: recursive startup rsync: /mnt/local/ -> /mnt/backup/
> Unknown filter rule: `'-xr ceph.*''
> rsync error: syntax or usage error (code 1) at exclude.c(927) [client=3.1.3]
> 07:07:19 Error: Failure on startup of /mnt/local/ -> /mnt/backup/.

Which is a bit odd since --filter='-xr ceph.*' works fine on the command line. But rsync here seems to be complaining about it

I'm out of ideas now

**Comment by ashak** [comment]
I've been trying to understand what the parts of the rsync command that are executed are and I believe the existence of the space that's added between the - and the xr in my filter is what's causing the problem. The parts i'm lookig at from above are:

`[- xr ceph.*] [--filter=. -]`

--filter=.  is 'specifies a merge-file to read for more rules.' It seems that it would expect to take a file as an argument. Since here '-' is specified instead of an actual file presumably it will read from stdin. Therefore I guess it's then taking the previous part as stdin? Which means it will get '- xr ceph.*' on stdin?

I can test that easily...
```
echo "- xr ceph.*" | /usr/bin/rsync --delete -XgHvtpsolAD -r /mnt/local/ /mnt/backup/ --filter='. -'
rsync: rsync_xal_set: lremovexattr("/mnt/backup/path/to/dir","ceph.dir.rctime") failed: Operation not supported (95)
```
Which is the problem that I see. If I echo that option without the space (exactly like I would specify on the command line) :
```
echo "-xr ceph.*" | /usr/bin/rsync --delete -XgHvtpsolAD -r /mnt/local/ /mnt/backup/ --filter='. -'
path/to/dir
```
It works as I expect

My guess is that lsyncd is parsing the filter rules passed into it and then mangling them making some assumption that it will always be dash space or plus space. After reading the FILTER RULES section of the rsync docs I could understand why that might be. It uses those terms almost exactly when talking about how --include and --exclude are treated.

However, there's a section further down that says:

> The following modifiers are accepted after a "+" or "-":
> ---- 8< SNIP >8 ----
> o      An  x  indicates that a rule affects xattr names in xattr copy/delete operations (and is thus ignored when matching file/dir names).  If no xattr-matching rules are specified, a
>               default xattr filtering rule is used (see the --xattrs option).

Which is obviously what i'm trying to do.

**Comment by axkibe** [comment]
>
>
> My guess is that lsyncd is parsing the filter rules passed into it and
> then mangling them making some assumption that it will always be dash space
> or plus space. After reading the FILTER RULES section of the rsync docs I
> could understand why that might be. It uses those terms almost exactly when
> talking about how --include and --exclude are treated.
>
However, there's a section further down that says:
>
> The following modifiers are accepted after a "+" or "-":
> ---- 8< SNIP >8 ----
> o An x indicates that a rule affects xattr names in xattr copy/delete
> operations (and is thus ignored when matching file/dir names). If no
> xattr-matching rules are specified, a
> default xattr filtering rule is used (see the --xattrs option).
>
> Which is obviously what i'm trying to do.
>
Exactly that's not supported.  Lsyncd is not a "thin layer between inotify
and rsync" as some people believe, where all the rsync commands work nicely
through it, it's quite a bunch of mechanics to make these things work
together. It interprets the contents of the filter rules to also track
watches. The 'x' rule isn't implemented.

The real error I see is that the "filter" option is not described in the
manual.

- Axel

**Comment by ashak** [comment]
Could support for the 'x' rule be implemented? As in, is it possible or are there reasons why it couldn't be supported?

**Comment by axkibe** [comment]
I don't know, so far I can say it has not even been attempted.

**Comment by ashak** [comment]
It seems that using _extra can work.

On the command line I would need to quote the argument to the --filter option. However lsyncd is passing arguments to rsync doesn't seem to require the quotes, actually those quotes were the thing causing the error I mentioned above.

Without the quotes I no longer get the errors

```
_extra     = {
  "--filter=-xr ceph.*",
}
```

This seems to work well enough for me and it means that I don't need to learn lua
