### ISSUE TITLE
Tried to sync new files from remote to local, but lsyncd erased all my new files from the remote server and replaced them with 2 month old files..

### ISSUE THREAD

**Issue by breakone9r** [axkibe/lsyncd#616]
This destroy 2 months of work. Thanks.

Generally when you sync files, you want the NEWEST COPIES. Not the OLDEST COPIES. But this idiotic program decides my directory of files that hadn't been touched since august 8th was newer than the files and directories modified TODAY.

Good work there, boyo.

**Comment by axkibe** [comment]
Sorry for your work, but Lsyncd is unidirectional by design and says so clearly in the documentation several times.

**Comment by breakone9r** [comment]
then that's just copying. not synchronization.

**Comment by yoanisgil** [comment]
> This destroy 2 months of work. Thanks.
> 
> Generally when you sync files, you want the NEWEST COPIES. Not the OLDEST COPIES. But this idiotic program decides my directory of files that hadn't been touched since august 8th was newer than the files and directories modified TODAY.
> 
> Good work there, boyo.

RTFM :)
