### ISSUE TITLE
rsync.ssh not updating "updated" files on remote server

### ISSUE THREAD

**Issue by 4X5IQ** [axkibe/lsyncd#617]
**Hey All
I'm using lsyncd --version Version: 2.2.3 to copy log files from raspberry pi to AWS EC2 server
(The log files are GPS nmea files which are being update constantly)

On my local r pi the config file looks like:** 

settings {
        logfile = "/var/log/lsyncd/lsyncd.log",
        statusFile = "/var/log/lsyncd/lsyncd.status",
	statusInterval = 20,
	nodaemon   = false,	
}
sync {
	default.rsyncssh, 
	source = "/GPSLog/Script/data", 
	host = "ubuntu@x.x.x.x", 
	targetdir = "/GPSLogger01",
	delay = 10,
	rsync = {
     		archive = true,
     		compress = false,
     		whole_file = fale,
		update = true,
		append = true,
		temp_dir = "/tmp",
		times = fale,
		links = false,
        	owner = false,
        	perms = false,
        	verbose = true,
		acls = false,
		_extra = { "--omit-dir-times", "--ignore-times" , "--checksum", },
   	},
   	ssh = {
     		port = 22,
		identityFile = "/GPSLog/identityFile/xxx.pem",
	},
}

**when starting the demon "sudo systemctl start lsyncd"

It will only run once 

log file looks like:**

tail -f  /var/log/lsyncd/lsyncd.log
Thu Oct  1 23:06:35 2020 Normal: --- TERM signal, fading ---
Thu Oct  1 23:06:35 2020 Normal: --- Startup, daemonizing ---
Thu Oct  1 23:06:35 2020 Normal: recursive startup rsync: /GPSLog/Script/data/ -> ubuntu@x.x.x.x:/GPSLogger01/
sending incremental file list
data.20201001Oct101601586599.nmea
data.20201001Oct101601589565.nmea

sent 772,911 bytes  received 54 bytes  140,539.09 bytes/sec
total size is 41,879,927  speedup is 54.18
Thu Oct  1 23:06:40 2020 Normal: Startup of "/GPSLog/Script/data/" finished: 0

It will update the files on the server and will not run again 
(unless I will create or delete a file in the local directory)

I really do not understand what I'm missing

any help will be highly appreciated !!!!

Thanks ahead and best wishes

Roy

**Comment by axkibe** [comment]
Lsyncd is likely not receiving any inotify notifications from the linux kernel.

Possible reasons:
* whatever writes the files doesn't close them, but keeps them open (default Lsyncd behavior is to sync on closeWrite)
* the specified source directory is a network part or other file system that doesn't support notify events.
* the writes don't happen on these file, but hard linked files.

**Comment by axkibe** [comment]
PS: in case it is the first, try to change inotifyMode to 'modify'.

https://axkibe.github.io/lsyncd/manual/config/file/

**Comment by 4X5IQ** [comment]
Perfect !!!
Thank you Mr axkibe!!!  inotifyMode to 'modify'. did the trick 👍
