### ISSUE TITLE
sync interval

### ISSUE THREAD

**Issue by perfecto25** [axkibe/lsyncd#634]
Hello, Im using lsyncd 2.2.2

I have it running and syncing between 2 servers, I noticed it syncs around every 12 seconds, so if Im syncing server A > server B

it checks for changes around every 12sec

Is there a config value that controls this interval? Dont see anything in docs, I want to check every 3 or 4 seconds.

thank you.

**Comment by svenha** [comment]
It is the option `-delay`, see output of `lsyncd --help`.

**Comment by perfecto25** [comment]
thank you, this works.
