### ISSUE TITLE
Lsyncd failed to delete at destination server

### ISSUE THREAD

**Issue by L1so** [axkibe/lsyncd#652]
This is my configuration on `server1`, I want to sync `/var/www/sys` on `server1` to `/var/www/sys` on `server2`. 

```bash
settings {
    logfile = "/var/log/lsyncd/lsyncd.log",
    statusFile = "/var/log/lsyncd/lsyncd.status",
    statusInterval = 5,
    nodaemon = false
}
sync {
    default.rsyncssh,
    delete = 'running',
    source = "/var/www/sys",
    host = "user@xxx.xxx.xx.xx",
    targetdir = "/var/www/sys",
    rsync = {
        rsh = "/usr/bin/ssh -l user -i /home/user/.ssh/id_rsa -p 2912 -o StrictHostKeyChecking=no",
        timeout = 1500,
        archive = true,
        update = true,
        perms = true,
        owner = true
    },
}
``` 

If I created a file on `server1`, it will automatically sync to `server2`. But if I delete the same file on `server1`, the said file on `server2` will not be deleted and will remain there. Any idea why ?

**Comment by LeonGaultier** [comment]
Sorry, i can't reproduce you problem. What i did to reproduce your issues.

- i use your configuration 1:1
- lsyncd copy 1GB large folder from server1 to server2
- i remove 1 subfolder at server1
- after few seconds lsyncd is still sync and at server2 the subfolder is remove

Is the issues described still present?
That version of lsynd do you use?

**Comment by L1so** [comment]
Still present, I have version 2.1.6
```
$ lsyncd --version
Version: 2.1.6
```

**Comment by LeonGaultier** [comment]
the last stable version is 2.2.3. please can you test this version.
