### ISSUE TITLE
 ERROR: Connection to remote host failed.

### ISSUE THREAD

**Issue by axkibe** [axkibe/lsyncd#96]
Originally filed by Phelms...@gmail.com on 2011-11-16T03:57:50

Tue Nov 15 21:46:15 2011 Error: Failure on startup of 'server1' instance.
Tue Nov 15 21:53:06 2011 Normal: Recursive startup sync: server1:/var/www/
ERROR from peer server12: Connection closed.
ERROR: Connection to remote host failed.
Finished with 2 errors.
Tue Nov 15 21:53:07 2011 Error: Failure on startup of 'server1' instance.

**Comment by 24kpure** [comment]
it is sad
