### ISSUE TITLE
lsyncd does not mirror files that are inside symlink directories.

### ISSUE THREAD

**Issue by slayerduck** [axkibe/lsyncd#98]
I'm running lsyncd 2.0.5 and i'm trying to go inside a folder that has symlinks. On the rsyncOpts i give the option "k" to threat symlinks as directories on destination. The initial rsync tranfer works but after that lsyncd does not sync any files. What should i do to make lsyncd threat the symlinks as directories?

My config:
settings = {
   statusFile = "/tmp/lsyncd_booru.status",
   nodaemon   = false,
   maxDelays  = 0,  
   maxProcesses = 10,
}

sync{
        default.rsync,
        source="/home/booru/public_html/thumbs/",
        target="/mnt/ssd/thumbs/booru/",
        rsyncOpts="-rptgoDvk",
     exclude={ "rule34", "furry", "size", }
}

**Comment by mnpenner** [comment]
This still appears to be a problem with `--copy-unsafe-links`. Is there no workaround?

My configuration is:

```lua
rsync = {
    links = true,
    times = true,
    update = false,
    compress = true,
    executability = true,
    perms = true,
    verbose = false,

    _extra = {
        "-og",
        "--chown=:developers",
        "--chmod=g+rwX,o=",
        "--info=NAME",
        "--copy-unsafe-links" -- if symlink points outside the project tree, copy the files
    }
}
```

**Comment by KingDuckZ** [comment]
Is this still not implemented, or is there in 2024 a way to make it watch inside symlinked directories as well?
